! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gas_Parameters.f90
! Time                 : Thu Jun 20 15:54:13 2024
! Working directory    : /DFS-L/DATA/carlton/srosanka/code/CMAQ_MCHEM/UTIL/mchemmech
! Equation file        : gas.kpp
! Output root filename : gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gas_Parameters

  USE gas_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 155 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 150 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 131 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 349 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 151 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1370 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1556 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 151 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_AMTNO3J = 1 
  INTEGER, PARAMETER :: ind_AAVB2J = 2 
  INTEGER, PARAMETER :: ind_AAVB3J = 3 
  INTEGER, PARAMETER :: ind_AAVB4J = 4 
  INTEGER, PARAMETER :: ind_AISO1J = 5 
  INTEGER, PARAMETER :: ind_AISO2J = 6 
  INTEGER, PARAMETER :: ind_ASQTJ = 7 
  INTEGER, PARAMETER :: ind_APOCI = 8 
  INTEGER, PARAMETER :: ind_APNCOMI = 9 
  INTEGER, PARAMETER :: ind_APOCJ = 10 
  INTEGER, PARAMETER :: ind_APNCOMJ = 11 
  INTEGER, PARAMETER :: ind_TOLU = 12 
  INTEGER, PARAMETER :: ind_DUMMY = 13 
  INTEGER, PARAMETER :: ind_MTNO3 = 14 
  INTEGER, PARAMETER :: ind_TERPNRO2 = 15 
  INTEGER, PARAMETER :: ind_FORM_PRIMARY = 16 
  INTEGER, PARAMETER :: ind_ALD2_PRIMARY = 17 
  INTEGER, PARAMETER :: ind_ACROLEIN = 18 
  INTEGER, PARAMETER :: ind_BUTADIENE13 = 19 
  INTEGER, PARAMETER :: ind_ACRO_PRIMARY = 20 
  INTEGER, PARAMETER :: ind_SULF = 21 
  INTEGER, PARAMETER :: ind_SULRXN = 22 
  INTEGER, PARAMETER :: ind_ISOPRXN = 23 
  INTEGER, PARAMETER :: ind_TRPRXN = 24 
  INTEGER, PARAMETER :: ind_SVAVB2 = 25 
  INTEGER, PARAMETER :: ind_SVAVB4 = 26 
  INTEGER, PARAMETER :: ind_SVAVB3 = 27 
  INTEGER, PARAMETER :: ind_SOAALK = 28 
  INTEGER, PARAMETER :: ind_SVAVB1 = 29 
  INTEGER, PARAMETER :: ind_BENZRO2 = 30 
  INTEGER, PARAMETER :: ind_TOLRO2 = 31 
  INTEGER, PARAMETER :: ind_XYLRO2 = 32 
  INTEGER, PARAMETER :: ind_PAHRO2 = 33 
  INTEGER, PARAMETER :: ind_SESQRXN = 34 
  INTEGER, PARAMETER :: ind_SESQ = 35 
  INTEGER, PARAMETER :: ind_AISO3J = 36 
  INTEGER, PARAMETER :: ind_AGLYJ = 37 
  INTEGER, PARAMETER :: ind_AMTHYDJ = 38 
  INTEGER, PARAMETER :: ind_AOLGAJ = 39 
  INTEGER, PARAMETER :: ind_AOLGBJ = 40 
  INTEGER, PARAMETER :: ind_PCSOARXN = 41 
  INTEGER, PARAMETER :: ind_PCVOC = 42 
  INTEGER, PARAMETER :: ind_HGIIAER = 43 
  INTEGER, PARAMETER :: ind_HGIIGAS = 44 
  INTEGER, PARAMETER :: ind_HG = 45 
  INTEGER, PARAMETER :: ind_MSA = 46 
  INTEGER, PARAMETER :: ind_CL2 = 47 
  INTEGER, PARAMETER :: ind_ASO4J = 48 
  INTEGER, PARAMETER :: ind_IEPOXP = 49 
  INTEGER, PARAMETER :: ind_ACLI = 50 
  INTEGER, PARAMETER :: ind_ACLJ = 51 
  INTEGER, PARAMETER :: ind_H2NO3PIJ = 52 
  INTEGER, PARAMETER :: ind_ACLK = 53 
  INTEGER, PARAMETER :: ind_H2NO3PK = 54 
  INTEGER, PARAMETER :: ind_CLNO2 = 55 
  INTEGER, PARAMETER :: ind_O1D = 56 
  INTEGER, PARAMETER :: ind_ECH4 = 57 
  INTEGER, PARAMETER :: ind_ETHY = 58 
  INTEGER, PARAMETER :: ind_EPOX = 59 
  INTEGER, PARAMETER :: ind_BENZENE = 60 
  INTEGER, PARAMETER :: ind_HOCL = 61 
  INTEGER, PARAMETER :: ind_KET = 62 
  INTEGER, PARAMETER :: ind_HPLD = 63 
  INTEGER, PARAMETER :: ind_SO2 = 64 
  INTEGER, PARAMETER :: ind_N2O5 = 65 
  INTEGER, PARAMETER :: ind_VIVPO1 = 66 
  INTEGER, PARAMETER :: ind_PAN = 67 
  INTEGER, PARAMETER :: ind_PACD = 68 
  INTEGER, PARAMETER :: ind_CLNO3 = 69 
  INTEGER, PARAMETER :: ind_HONO = 70 
  INTEGER, PARAMETER :: ind_PNA = 71 
  INTEGER, PARAMETER :: ind_XPRP = 72 
  INTEGER, PARAMETER :: ind_ETHA = 73 
  INTEGER, PARAMETER :: ind_NTR2 = 74 
  INTEGER, PARAMETER :: ind_MEPX = 75 
  INTEGER, PARAMETER :: ind_XYLMN = 76 
  INTEGER, PARAMETER :: ind_NAPH = 77 
  INTEGER, PARAMETER :: ind_CAT1 = 78 
  INTEGER, PARAMETER :: ind_OPAN = 79 
  INTEGER, PARAMETER :: ind_ISPX = 80 
  INTEGER, PARAMETER :: ind_H2O2 = 81 
  INTEGER, PARAMETER :: ind_TOL = 82 
  INTEGER, PARAMETER :: ind_PRPA = 83 
  INTEGER, PARAMETER :: ind_ETOH = 84 
  INTEGER, PARAMETER :: ind_HCL = 85 
  INTEGER, PARAMETER :: ind_VSVPO2 = 86 
  INTEGER, PARAMETER :: ind_VSVPO3 = 87 
  INTEGER, PARAMETER :: ind_VSVPO1 = 88 
  INTEGER, PARAMETER :: ind_VLVPO1 = 89 
  INTEGER, PARAMETER :: ind_VSVOO2 = 90 
  INTEGER, PARAMETER :: ind_VSVOO3 = 91 
  INTEGER, PARAMETER :: ind_VLVOO2 = 92 
  INTEGER, PARAMETER :: ind_VLVOO1 = 93 
  INTEGER, PARAMETER :: ind_VSVOO1 = 94 
  INTEGER, PARAMETER :: ind_FACD = 95 
  INTEGER, PARAMETER :: ind_MEOH = 96 
  INTEGER, PARAMETER :: ind_HCO3 = 97 
  INTEGER, PARAMETER :: ind_PANX = 98 
  INTEGER, PARAMETER :: ind_XPAR = 99 
  INTEGER, PARAMETER :: ind_FMCL = 100 
  INTEGER, PARAMETER :: ind_CRO = 101 
  INTEGER, PARAMETER :: ind_DMS = 102 
  INTEGER, PARAMETER :: ind_ROOH = 103 
  INTEGER, PARAMETER :: ind_NTR1 = 104 
  INTEGER, PARAMETER :: ind_ACET = 105 
  INTEGER, PARAMETER :: ind_INTR = 106 
  INTEGER, PARAMETER :: ind_CRON = 107 
  INTEGER, PARAMETER :: ind_AACD = 108 
  INTEGER, PARAMETER :: ind_BZO2 = 109 
  INTEGER, PARAMETER :: ind_CO = 110 
  INTEGER, PARAMETER :: ind_TERP = 111 
  INTEGER, PARAMETER :: ind_ROR = 112 
  INTEGER, PARAMETER :: ind_APIN = 113 
  INTEGER, PARAMETER :: ind_ETH = 114 
  INTEGER, PARAMETER :: ind_TO2 = 115 
  INTEGER, PARAMETER :: ind_XLO2 = 116 
  INTEGER, PARAMETER :: ind_EPX2 = 117 
  INTEGER, PARAMETER :: ind_CLO = 118 
  INTEGER, PARAMETER :: ind_CRES = 119 
  INTEGER, PARAMETER :: ind_HNO3 = 120 
  INTEGER, PARAMETER :: ind_ISOP = 121 
  INTEGER, PARAMETER :: ind_GLY = 122 
  INTEGER, PARAMETER :: ind_XOPN = 123 
  INTEGER, PARAMETER :: ind_MGLY = 124 
  INTEGER, PARAMETER :: ind_OPEN = 125 
  INTEGER, PARAMETER :: ind_GLYD = 126 
  INTEGER, PARAMETER :: ind_IOLE = 127 
  INTEGER, PARAMETER :: ind_OPO3 = 128 
  INTEGER, PARAMETER :: ind_XO2 = 129 
  INTEGER, PARAMETER :: ind_FORM = 130 
  INTEGER, PARAMETER :: ind_XO2N = 131 
  INTEGER, PARAMETER :: ind_XO2H = 132 
  INTEGER, PARAMETER :: ind_OLE = 133 
  INTEGER, PARAMETER :: ind_CXO3 = 134 
  INTEGER, PARAMETER :: ind_ALD2 = 135 
  INTEGER, PARAMETER :: ind_ISO2 = 136 
  INTEGER, PARAMETER :: ind_ISPD = 137 
  INTEGER, PARAMETER :: ind_MEO2 = 138 
  INTEGER, PARAMETER :: ind_ALDX = 139 
  INTEGER, PARAMETER :: ind_NO2 = 140 
  INTEGER, PARAMETER :: ind_NO3 = 141 
  INTEGER, PARAMETER :: ind_CL = 142 
  INTEGER, PARAMETER :: ind_OH = 143 
  INTEGER, PARAMETER :: ind_NO = 144 
  INTEGER, PARAMETER :: ind_RO2 = 145 
  INTEGER, PARAMETER :: ind_HO2 = 146 
  INTEGER, PARAMETER :: ind_C2O3 = 147 
  INTEGER, PARAMETER :: ind_PAR = 148 
  INTEGER, PARAMETER :: ind_O3 = 149 
  INTEGER, PARAMETER :: ind_O = 150 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_M = 151 
  INTEGER, PARAMETER :: ind_H2 = 152 
  INTEGER, PARAMETER :: ind_O2 = 153 
  INTEGER, PARAMETER :: ind_CH4 = 154 
  INTEGER, PARAMETER :: ind_H2O = 155 

! Index declaration for dummy species

  INTEGER, PARAMETER :: ind_N2 = 0 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_M = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_H2O = 5 

END MODULE gas_Parameters

