! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gas_Rates.f90
! Time                 : Fri Jul  5 12:12:56 2024
! Working directory    : /DFS-L/DATA/carlton/srosanka/code/CMAQ_MCHEM/UTIL/mchemmech
! Equation file        : gas.kpp
! Output root filename : gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gas_Rates

  USE gas_Parameters
  USE gas_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


REAL(kind=dp) FUNCTION FALL_OFF ( A0,B0,C0,A1,B1,C1,CE,CF)
  IMPLICIT NONE
  REAL(kind=dp), INTENT( IN ) :: A0,B0,C0,A1,B1,C1,CE,CF
  REAL(kind=dp) K0, K1, KEND
! K0 = A0 * COEFF_FALLOFF * DEXP(B0/TEMP)* (TEMP/300.0_dp)**C0
! K1 = A1 * DEXP(B1/TEMP) * (TEMP/300.0_dp)**C1
  K0 = A0 * COEFF_FALLOFF * DEXP(B0*INV_TEMP)* (TEMP/300.0_dp)**C0
  K1 = A1 * DEXP(B1*INV_TEMP) * (TEMP/300.0_dp)**C1
  KEND = ( ( 1.0_dp + ( ( 1.0_dp / CE ) * DLOG10( K0 / K1 ) ) ** 2.0_dp ) )
  KEND = 1.0_dp / KEND
  FALL_OFF = ( K0 / ( 1.0_dp + K0/K1 ) ) * CF ** KEND
END FUNCTION FALL_OFF

REAL( kind=dp ) FUNCTION HALOGEN_FALLOFF(A1,B1,A2,B2,A3)
   IMPLICIT NONE
   REAL( kind=dp ), INTENT( IN ) :: A1
   REAL( kind=dp ), INTENT( IN ) :: B1
   REAL( kind=dp ), INTENT( IN ) :: A2
   REAL( kind=dp ), INTENT( IN ) :: B2
   REAL( kind=dp ), INTENT( IN ) :: A3
   INTRINSIC DEXP
   IF ( ( OPEN_WATER ) .AND. LSUNLIGHT ) THEN
       HALOGEN_FALLOFF = A1 * DEXP( B1 * PRESS ) + A2 * DEXP( B2 * PRESS )
       HALOGEN_FALLOFF = DMIN1( A3, HALOGEN_FALLOFF) 
       HALOGEN_FALLOFF = HALOGEN_FALLOFF * SEAWATER
   ELSE
       HALOGEN_FALLOFF = 0.0_dp
   END IF
   RETURN
END FUNCTION HALOGEN_FALLOFF

   REAL(kind=dp) FUNCTION ARR2_DP( A0,B0 )
   ! Same as ARR2 just taking A0 and B0 in dp
      REAL(kind=dp) A0,B0
      ARR2_DP =  A0 * EXP( B0/TEMP )
   END FUNCTION ARR2_DP

       REAL( kind=dp ) FUNCTION POWER_T02( A0,B0 )
         IMPLICIT NONE
! rate constant for CMAQ Arrhenuis reaction type 2
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         ! Local
         REAL( kind=dp ) :: TEMPOT300
         TEMPOT300 = TEMP / 300.0D0
         POWER_T02 =  A0 * TEMPOT300**B0
         RETURN
       END FUNCTION POWER_T02

       REAL( kind=dp ) FUNCTION ARRHENUIS_T04( A0,B0,C0 )
         IMPLICIT NONE
! rate constant for CMAQ Arrhenuis reaction type 4
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         REAL( kind=dp ), INTENT( IN ) :: C0
         ! Local:
         INTRINSIC DEXP
         REAL( kind=dp ) :: INV_TEMP
         REAL( kind=dp ) :: TEMPOT300
         INV_TEMP  = 1.0D0 / TEMP
         TEMPOT300 = TEMP / 300.0D0
         ARRHENUIS_T04 =  A0 * DEXP( B0 * INV_TEMP ) * TEMPOT300**C0
         RETURN
       END FUNCTION ARRHENUIS_T04

       REAL( kind=dp ) FUNCTION FALLOFF_T08(A0,C0,A2,C2,A3,C3)
! rate constant for CMAQ fall off reaction type 8
         IMPLICIT NONE
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: C0
         REAL( kind=dp ), INTENT( IN ) :: A2
         REAL( kind=dp ), INTENT( IN ) :: C2
         REAL( kind=dp ), INTENT( IN ) :: A3
         REAL( kind=dp ), INTENT( IN ) :: C3
         ! Local:
         REAL( kind=dp ) K0
         REAL( kind=dp ) K2
         REAL( kind=dp ) K3
         REAL( kind=dp ) :: INV_TEMP
         INTRINSIC DEXP
         INV_TEMP  = 1.0D0 / TEMP
         K0 = A0 * DEXP( C0 * INV_TEMP )
         K2 = A2 * DEXP( C2 * INV_TEMP )
         K3 = A3 * DEXP( C3 * INV_TEMP )
         K3 = K3 * COEFF_FALLOFF
         FALLOFF_T08 = K0 + K3/( 1.0D0 + K3/K2 )
         RETURN
       END FUNCTION FALLOFF_T08

       REAL( kind=dp ) FUNCTION FALLOFF_T09(A1,C1,A2,C2)
! rate constant for CMAQ fall off reaction type 9
         IMPLICIT NONE
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A1
         REAL( kind=dp ), INTENT( IN ) :: C1
         REAL( kind=dp ), INTENT( IN ) :: A2
         REAL( kind=dp ), INTENT( IN ) :: C2
         !  Local:
         REAL( kind=dp ) K1
         REAL( kind=dp ) K2
         REAL( kind=dp ) :: INV_TEMP
         INTRINSIC DEXP
         INV_TEMP  = 1.0D0 / TEMP
         K1 = A1 * DEXP( C1 * INV_TEMP )
         K2 = A2 * DEXP( C2 * INV_TEMP )
         FALLOFF_T09 = K1 + K2 * COEFF_FALLOFF
         RETURN
       END FUNCTION FALLOFF_T09
       REAL( kind=dp ) FUNCTION FALLOFF_T10(A0,B0,C0,A1,B1,C1,CE,CF)
         IMPLICIT NONE
! rate constant for CMAQ fall off reaction type 10
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         REAL( kind=dp ), INTENT( IN ) :: C0
         REAL( kind=dp ), INTENT( IN ) :: A1
         REAL( kind=dp ), INTENT( IN ) :: B1
         REAL( kind=dp ), INTENT( IN ) :: C1
         REAL( kind=dp ), INTENT( IN ) :: CE
         REAL( kind=dp ), INTENT( IN ) :: CF
         ! Local:
         REAL( kind=dp ) K0
         REAL( kind=dp ) K1
         REAL( kind=dp ) KEND
         REAL( kind=dp ) :: INV_TEMP
         REAL( kind=dp ) :: TEMPOT300
         INV_TEMP  = 1.0D0 / TEMP
         TEMPOT300 = TEMP / 300.0D0
         K0 = A0 * COEFF_FALLOFF * DEXP(B0*INV_TEMP)* TEMPOT300**C0
         K1 = A1 * DEXP(B1*INV_TEMP) * TEMPOT300**C1
         KEND = ( ( 1.0D0 + ( ( 1.0D0 / CE ) * DLOG10( K0 / K1 ) ) ** 2.0D0 ) )
         KEND = 1.0D0 / KEND
         FALLOFF_T10 = ( K0 / ( 1.0D0 + K0/K1 ) ) * CF ** KEND
         RETURN
       END FUNCTION FALLOFF_T10

! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE gas_Parameters
      !USE gas_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


  USE MCHEM_CLOUDS, ONLY: UPDATE_GM1_GM2

REAL(dp)  :: FALLOFF_T10_R4
REAL(dp)  :: FALLOFF_T10_R6
REAL(dp)  :: FALLOFF_T10_R17
REAL(dp)  :: FALLOFF_T10_R36
REAL(dp)  :: FALLOFF_T10_R37
REAL(dp)  :: FALLOFF_T10_R40
REAL(dp)  :: FALLOFF_T10_R45
REAL(dp)  :: FALLOFF_T08_R46
REAL(dp)  :: FALLOFF_T10_R48
REAL(dp)  :: FALLOFF_T10_R49
REAL(dp)  :: FALLOFF_T10_R52
REAL(dp)  :: FALLOFF_T10_R54
REAL(dp)  :: FALLOFF_T10_R55
REAL(dp)  :: FALLOFF_T10_R136
REAL(dp)  :: FALLOFF_T10_R138
REAL(dp)  :: FALLOFF_T10_R142
REAL(dp)  :: FALLOFF_T10_R217
REAL(dp)  :: FALLOFF_T10_R219
REAL(dp)  :: FALLOFF_T10_CL28
REAL(dp)  :: FALLOFF_T10_DMS2

FALLOFF_T10_R4 = FALLOFF_T10( 1.0000D-31,-0.0000D+00, &
-1.6000D+00,5.0000D-11, &
-0.0000D+00,3.0000D-01, &
8.4000D-01,8.5000D-01)
FALLOFF_T10_R6 = FALLOFF_T10( 1.3000D-31,-0.0000D+00, &
-1.5000D+00,2.3000D-11, &
-0.0000D+00,2.4000D-01, &
1.0300D+00,6.0000D-01)
FALLOFF_T10_R17 = FALLOFF_T10( 9.0000D-31,-0.0000D+00, &
-3.2000D+00,3.9000D-11, &
-0.0000D+00,-4.7000D-01, &
1.2300D+00,4.2000D-01)
FALLOFF_T10_R36 = FALLOFF_T10( 3.6000D-30,-0.0000D+00, &
-4.1000D+00,1.9000D-12, &
-0.0000D+00,2.0000D-01, &
1.3300D+00,3.5000D-01)
FALLOFF_T10_R37 = FALLOFF_T10( 1.3000D-03,-1.1000D+04, &
-3.5000D+00,9.7000D+14, &
-1.1080D+04,1.0000D-01, &
1.3300D+00,3.5000D-01)
FALLOFF_T10_R40 = FALLOFF_T10( 7.4000D-31,-0.0000D+00, &
-2.4000D+00,3.3000D-11, &
-0.0000D+00,-3.0000D-01, &
8.7000D-01,8.1000D-01)
FALLOFF_T10_R45 = FALLOFF_T10( 1.8000D-30,-0.0000D+00, &
-3.0000D+00,2.8000D-11, &
-0.0000D+00,1.0000D+00, &
1.0000D+00,6.0000D-01)
FALLOFF_T08_R46 = FALLOFF_T08( 2.4000D-14,4.6000D+02, &
2.7000D-17,2.1990D+03, &
6.5000D-34,1.3350D+03 )
FALLOFF_T10_R48 = FALLOFF_T10( 1.4000D-31,-0.0000D+00, &
-3.1000D+00,4.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.2600D+00,4.0000D-01)
FALLOFF_T10_R49 = FALLOFF_T10( 4.1000D-05,-1.0650D+04, &
1.0000D+00,6.0000D+15, &
-1.1170D+04,1.0000D+00, &
1.2600D+00,4.0000D-01)
FALLOFF_T10_R52 = FALLOFF_T10( 2.8000D-31,-0.0000D+00, &
-2.6000D+00,2.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.1000D+00,5.3000D-01)
FALLOFF_T10_R54 = FALLOFF_T10( 3.6100D-28,-0.0000D+00, &
-6.8700D+00,1.2400D-11, &
-0.0000D+00,-1.1050D+00, &
1.4100D+00,3.0000D-01)
FALLOFF_T10_R55 = FALLOFF_T10( 1.1000D-05,-1.0100D+04, &
1.0000D+00,1.9000D+17, &
-1.4100D+04,1.0000D+00, &
1.4100D+00,3.0000D-01)
FALLOFF_T10_R136 = FALLOFF_T10( 5.0000D-30,-0.0000D+00, &
-1.5000D+00,1.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.3000D+00,3.7000D-01)
FALLOFF_T10_R138 = FALLOFF_T10( 8.6000D-29,-0.0000D+00, &
-3.1000D+00,9.0000D-12, &
-0.0000D+00,-8.5000D-01, &
1.1500D+00,4.8000D-01)
FALLOFF_T10_R142 = FALLOFF_T10( 8.0000D-27,-0.0000D+00, &
-3.5000D+00,3.0000D-11, &
-0.0000D+00,-1.0000D+00, &
1.1300D+00,5.0000D-01)
FALLOFF_T10_R217 = FALLOFF_T10( 2.3700D-21,-0.0000D+00, &
1.0000D+00,4.0700D-01, &
-0.0000D+00,-8.0000D+00, &
1.0000D+00,4.1000D-01)
FALLOFF_T10_R219 = FALLOFF_T10( 4.8100D-20,-0.0000D+00, &
1.0000D+00,4.0700D-01, &
-0.0000D+00,-8.0000D+00, &
1.0000D+00,4.1000D-01)
FALLOFF_T10_CL28 = FALLOFF_T10( 1.8000D-31,-0.0000D+00, &
-3.4000D+00,1.5000D-11, &
-0.0000D+00,-1.9000D+00, &
1.0000D+00,6.0000D-01)
FALLOFF_T10_DMS2 = FALLOFF_T10( 1.9900D-39,5.2700D+03, &
1.0000D+00,1.2600D-10, &
-3.4000D+02,1.0000D+00, &
1.0000D+00,1.0000D+00)


! End INLINED RCONST

! Constant rate moved to initialize :   RCONST(1) = (1.0*RJCELL(IJ_NO2_IUPAC10))
! Constant rate moved to initialize :   RCONST(2) = (POWER_T02(6.0000D-34,-2.6000D+00))
! Constant rate moved to initialize :   RCONST(3) = (ARR2_DP(2.0700D-12,-1.4000D+03))
  RCONST(4) = (FALLOFF_T10_R4)
! Constant rate moved to initialize :   RCONST(5) = (ARR2_DP(5.1000D-12,1.9800D+02))
  RCONST(6) = (FALLOFF_T10_R6)
! Constant rate moved to initialize :   RCONST(7) = (ARR2_DP(8.0000D-12,-2.0600D+03))
! Constant rate moved to initialize :   RCONST(8) = (1.0*RJCELL(IJ_O3_O3P_IUPAC10))
! Constant rate moved to initialize :   RCONST(9) = (1.0*RJCELL(IJ_O3_O1D_IUPAC10))
! Constant rate moved to initialize :   RCONST(10) = (ARR2_DP(2.2300D-11,1.1500D+02))
! RCONST(11) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(12) = (ARR2_DP(1.7000D-12,-9.4000D+02))
! Constant rate moved to initialize :   RCONST(13) = (ARRHENUIS_T04(2.0300D-16,6.9300D+02,4.5700D+00))
! Constant rate moved to initialize :   RCONST(14) = (ARR2_DP(2.4000D-11,1.1000D+02))
! Constant rate moved to initialize :   RCONST(15) = (ARR2_DP(3.0000D-11,2.0000D+02))
! Constant rate moved to initialize :   RCONST(16) = (ARRHENUIS_T04(6.2000D-14,9.4500D+02,2.6000D+00))
  RCONST(17) = (FALLOFF_T10_R17)
! Constant rate moved to initialize :   RCONST(18) = (ARR2_DP(4.8000D-11,2.5000D+02))
  RCONST(19) = (FALLOFF_T09(2.2000D-13,6.0000D+02,1.9000D-33,9.8000D+02))
  RCONST(20) = (FALLOFF_T09(3.0800D-34,2.8000D+03,2.6600D-54,3.1800D+03))
! Constant rate moved to initialize :   RCONST(21) = (1.0*RJCELL(IJ_H2O2_IUPAC10))
! RCONST(22) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(23) = (ARR2_DP(1.4000D-12,-2.0000D+03))
! Constant rate moved to initialize :   RCONST(24) = (ARR2_DP(4.2500D-39,6.6400D+02))
! Constant rate moved to initialize :   RCONST(25) = (ARR2_DP(3.4500D-12,2.7000D+02))
! Constant rate moved to initialize :   RCONST(26) = (ARR2_DP(1.4000D-13,-2.4700D+03))
! Constant rate moved to initialize :   RCONST(27) = (1.0*RJCELL(IJ_NO3NO2_06))
! Constant rate moved to initialize :   RCONST(28) = (1.0*RJCELL(IJ_NO3NO_06))
! Constant rate moved to initialize :   RCONST(29) = (ARR2_DP(1.8000D-11,1.1000D+02))
! Constant rate moved to initialize :   RCONST(30) = (ARR2_DP(4.5000D-14,-1.2600D+03))
! RCONST(31) = constant rate coefficient
! RCONST(32) = constant rate coefficient
! RCONST(33) = constant rate coefficient
! RCONST(34) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(35) = (ARR2_DP(8.5000D-13,-2.4500D+03))
  RCONST(36) = (FALLOFF_T10_R36)
  RCONST(37) = (FALLOFF_T10_R37)
! Constant rate moved to initialize :   RCONST(38) = (1.0*RJCELL(IJ_N2O5_IUPAC10))
! RCONST(39) = constant rate coefficient
  RCONST(40) = (FALLOFF_T10_R40)
! Constant rate moved to initialize :   RCONST(41) = (5.0000D-40)
! RCONST(42) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(43) = (1.0*RJCELL(IJ_HONO_IUPAC10))
! Constant rate moved to initialize :   RCONST(44) = (ARR2_DP(2.5000D-12,2.6000D+02))
  RCONST(45) = (FALLOFF_T10_R45)
  RCONST(46) = (FALLOFF_T08_R46)
! Constant rate moved to initialize :   RCONST(47) = (1.0*RJCELL(IJ_HNO3_IUPAC10))
  RCONST(48) = (FALLOFF_T10_R48)
  RCONST(49) = (FALLOFF_T10_R49)
! Constant rate moved to initialize :   RCONST(50) = (1.0*RJCELL(IJ_PNA_IUPAC10))
! Constant rate moved to initialize :   RCONST(51) = (ARR2_DP(3.2000D-13,6.9000D+02))
  RCONST(52) = (FALLOFF_T10_R52)
! Constant rate moved to initialize :   RCONST(53) = (ARR2_DP(7.5000D-12,2.9000D+02))
  RCONST(54) = (FALLOFF_T10_R54)
  RCONST(55) = (FALLOFF_T10_R55)
! Constant rate moved to initialize :   RCONST(56) = (1.0*RJCELL(IJ_PAN_IUPAC10))
! Constant rate moved to initialize :   RCONST(57) = (ARR2_DP(3.1400D-12,5.8000D+02))
! Constant rate moved to initialize :   RCONST(58) = (ARR2_DP(4.4000D-13,1.0700D+03))
! Constant rate moved to initialize :   RCONST(59) = (ARR2_DP(2.9000D-12,5.0000D+02))
  RCONST(60) = (1.00E+0*RCONST(59))
! Constant rate moved to initialize :   RCONST(61) = (ARR2_DP(6.7000D-12,3.4000D+02))
  RCONST(62) = (8.4E-1*RCONST(54))
  RCONST(63) = (8.4E-1*RCONST(55))
! Constant rate moved to initialize :   RCONST(64) = (1.0*RJCELL(IJ_PAN_IUPAC10))
  RCONST(65) = (1.00E+0*RCONST(57))
  RCONST(66) = (1.00E+0*RCONST(58))
  RCONST(67) = (1.00E+0*RCONST(59))
! Constant rate moved to initialize :   RCONST(68) = (ARR2_DP(2.4000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(69) = (ARR2_DP(4.8000D-13,8.0000D+02))
! Constant rate moved to initialize :   RCONST(70) = (ARR2_DP(6.5000D-14,5.0000D+02))
! Constant rate moved to initialize :   RCONST(71) = (ARR2_DP(2.3000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(72) = (ARR2_DP(3.8000D-13,7.8000D+02))
! Constant rate moved to initialize :   RCONST(73) = (ARR2_DP(2.0000D-12,5.0000D+02))
  RCONST(74) = (1.0*RCONST(70))
! Constant rate moved to initialize :   RCONST(75) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(76) = (ARR2_DP(6.8000D-13,8.0000D+02))
  RCONST(77) = (1.0*RCONST(58))
  RCONST(78) = (1.00E+0*RCONST(70))
  RCONST(79) = (1.00E+0*RCONST(75))
  RCONST(80) = (1.00E+0*RCONST(76))
  RCONST(81) = (1.0*RCONST(58))
  RCONST(82) = (1.00E+0*RCONST(70))
  RCONST(83) = (1.00E+0*RCONST(75))
  RCONST(84) = (1.00E+0*RCONST(76))
  RCONST(85) = (1.0*RCONST(58))
  RCONST(86) = (1.00E+0*RCONST(70))
! Constant rate moved to initialize :   RCONST(87) = (ARR2_DP(5.3000D-12,1.9000D+02))
! Constant rate moved to initialize :   RCONST(88) = (1.0*RJCELL(IJ_MEPX_IUPAC10))
! Constant rate moved to initialize :   RCONST(89) = (ARR2_DP(5.3000D-12,1.9000D+02))
! Constant rate moved to initialize :   RCONST(90) = (1.0*RJCELL(IJ_MEPX_IUPAC10))
! RCONST(91) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(92) = (1.0*RJCELL(IJ_NTR_IUPAC10))
! RCONST(93) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(94) = (ARR2_DP(4.0000D-14,8.5000D+02))
! Constant rate moved to initialize :   RCONST(95) = (ARR2_DP(5.3000D-12,1.9000D+02))
! Constant rate moved to initialize :   RCONST(96) = (ARR2_DP(5.4000D-12,1.3500D+02))
! Constant rate moved to initialize :   RCONST(97) = (1.0*RJCELL(IJ_FORM_R_IUPAC13))
! Constant rate moved to initialize :   RCONST(98) = (1.0*RJCELL(IJ_FORM_M_IUPAC13))
! Constant rate moved to initialize :   RCONST(99) = (ARR2_DP(3.4000D-11,-1.6000D+03))
! RCONST(100) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(101) = (ARR2_DP(9.7000D-15,6.2500D+02))
! Constant rate moved to initialize :   RCONST(102) = (ARR2_DP(2.4000D+12,-7.0000D+03))
! RCONST(103) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(104) = (ARR2_DP(5.6000D-15,2.3000D+03))
! Constant rate moved to initialize :   RCONST(105) = (ARR2_DP(1.8000D-11,-1.1000D+03))
! Constant rate moved to initialize :   RCONST(106) = (ARR2_DP(4.7000D-12,3.4500D+02))
! Constant rate moved to initialize :   RCONST(107) = (ARR2_DP(1.4000D-12,-1.8600D+03))
! Constant rate moved to initialize :   RCONST(108) = (1.0*RJCELL(IJ_ALD2_R_IUPAC13))
! Constant rate moved to initialize :   RCONST(109) = (ARR2_DP(1.3000D-11,-8.7000D+02))
! Constant rate moved to initialize :   RCONST(110) = (ARR2_DP(4.9000D-12,4.0500D+02))
! RCONST(111) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(112) = (1.0*RJCELL(IJ_ALDX_R_IUPAC13))
! RCONST(113) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(114) = (1.0*RJCELL(IJ_GLYD_IUPAC13))
  RCONST(115) = (1.00E+0*RCONST(107))
! Constant rate moved to initialize :   RCONST(116) = (ARR2_DP(3.1000D-12,3.4000D+02))
! Constant rate moved to initialize :   RCONST(117) = (1.0*RJCELL(IJ_GLY_R_IUPAC13))
! RCONST(118) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(119) = (1.0*RJCELL(IJ_MGLY_IUPAC10))
! RCONST(120) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(121) = (ARR2_DP(1.9000D-12,5.7500D+02))
! Constant rate moved to initialize :   RCONST(122) = (ARR2_DP(7.7000D-12,-2.1000D+03))
  RCONST(123) = (FALLOFF_T09(1.4400D-13,-0.0000D+00,3.4300D-33,-0.0000D+00))
! Constant rate moved to initialize :   RCONST(124) = (ARR2_DP(1.8500D-12,-1.6900D+03))
! Constant rate moved to initialize :   RCONST(125) = (ARR2_DP(6.9000D-12,-1.0000D+03))
! Constant rate moved to initialize :   RCONST(126) = (ARR2_DP(2.8500D-12,-3.4500D+02))
! Constant rate moved to initialize :   RCONST(127) = (ARR2_DP(3.0000D-12,2.0000D+01))
! Constant rate moved to initialize :   RCONST(128) = (1.0*RJCELL(IJ_KET_IUPAC10))
! Constant rate moved to initialize :   RCONST(129) = (1.0*RJCELL(IJ_ACET_IUPAC10))
! Constant rate moved to initialize :   RCONST(130) = (ARR2_DP(1.4100D-12,-6.2060D+02))
! Constant rate moved to initialize :   RCONST(131) = (ARR2_DP(7.6000D-12,-5.8500D+02))
! RCONST(132) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(133) = (ARR2_DP(5.7000D+12,-5.7800D+03))
! Constant rate moved to initialize :   RCONST(134) = (ARR2_DP(1.5000D-14,-2.0000D+02))
! Constant rate moved to initialize :   RCONST(135) = (ARR2_DP(8.6000D-12,4.0000D+02))
  RCONST(136) = (FALLOFF_T10_R136)
! Constant rate moved to initialize :   RCONST(137) = (ARR2_DP(1.0400D-11,-7.9200D+02))
  RCONST(138) = (FALLOFF_T10_R138)
! Constant rate moved to initialize :   RCONST(139) = (ARR2_DP(6.8200D-15,-2.5000D+03))
! Constant rate moved to initialize :   RCONST(140) = (ARR2_DP(3.3000D-12,-2.8800D+03))
! Constant rate moved to initialize :   RCONST(141) = (ARR2_DP(1.0000D-11,-2.8000D+02))
  RCONST(142) = (FALLOFF_T10_R142)
! Constant rate moved to initialize :   RCONST(143) = (ARR2_DP(5.5000D-15,-1.8800D+03))
! Constant rate moved to initialize :   RCONST(144) = (ARR2_DP(4.6000D-13,-1.1550D+03))
! RCONST(145) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(146) = (ARR2_DP(1.0500D-11,5.1900D+02))
! Constant rate moved to initialize :   RCONST(147) = (ARR2_DP(4.7000D-15,-1.0130D+03))
! RCONST(148) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(149) = (ARR2_DP(2.7000D-11,3.9000D+02))
! RCONST(150) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(151) = (ARR2_DP(2.3900D-12,3.6500D+02))
! Constant rate moved to initialize :   RCONST(152) = (ARR2_DP(7.4300D-13,7.0000D+02))
  RCONST(153) = (1.00E+0*RCONST(58))
  RCONST(154) = (1.0*RCONST(70))
! Constant rate moved to initialize :   RCONST(155) = (ARR2_DP(3.3000D+09,-8.3000D+03))
! Constant rate moved to initialize :   RCONST(156) = (ARR2_DP(1.0300D-14,-1.9950D+03))
! Constant rate moved to initialize :   RCONST(157) = (ARR2_DP(3.0300D-12,-4.4800D+02))
! Constant rate moved to initialize :   RCONST(158) = (ARR2_DP(5.5800D-12,5.1100D+02))
! Constant rate moved to initialize :   RCONST(159) = (ARR2_DP(3.8800D-15,-1.7700D+03))
! Constant rate moved to initialize :   RCONST(160) = (ARR2_DP(4.1000D-12,-1.8600D+03))
! Constant rate moved to initialize :   RCONST(161) = (1.0*RJCELL(IJ_ISPD))
! Constant rate moved to initialize :   RCONST(162) = (ARR2_DP(2.2300D-11,3.7200D+02))
! Constant rate moved to initialize :   RCONST(163) = (1.0*RJCELL(IJ_HPALD))
! Constant rate moved to initialize :   RCONST(164) = (ARR2_DP(6.0000D-12,-1.8600D+03))
! Constant rate moved to initialize :   RCONST(165) = (ARR2_DP(5.7800D-11,-4.0000D+02))
! Constant rate moved to initialize :   RCONST(166) = (ARR2_DP(7.4300D-13,7.0000D+02))
! Constant rate moved to initialize :   RCONST(167) = (ARR2_DP(2.3900D-12,3.6500D+02))
  RCONST(168) = (1.0*RCONST(58))
  RCONST(169) = (1.0*RCONST(70))
! RCONST(170) = constant rate coefficient
! RCONST(171) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(172) = (ARR2_DP(1.5000D-11,4.4900D+02))
! Constant rate moved to initialize :   RCONST(173) = (ARR2_DP(1.2000D-15,-8.2100D+02))
! Constant rate moved to initialize :   RCONST(174) = (ARR2_DP(3.7000D-12,1.7500D+02))
! RCONST(175) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(176) = (ARR2_DP(1.5000D-11,4.4900D+02))
! Constant rate moved to initialize :   RCONST(177) = (ARR2_DP(1.2000D-15,-8.2100D+02))
! Constant rate moved to initialize :   RCONST(178) = (ARR2_DP(3.7000D-12,1.7500D+02))
! Constant rate moved to initialize :   RCONST(179) = (ARR2_DP(2.3000D-12,-1.9000D+02))
! Constant rate moved to initialize :   RCONST(180) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(181) = (1.0*RCONST(58))
! Constant rate moved to initialize :   RCONST(182) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(183) = (1.0*RCONST(70))
! Constant rate moved to initialize :   RCONST(184) = (ARR2_DP(1.8000D-12,3.4000D+02))
! Constant rate moved to initialize :   RCONST(185) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(186) = (1.0*RCONST(58))
! Constant rate moved to initialize :   RCONST(187) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(188) = (1.0*RCONST(70))
! RCONST(189) = constant rate coefficient
! RCONST(190) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(191) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(192) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(193) = (1.0*RCONST(58))
  RCONST(194) = (1.0*RCONST(70))
! Constant rate moved to initialize :   RCONST(195) = (ARR2_DP(1.7000D-12,9.5000D+02))
! RCONST(196) = constant rate coefficient
! RCONST(197) = constant rate coefficient
! RCONST(198) = constant rate coefficient
! RCONST(199) = constant rate coefficient
! RCONST(200) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(201) = (1.0*RJCELL(IJ_NTR_IUPAC10))
! Constant rate moved to initialize :   RCONST(202) = (0.05*RJCELL(IJ_NO2_IUPAC10))
! RCONST(203) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(204) = (ARR2_DP(1.0800D-16,-5.0000D+02))
! RCONST(205) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(206) = (0.028*RJCELL(IJ_NO2_IUPAC10))
! RCONST(207) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(208) = (ARR2_DP(5.4000D-17,-5.0000D+02))
! RCONST(209) = constant rate coefficient
! RCONST(210) = constant rate coefficient
! RCONST(211) = constant rate coefficient
  RCONST(212) = (1.00E+0*RCONST(61))
  RCONST(213) = (1.00E+0*RCONST(62))
  RCONST(214) = (1.00E+0*RCONST(63))
  RCONST(215) = (1.00E+0*RCONST(57))
  RCONST(216) = (1.00E+0*RCONST(59))
  RCONST(217) = (1.00E+0*RCONST(58))
! RCONST(218) = constant rate coefficient
! RCONST(219) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(220) = (ARR2_DP(1.8500D-12,-1.6900D+03))
  RCONST(221) = (FALLOFF_T10_R217)
! RCONST(222) = constant rate coefficient
  RCONST(223) = (FALLOFF_T10_R219)
! RCONST(224) = constant rate coefficient
! RCONST(225) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(226) = (1.0*RJCELL(IJ_CL2_IUPAC04))
! Constant rate moved to initialize :   RCONST(227) = (1.0*RJCELL(IJ_HOCL_IUPAC04))
! Constant rate moved to initialize :   RCONST(228) = (ARR2_DP(2.3000D-11,-2.0000D+02))
! RCONST(229) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(230) = (ARR2_DP(6.4000D-12,2.9000D+02))
! Constant rate moved to initialize :   RCONST(231) = (ARR2_DP(2.2000D-12,3.4000D+02))
! Constant rate moved to initialize :   RCONST(232) = (ARR2_DP(3.2000D-12,-1.1000D+02))
! RCONST(233) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(234) = (1.0*RJCELL(IJ_FMCL_IUPAC04))
! Constant rate moved to initialize :   RCONST(235) = (ARR2_DP(6.6000D-12,-1.2400D+03))
! RCONST(236) = constant rate coefficient
! RCONST(237) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(238) = (ARR2_DP(8.3000D-11,-1.0000D+02))
! RCONST(239) = constant rate coefficient
! RCONST(240) = constant rate coefficient
! RCONST(241) = constant rate coefficient
! RCONST(242) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(243) = (ARR2_DP(8.2000D-11,-3.4000D+01))
! RCONST(244) = constant rate coefficient
! RCONST(245) = constant rate coefficient
! RCONST(246) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(247) = (ARR2_DP(8.2000D-11,4.5000D+01))
! Constant rate moved to initialize :   RCONST(248) = (ARRHENUIS_T04(6.5800D-13,5.8000D+01,1.1600D+00))
! RCONST(249) = constant rate coefficient
! RCONST(250) = constant rate coefficient
! RCONST(251) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(252) = (1.0*RJCELL(IJ_CLNO2_IUPAC13))
  RCONST(253) = (FALLOFF_T10_CL28)
! Constant rate moved to initialize :   RCONST(254) = (1.0*RJCELL(IJ_CLONO2_1))
! Constant rate moved to initialize :   RCONST(255) = (1.0*RJCELL(IJ_CLONO2_2))
! Constant rate moved to initialize :   RCONST(256) = (1.0*KHETCELL(IK_HETERO_CLNO3_WAI))
! Constant rate moved to initialize :   RCONST(257) = (1.0*KHETCELL(IK_HETERO_CLNO3_WAJ))
! Constant rate moved to initialize :   RCONST(258) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(259) = (ARR2_DP(1.9000D-13,1.3000D+03))
! Constant rate moved to initialize :   RCONST(260) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(261) = (ARR2_DP(1.9000D-13,1.3000D+03))
! Constant rate moved to initialize :   RCONST(262) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(263) = (ARR2_DP(1.9000D-13,1.3000D+03))
! RCONST(264) = constant rate coefficient
! RCONST(265) = constant rate coefficient
! RCONST(266) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(267) = (ARR2_DP(2.7000D-12,3.6000D+02))
! Constant rate moved to initialize :   RCONST(268) = (ARR2_DP(1.9000D-13,1.3000D+03))
! Constant rate moved to initialize :   RCONST(269) = (ARR2_DP(2.7000D-12,3.7400D+02))
! Constant rate moved to initialize :   RCONST(270) = (1.4*KHETCELL(IK_HETERO_NTR2))
! Constant rate moved to initialize :   RCONST(271) = (1.0*KHETCELL(IK_HETERO_N2O5IJ))
! Constant rate moved to initialize :   RCONST(272) = (1.0*KHETCELL(IK_HETERO_N2O5K))
! Constant rate moved to initialize :   RCONST(273) = (1.0*KHETCELL(IK_HETERO_H2NO3PAIJ))
! Constant rate moved to initialize :   RCONST(274) = (1.0*KHETCELL(IK_HETERO_H2NO3PAK))
! Constant rate moved to initialize :   RCONST(275) = (1.0*KHETCELL(IK_HETERO_H2NO3PBIJ)/CAIR)
! Constant rate moved to initialize :   RCONST(276) = (1.0*KHETCELL(IK_HETERO_H2NO3PBIJ)/CAIR)
! Constant rate moved to initialize :   RCONST(277) = (1.0*KHETCELL(IK_HETERO_H2NO3PBK)/CAIR)
! Constant rate moved to initialize :   RCONST(278) = (1.0*KHETCELL(IK_HETERO_NO2))
  RCONST(279) = (HALOGEN_FALLOFF(6.7006D-11,1.0743D+01,3.4153D-08,-6.7130D-01,2.0000D-06))
! Constant rate moved to initialize :   RCONST(280) = (1.0*KHETCELL(IK_HETERO_IEPOX))
! Constant rate moved to initialize :   RCONST(281) = (1.0*KHETCELL(IK_HETERO_IEPOXOS)/CAIR)
! Constant rate moved to initialize :   RCONST(282) = (1.0*KHETCELL(IK_HETERO_TETROL))
! Constant rate moved to initialize :   RCONST(283) = (1.0*KHETCELL(IK_HETERO_GLY))
! Constant rate moved to initialize :   RCONST(284) = (1.0*KHETCELL(IK_HETERO_MGLY))
! Constant rate moved to initialize :   RCONST(285) = (ARR2_DP(2.6000D-12,3.8000D+02))
! Constant rate moved to initialize :   RCONST(286) = (ARR2_DP(2.6500D-13,1.3000D+03))
! RCONST(287) = constant rate coefficient
! RCONST(288) = constant rate coefficient
! RCONST(289) = constant rate coefficient
! RCONST(290) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(291) = (1.0*RJCELL(IJ_IC3ONO2))
! RCONST(292) = constant rate coefficient
! RCONST(293) = constant rate coefficient
! RCONST(294) = constant rate coefficient
! RCONST(295) = constant rate coefficient
! RCONST(296) = constant rate coefficient
! RCONST(297) = constant rate coefficient
! RCONST(298) = constant rate coefficient
! RCONST(299) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(300) = (1.0*KHETCELL(IK_HETERO_PNCOMLI)/CAIR)
! RCONST(301) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(302) = (1.0*KHETCELL(IK_HETERO_PNCOMLJ)/CAIR)
! RCONST(303) = constant rate coefficient
! RCONST(304) = constant rate coefficient
! RCONST(305) = constant rate coefficient
! RCONST(306) = constant rate coefficient
! RCONST(307) = constant rate coefficient
! RCONST(308) = constant rate coefficient
! RCONST(309) = constant rate coefficient
! RCONST(310) = constant rate coefficient
! RCONST(311) = constant rate coefficient
! RCONST(312) = constant rate coefficient
! RCONST(313) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(314) = (ARR2_DP(5.4000D-12,1.3500D+02))
! RCONST(315) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(316) = (ARR2_DP(3.4000D-11,-1.6000D+03))
! Constant rate moved to initialize :   RCONST(317) = (1.0*RJCELL(IJ_FORM_R_IUPAC13))
! Constant rate moved to initialize :   RCONST(318) = (1.0*RJCELL(IJ_FORM_M_IUPAC13))
! Constant rate moved to initialize :   RCONST(319) = (ARR2_DP(8.2000D-11,-3.4000D+01))
! Constant rate moved to initialize :   RCONST(320) = (ARR2_DP(4.7000D-12,3.4500D+02))
! Constant rate moved to initialize :   RCONST(321) = (ARR2_DP(1.4000D-12,-1.8600D+03))
! Constant rate moved to initialize :   RCONST(322) = (ARR2_DP(1.8000D-11,-1.1000D+03))
! Constant rate moved to initialize :   RCONST(323) = (1.0*RJCELL(IJ_ALD2_R_IUPAC13))
! RCONST(324) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(325) = (ARR2_DP(1.4800D-11,4.4800D+02))
! Constant rate moved to initialize :   RCONST(326) = (ARR2_DP(1.3400D-14,-2.2830D+03))
! RCONST(327) = constant rate coefficient
! RCONST(328) = constant rate coefficient
! RCONST(329) = constant rate coefficient
! RCONST(330) = constant rate coefficient
! RCONST(331) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(332) = (1.0*RJCELL(IJ_ACRO_09))
! RCONST(333) = constant rate coefficient
! RCONST(334) = constant rate coefficient
! RCONST(335) = constant rate coefficient
! RCONST(336) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(337) = (1.0*RJCELL(IJ_ACRO_09))
! RCONST(338) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(339) = (ARR2_DP(1.8000D-12,3.4000D+02))
! RCONST(340) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(341) = (ARR2_DP(2.1100D-18,-1.2565D+03))
! RCONST(342) = constant rate coefficient
! RCONST(343) = constant rate coefficient
! RCONST(344) = constant rate coefficient
! Constant rate moved to initialize :   RCONST(345) = (ARR2_DP(2.2500D-33,6.8000D+02))
! Constant rate moved to initialize :   RCONST(346) = (ARR2_DP(1.1200D-11,-2.5000D+02))
  RCONST(347) = (FALLOFF_T10_DMS2)
! Constant rate moved to initialize :   RCONST(348) = (ARR2_DP(1.9000D-13,5.2000D+02))
! Constant rate moved to initialize :   RCONST(349) = (ARR2_DP(3.4000D-13,2.0810D+03))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE gas_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gas_Rates

