! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gas_Global.F90
! Equation file        : gas.kpp
! Output root filename : gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gas_Global

  USE gas_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT, LU_NONZERO
  PUBLIC
  SAVE


! Declaration of global variables

! ~~~ If you are using KPP within an OpenMP parallel environment,
! ~~~ then these variables must be declared THREADPRIVATE.  This means
! ~~~ that the compiler will make a private copy of these variables
! ~~~ (in stack memory) for each execution thread.  At the end of
! ~~~ the OpenMP parallel loop, these variables will be finalized,
! ~~~ and their memory deallocated.
! ~~~
! ~~~ NOTE: Because the OpenMP commands all begin with a comment
! ~~~ character, they will be ignored unless the code is compiled
! ~~~ with OpenMP parallelization turned on.

! C - Concentration of all species
  REAL(kind=dp), TARGET :: C(NSPEC)
  !$OMP THREADPRIVATE( C )
! VAR - Concentrations of variable species (global)
  REAL(kind=dp), POINTER :: VAR(:)
  !$OMP THREADPRIVATE( VAR )
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp), POINTER :: FIX(:)
  !$OMP THREADPRIVATE( FIX )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
  !$OMP THREADPRIVATE( RCONST )
! TIME - Current integration time
  REAL(kind=dp) :: TIME
  !$OMP THREADPRIVATE( TIME )
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
  !$OMP THREADPRIVATE( SUN )
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
  !$OMP THREADPRIVATE( TEMP )

! ~~~ If you are using KPP within an OpenMP parallel environment,
! ~~~ these variables DO NOT need to be declared THREADPRIVATE.

! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! DO_JVS -
  LOGICAL :: DO_JVS(LU_NONZERO)
! DO_SLV -
  LOGICAL :: DO_SLV(NVAR+1)
! DO_FUN -
  LOGICAL :: DO_FUN(NVAR)
! cLU_IROW -
  INTEGER :: cLU_IROW(LU_NONZERO)
! cLU_ICOL -
  INTEGER :: cLU_ICOL(LU_NONZERO)
! cLU_CROW -
  INTEGER :: cLU_CROW(NVAR+1)
! cLU_DIAG -
  INTEGER :: cLU_DIAG(NVAR+1)
! JVS_MAP -
  INTEGER :: JVS_MAP(LU_NONZERO)
! SPC_MAP -
  INTEGER :: SPC_MAP(NVAR)
! iSPC_MAP -
  INTEGER :: iSPC_MAP(NVAR)
! RMV -
  INTEGER :: RMV(NVAR)
! rNVAR -
  INTEGER :: rNVAR
! cNONZERO -
  INTEGER :: cNONZERO
! KEEPSPCACTIVE -
  LOGICAL :: KEEPSPCACTIVE(NVAR)
! KEEPACTIVE -
  LOGICAL :: KEEPACTIVE
  !$OMP THREADPRIVATE(  DO_JVS, DO_SLV, DO_FUN, cLU_IROW, cLU_ICOL, cLU_CROW )
  !$OMP THREADPRIVATE(  cLU_DIAG, JVS_MAP, SPC_MAP, iSPC_MAP, RMV, rNVAR, cNONZERO, KEEPACTIVE )
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

! Name of Mechanism 
CHARACTER(32), PARAMETER :: MECHNAME = 'MCHEM'
!
!
REAL(dp), PARAMETER :: INV_T300 = 1.0D0 / 300.0D0 ! reciprocal 300K
REAL(dp)            :: CAIR          ! air number density (wet) [molec/cm^3]
REAL(dp)            :: INV_TEMP      ! reciprocal of air temperature, K-1
REAL(dp)            :: PRESS         ! pressure [Atm]
REAL(dp)            :: COEFF_FALLOFF ! Factor in pressure limiting rate constants, [molec/cm^3]
REAL(dp)            :: SEAWATER      ! Fraction of seawater in grid box
LOGICAL             :: OPEN_WATER    ! Is land category ice free open water?
LOGICAL             :: LSUNLIGHT     ! Logical that is true if photolysis rates are above zero
REAL(dp)            :: TFAC

INTEGER, PARAMETER  :: KPP_NPHOTAB  =  32     ! number of photolysis rates
CHARACTER(16), SAVE :: KPP_PHOTAB( KPP_NPHOTAB )  ! Names of  photolysis
REAL(dp)            :: RJCELL( KPP_NPHOTAB )  ! grid cell photolysis rates ,[min-1]
INTEGER, PARAMETER  :: IJ_NO2_IUPAC10           =   1
INTEGER, PARAMETER  :: IJ_O3_O3P_IUPAC10        =   2
INTEGER, PARAMETER  :: IJ_O3_O1D_IUPAC10        =   3
INTEGER, PARAMETER  :: IJ_H2O2_IUPAC10          =   4
INTEGER, PARAMETER  :: IJ_NO3NO2_06             =   5
INTEGER, PARAMETER  :: IJ_NO3NO_06              =   6
INTEGER, PARAMETER  :: IJ_N2O5_IUPAC10          =   7
INTEGER, PARAMETER  :: IJ_HONO_IUPAC10          =   8
INTEGER, PARAMETER  :: IJ_HNO3_IUPAC10          =   9
INTEGER, PARAMETER  :: IJ_PNA_IUPAC10           =   10
INTEGER, PARAMETER  :: IJ_PAN_IUPAC10           =   11
INTEGER, PARAMETER  :: IJ_MEPX_IUPAC10          =   12
INTEGER, PARAMETER  :: IJ_NTR_IUPAC10           =   13
INTEGER, PARAMETER  :: IJ_FORM_R_IUPAC13        =   14
INTEGER, PARAMETER  :: IJ_FORM_M_IUPAC13        =   15
INTEGER, PARAMETER  :: IJ_ALD2_R_IUPAC13        =   16
INTEGER, PARAMETER  :: IJ_ALDX_R_IUPAC13        =   17
INTEGER, PARAMETER  :: IJ_GLYD_IUPAC13          =   18
INTEGER, PARAMETER  :: IJ_GLY_R_IUPAC13         =   19
INTEGER, PARAMETER  :: IJ_MGLY_IUPAC10          =   20
INTEGER, PARAMETER  :: IJ_KET_IUPAC10           =   21
INTEGER, PARAMETER  :: IJ_ACET_IUPAC10          =   22
INTEGER, PARAMETER  :: IJ_ISPD                  =   23
INTEGER, PARAMETER  :: IJ_HPALD                 =   24
INTEGER, PARAMETER  :: IJ_CL2_IUPAC04           =   25
INTEGER, PARAMETER  :: IJ_HOCL_IUPAC04          =   26
INTEGER, PARAMETER  :: IJ_FMCL_IUPAC04          =   27
INTEGER, PARAMETER  :: IJ_CLNO2_IUPAC13         =   28
INTEGER, PARAMETER  :: IJ_CLONO2_1              =   29
INTEGER, PARAMETER  :: IJ_CLONO2_2              =   30
INTEGER, PARAMETER  :: IJ_IC3ONO2               =   31
INTEGER, PARAMETER  :: IJ_ACRO_09               =   32
DATA KPP_PHOTAB(  1 ) / 'NO2_IUPAC10     ' /
DATA KPP_PHOTAB(  2 ) / 'O3_O3P_IUPAC10  ' /
DATA KPP_PHOTAB(  3 ) / 'O3_O1D_IUPAC10  ' /
DATA KPP_PHOTAB(  4 ) / 'H2O2_IUPAC10    ' /
DATA KPP_PHOTAB(  5 ) / 'NO3NO2_06       ' /
DATA KPP_PHOTAB(  6 ) / 'NO3NO_06        ' /
DATA KPP_PHOTAB(  7 ) / 'N2O5_IUPAC10    ' /
DATA KPP_PHOTAB(  8 ) / 'HONO_IUPAC10    ' /
DATA KPP_PHOTAB(  9 ) / 'HNO3_IUPAC10    ' /
DATA KPP_PHOTAB( 10 ) / 'PNA_IUPAC10     ' /
DATA KPP_PHOTAB( 11 ) / 'PAN_IUPAC10     ' /
DATA KPP_PHOTAB( 12 ) / 'MEPX_IUPAC10    ' /
DATA KPP_PHOTAB( 13 ) / 'NTR_IUPAC10     ' /
DATA KPP_PHOTAB( 14 ) / 'FORM_R_IUPAC13  ' /
DATA KPP_PHOTAB( 15 ) / 'FORM_M_IUPAC13  ' /
DATA KPP_PHOTAB( 16 ) / 'ALD2_R_IUPAC13  ' /
DATA KPP_PHOTAB( 17 ) / 'ALDX_R_IUPAC13  ' /
DATA KPP_PHOTAB( 18 ) / 'GLYD_IUPAC13    ' /
DATA KPP_PHOTAB( 19 ) / 'GLY_R_IUPAC13   ' /
DATA KPP_PHOTAB( 20 ) / 'MGLY_IUPAC10    ' /
DATA KPP_PHOTAB( 21 ) / 'KET_IUPAC10     ' /
DATA KPP_PHOTAB( 22 ) / 'ACET_IUPAC10    ' /
DATA KPP_PHOTAB( 23 ) / 'ISPD            ' /
DATA KPP_PHOTAB( 24 ) / 'HPALD           ' /
DATA KPP_PHOTAB( 25 ) / 'CL2_IUPAC04     ' /
DATA KPP_PHOTAB( 26 ) / 'HOCL_IUPAC04    ' /
DATA KPP_PHOTAB( 27 ) / 'FMCL_IUPAC04    ' /
DATA KPP_PHOTAB( 28 ) / 'CLNO2_IUPAC13   ' /
DATA KPP_PHOTAB( 29 ) / 'CLONO2_1        ' /
DATA KPP_PHOTAB( 30 ) / 'CLONO2_2        ' /
DATA KPP_PHOTAB( 31 ) / 'IC3ONO2         ' /
DATA KPP_PHOTAB( 32 ) / 'ACRO_09         ' /

INTEGER, PARAMETER  :: KPP_NHETERO  =  17     ! number of heterogeneous rates
CHARACTER(16), SAVE :: KPP_HETERO( KPP_NHETERO )  ! Names of  heterogeneous
REAL(dp)            :: KHETCELL( KPP_NHETERO )  ! grid cell heterogeneous rates ,[min-1]
INTEGER, PARAMETER  :: IK_HETERO_CLNO3_WAI      =   1
INTEGER, PARAMETER  :: IK_HETERO_CLNO3_WAJ      =   2
INTEGER, PARAMETER  :: IK_HETERO_NTR2           =   3
INTEGER, PARAMETER  :: IK_HETERO_N2O5IJ         =   4
INTEGER, PARAMETER  :: IK_HETERO_N2O5K          =   5
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PAIJ      =   6
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PAK       =   7
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PBIJ      =   8
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PBK       =   9
INTEGER, PARAMETER  :: IK_HETERO_NO2            =   10
INTEGER, PARAMETER  :: IK_HETERO_IEPOX          =   11
INTEGER, PARAMETER  :: IK_HETERO_IEPOXOS        =   12
INTEGER, PARAMETER  :: IK_HETERO_TETROL         =   13
INTEGER, PARAMETER  :: IK_HETERO_GLY            =   14
INTEGER, PARAMETER  :: IK_HETERO_MGLY           =   15
INTEGER, PARAMETER  :: IK_HETERO_PNCOMLI        =   16
INTEGER, PARAMETER  :: IK_HETERO_PNCOMLJ        =   17
DATA KPP_HETERO(  1 ) / 'HETERO_CLNO3_WAI' /
DATA KPP_HETERO(  2 ) / 'HETERO_CLNO3_WAJ' /
DATA KPP_HETERO(  3 ) / 'HETERO_NTR2     ' /
DATA KPP_HETERO(  4 ) / 'HETERO_N2O5IJ   ' /
DATA KPP_HETERO(  5 ) / 'HETERO_N2O5K    ' /
DATA KPP_HETERO(  6 ) / 'HETERO_H2NO3PAIJ' /
DATA KPP_HETERO(  7 ) / 'HETERO_H2NO3PAK ' /
DATA KPP_HETERO(  8 ) / 'HETERO_H2NO3PBIJ' /
DATA KPP_HETERO(  9 ) / 'HETERO_H2NO3PBK ' /
DATA KPP_HETERO( 10 ) / 'HETERO_NO2      ' /
DATA KPP_HETERO( 11 ) / 'HETERO_IEPOX    ' /
DATA KPP_HETERO( 12 ) / 'HETERO_IEPOXOS  ' /
DATA KPP_HETERO( 13 ) / 'HETERO_TETROL   ' /
DATA KPP_HETERO( 14 ) / 'HETERO_GLY      ' /
DATA KPP_HETERO( 15 ) / 'HETERO_MGLY     ' /
DATA KPP_HETERO( 16 ) / 'HETERO_PNCOMLI  ' /
DATA KPP_HETERO( 17 ) / 'HETERO_PNCOMLJ  ' /


! INLINED global variable declarations


END MODULE gas_Global

