! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gas_Initialize.f90
! Time                 : Wed Jul  3 11:52:29 2024
! Working directory    : /DFS-L/DATA/carlton/srosanka/code/CMAQ_MCHEM/UTIL/mchemmech
! Equation file        : gas.kpp
! Output root filename : gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gas_Initialize

  USE gas_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE gas_Global

  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 1.000000e+00_dp

  x = (0.)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (0.)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

! constant rate coefficients
  RCONST(11) = 2.14e-10
  RCONST(22) = 1.8e-12
  RCONST(31) = 1.7e-11
  RCONST(32) = 2e-11
  RCONST(33) = 4e-12
  RCONST(34) = 1e-17
  RCONST(39) = 1e-22
  RCONST(42) = 1e-20
  RCONST(91) = 2e-12
  RCONST(93) = 4.5e-13
  RCONST(100) = 5.5e-16
  RCONST(103) = 5.6e-12
  RCONST(111) = 6.3e-15
  RCONST(113) = 8e-12
  RCONST(118) = 4e-16
  RCONST(120) = 5e-16
  RCONST(132) = 8.1e-13
  RCONST(145) = 2.3e-11
  RCONST(148) = 3.7e-13
  RCONST(150) = 3e-11
  RCONST(170) = 3.1e-11
  RCONST(171) = 3.6e-11
  RCONST(175) = 3.6e-11
  RCONST(189) = 1.85e-11
  RCONST(190) = 1.85e-11
  RCONST(196) = 1.4e-11
  RCONST(197) = 2.1e-12
  RCONST(198) = 5.5e-12
  RCONST(199) = 1.53e-12
  RCONST(200) = 3.8e-12
  RCONST(203) = 9e-11
  RCONST(205) = 3e-12
  RCONST(207) = 4.4e-11
  RCONST(209) = 3.8e-12
  RCONST(210) = 5e-11
  RCONST(211) = 1.7e-10
  RCONST(218) = 3.6e-11
  RCONST(219) = 3e-12
  RCONST(222) = 1
  RCONST(224) = 1
  RCONST(225) = 1.1e-30
  RCONST(229) = 1.63e-14
  RCONST(233) = 5e-13
  RCONST(236) = 5e-11
  RCONST(237) = 1.4e-10
  RCONST(239) = 1.07e-10
  RCONST(240) = 2.5e-10
  RCONST(241) = 3.5e-10
  RCONST(242) = 4.3e-10
  RCONST(244) = 7.9e-11
  RCONST(245) = 1.3e-10
  RCONST(246) = 5.5e-11
  RCONST(249) = 6.1e-11
  RCONST(250) = 1.2e-10
  RCONST(251) = 1.2e-10
  RCONST(264) = 1.16e-14
  RCONST(265) = 1.97e-10
  RCONST(266) = 1.9e-11
  RCONST(287) = 2.3e-12
  RCONST(288) = 3.5e-14
  RCONST(289) = 1.92e-10
  RCONST(290) = 7.2e-12
  RCONST(292) = 9.259e-05
  RCONST(293) = 9.4882e-06
  RCONST(294) = 9.4882e-06
  RCONST(295) = 9.4882e-06
  RCONST(296) = 9.4882e-06
  RCONST(297) = 9.4882e-06
  RCONST(298) = 9.4882e-06
  RCONST(299) = 2.5e-12
  RCONST(301) = 2.5e-12
  RCONST(303) = 1.25e-11
  RCONST(304) = 4e-11
  RCONST(305) = 4e-11
  RCONST(306) = 4e-11
  RCONST(307) = 4e-11
  RCONST(308) = 4e-11
  RCONST(309) = 4e-11
  RCONST(310) = 4e-11
  RCONST(311) = 4e-11
  RCONST(312) = 4e-11
  RCONST(313) = 4e-11
  RCONST(315) = 5.5e-16
  RCONST(324) = 7.9e-11
  RCONST(327) = 1.79e-13
  RCONST(328) = 2.51e-10
  RCONST(329) = 2e-11
  RCONST(330) = 2.61e-19
  RCONST(331) = 1.15e-15
  RCONST(333) = 2.37e-10
  RCONST(334) = 2e-11
  RCONST(335) = 2.61e-19
  RCONST(336) = 1.15e-15
  RCONST(338) = 2.37e-10
  RCONST(340) = 6.1e-11
  RCONST(342) = 2.6e-18
  RCONST(343) = 8.5e-19
  RCONST(344) = 7.7e-14
! END constant rate coefficients

! INLINED initializations

! End INLINED initializations

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gas_Initialize

