! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gas_Monitor.F90
! Equation file        : gas.kpp
! Output root filename : gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gas_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'AMTNO3J                         ','AAVB2J                          ','AAVB3J                          ', & ! index 1 - 3
     'AAVB4J                          ','AISO1J                          ','AISO2J                          ', & ! index 4 - 6
     'ASQTJ                           ','APOCI                           ','APNCOMI                         ', & ! index 7 - 9
     'APOCJ                           ','APNCOMJ                         ','TOLU                            ', & ! index 10 - 12
     'DUMMY                           ','MTNO3                           ','TERPNRO2                        ', & ! index 13 - 15
     'FORM_PRIMARY                    ','ALD2_PRIMARY                    ','ACROLEIN                        ', & ! index 16 - 18
     'BUTADIENE13                     ','ACRO_PRIMARY                    ','SULF                            ', & ! index 19 - 21
     'SULRXN                          ','ISOPRXN                         ','TRPRXN                          ', & ! index 22 - 24
     'SVAVB2                          ','SVAVB4                          ','SVAVB3                          ', & ! index 25 - 27
     'SOAALK                          ','SVAVB1                          ','BENZRO2                         ', & ! index 28 - 30
     'TOLRO2                          ','XYLRO2                          ','PAHRO2                          ', & ! index 31 - 33
     'SESQRXN                         ','SESQ                            ','AISO3J                          ', & ! index 34 - 36
     'AGLYJ                           ','AMTHYDJ                         ','AOLGAJ                          ', & ! index 37 - 39
     'AOLGBJ                          ','PCSOARXN                        ','PCVOC                           ', & ! index 40 - 42
     'HGIIAER                         ','HGIIGAS                         ','HG                              ', & ! index 43 - 45
     'MSA                             ','CL2                             ','ASO4J                           ', & ! index 46 - 48
     'IEPOXP                          ','ACLI                            ','ACLJ                            ', & ! index 49 - 51
     'H2NO3PIJ                        ','ACLK                            ','H2NO3PK                         ', & ! index 52 - 54
     'CLNO2                           ','O1D                             ','ECH4                            ', & ! index 55 - 57
     'ETHY                            ','EPOX                            ','BENZENE                         ', & ! index 58 - 60
     'HOCL                            ','KET                             ','HPLD                            ', & ! index 61 - 63
     'SO2                             ','N2O5                            ','VIVPO1                          ', & ! index 64 - 66
     'PAN                             ','PACD                            ','CLNO3                           ', & ! index 67 - 69
     'HONO                            ','PNA                             ','XPRP                            ', & ! index 70 - 72
     'ETHA                            ','NTR2                            ','MEPX                            ', & ! index 73 - 75
     'XYLMN                           ','NAPH                            ','CAT1                            ', & ! index 76 - 78
     'OPAN                            ','ISPX                            ','H2O2                            ', & ! index 79 - 81
     'TOL                             ','PRPA                            ','ETOH                            ', & ! index 82 - 84
     'HCL                             ','VSVPO2                          ','VSVPO3                          ', & ! index 85 - 87
     'VSVPO1                          ','VLVPO1                          ','VSVOO2                          ' /) ! index up to 90
  CHARACTER(LEN=32), PARAMETER, DIMENSION(65) :: SPC_NAMES_1 = (/ &
     'VSVOO3                          ','VLVOO2                          ','VLVOO1                          ', & ! index 91 - 93
     'VSVOO1                          ','FACD                            ','MEOH                            ', & ! index 94 - 96
     'HCO3                            ','PANX                            ','XPAR                            ', & ! index 97 - 99
     'FMCL                            ','CRO                             ','DMS                             ', & ! index 100 - 102
     'ROOH                            ','NTR1                            ','ACET                            ', & ! index 103 - 105
     'INTR                            ','CRON                            ','AACD                            ', & ! index 106 - 108
     'BZO2                            ','CO                              ','TERP                            ', & ! index 109 - 111
     'ROR                             ','APIN                            ','ETH                             ', & ! index 112 - 114
     'TO2                             ','XLO2                            ','EPX2                            ', & ! index 115 - 117
     'CLO                             ','CRES                            ','HNO3                            ', & ! index 118 - 120
     'ISOP                            ','GLY                             ','XOPN                            ', & ! index 121 - 123
     'MGLY                            ','OPEN                            ','GLYD                            ', & ! index 124 - 126
     'IOLE                            ','OPO3                            ','XO2                             ', & ! index 127 - 129
     'FORM                            ','XO2N                            ','XO2H                            ', & ! index 130 - 132
     'OLE                             ','CXO3                            ','ALD2                            ', & ! index 133 - 135
     'ISO2                            ','ISPD                            ','MEO2                            ', & ! index 136 - 138
     'ALDX                            ','NO2                             ','NO3                             ', & ! index 139 - 141
     'CL                              ','OH                              ','NO                              ', & ! index 142 - 144
     'RO2                             ','HO2                             ','C2O3                            ', & ! index 145 - 147
     'PAR                             ','O3                              ','O                               ', & ! index 148 - 150
     'M                               ','H2                              ','O2                              ', & ! index 151 - 153
     'CH4                             ','H2O                             ' /) ! index up to 155
  CHARACTER(LEN=32), PARAMETER, DIMENSION(155) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '               NO2 --> NO + O                                                                       ', & ! index 1
     '        O + M + O2 --> O3 + M                                                                       ', & ! index 2
     '           NO + O3 --> NO2                                                                          ', & ! index 3
     '            NO + O --> NO2                                                                          ', & ! index 4
     '           NO2 + O --> NO                                                                           ', & ! index 5
     '           NO2 + O --> NO3                                                                          ', & ! index 6
     '            O3 + O --> DUMMY                                                                        ', & ! index 7
     '                O3 --> O                                                                            ', & ! index 8
     '                O3 --> O1D                                                                          ', & ! index 9
     '           O1D + M --> O + M                                                                        ', & ! index 10
     '         O1D + H2O --> 2 OH                                                                         ', & ! index 11
     '           OH + O3 --> HO2                                                                          ', & ! index 12
     '          HO2 + O3 --> OH                                                                           ', & ! index 13
     '            OH + O --> HO2                                                                          ', & ! index 14
     '           HO2 + O --> OH                                                                           ', & ! index 15
     '              2 OH --> O                                                                            ', & ! index 16
     '              2 OH --> H2O2                                                                         ', & ! index 17
     '          OH + HO2 --> DUMMY                                                                        ', & ! index 18
     '             2 HO2 --> H2O2                                                                         ', & ! index 19
     '       2 HO2 + H2O --> H2O2                                                                         ', & ! index 20
     '              H2O2 --> 2 OH                                                                         ', & ! index 21
     '         H2O2 + OH --> HO2                                                                          ', & ! index 22
     '          H2O2 + O --> OH + HO2                                                                     ', & ! index 23
     '         2 NO + O2 --> 2 NO2                                                                        ', & ! index 24
     '          NO + HO2 --> NO2 + OH                                                                     ', & ! index 25
     '          NO2 + O3 --> NO3                                                                          ', & ! index 26
     '               NO3 --> NO2 + O                                                                      ', & ! index 27
     '               NO3 --> NO                                                                           ', & ! index 28
     '          NO3 + NO --> 2 NO2                                                                        ', & ! index 29
     '         NO2 + NO3 --> NO2 + NO                                                                     ' /) ! index up to 30
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '           NO3 + O --> NO2                                                                          ', & ! index 31
     '          NO3 + OH --> NO2 + HO2                                                                    ', & ! index 32
     '         NO3 + HO2 --> NO2 + OH                                                                     ', & ! index 33
     '          NO3 + O3 --> NO2                                                                          ', & ! index 34
     '             2 NO3 --> 2 NO2                                                                        ', & ! index 35
     '         NO2 + NO3 --> N2O5                                                                         ', & ! index 36
     '              N2O5 --> NO2 + NO3                                                                    ', & ! index 37
     '              N2O5 --> DUMMY + NO2 + NO3                                                            ', & ! index 38
     '        N2O5 + H2O --> 2 HNO3                                                                       ', & ! index 39
     '           OH + NO --> HONO                                                                         ', & ! index 40
     '    NO2 + NO + H2O --> 2 HONO                                                                       ', & ! index 41
     '            2 HONO --> NO2 + NO                                                                     ', & ! index 42
     '              HONO --> OH + NO                                                                      ', & ! index 43
     '         HONO + OH --> NO2                                                                          ', & ! index 44
     '          NO2 + OH --> HNO3                                                                         ', & ! index 45
     '         HNO3 + OH --> NO3                                                                          ', & ! index 46
     '              HNO3 --> NO2 + OH                                                                     ', & ! index 47
     '         NO2 + HO2 --> PNA                                                                          ', & ! index 48
     '               PNA --> NO2 + HO2                                                                    ', & ! index 49
     '               PNA --> 0.59 NO2 + 0.41 NO3 + 0.41 OH + 0.59 HO2                                     ', & ! index 50
     '          PNA + OH --> NO2                                                                          ', & ! index 51
     '          SO2 + OH --> SULF + SULRXN + HO2                                                          ', & ! index 52
     '         NO + C2O3 --> MEO2 + NO2 + RO2                                                             ', & ! index 53
     '        NO2 + C2O3 --> PAN                                                                          ', & ! index 54
     '               PAN --> NO2 + C2O3                                                                   ', & ! index 55
     '               PAN --> 0.4 MEO2 + 0.6 NO2 + 0.4 NO3 + 0.4 RO2 + 0.6 C2O3                            ', & ! index 56
     '        HO2 + C2O3 --> 0.37 PACD + 0.13 AACD + 0.5 MEO2 + 0.5 OH + 0.5 RO2 + 0.13 O3                ', & ! index 57
     '        RO2 + C2O3 --> MEO2                                                                         ', & ! index 58
     '            2 C2O3 --> 2 MEO2 + 2 RO2                                                               ', & ! index 59
     '       CXO3 + C2O3 --> XO2H + ALD2 + MEO2 + 2 RO2                                                   ' /) ! index up to 60
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '         CXO3 + NO --> XO2H + ALD2 + NO2 + RO2                                                      ', & ! index 61
     '        CXO3 + NO2 --> PANX                                                                         ', & ! index 62
     '              PANX --> CXO3 + NO2                                                                   ', & ! index 63
     '              PANX --> 0.4 XO2H + 0.6 CXO3 + 0.4 ALD2 + 0.6 NO2 + 0.4 NO3 + 0.4 RO2                 ', & ! index 64
     '        CXO3 + HO2 --> 0.37 PACD + 0.13 AACD + 0.5 MEO2 + 0.5 OH + 0.5 RO2 + 0.13 O3                ', & ! index 65
     '        CXO3 + RO2 --> MEO2                                                                         ', & ! index 66
     '            2 CXO3 --> 2 MEO2 + 2 RO2                                                               ', & ! index 67
     '          NO + RO2 --> NO                                                                           ', & ! index 68
     '         RO2 + HO2 --> HO2                                                                          ', & ! index 69
     '             2 RO2 --> DUMMY                                                                        ', & ! index 70
     '         MEO2 + NO --> FORM + NO2 + HO2                                                             ', & ! index 71
     '        MEO2 + HO2 --> 0.9 MEPX + 0.1 FORM                                                          ', & ! index 72
     '       MEO2 + C2O3 --> 0.1 AACD + FORM + 0.9 MEO2 + 0.9 RO2 + 0.9 HO2                               ', & ! index 73
     '        MEO2 + RO2 --> 0.315 MEOH + 0.685 FORM + RO2 + 0.37 HO2                                     ', & ! index 74
     '         XO2H + NO --> NO2 + HO2                                                                    ', & ! index 75
     '        XO2H + HO2 --> ROOH                                                                         ', & ! index 76
     '       XO2H + C2O3 --> 0.2 AACD + 0.8 MEO2 + 0.8 RO2 + 0.8 HO2                                      ', & ! index 77
     '        XO2H + RO2 --> RO2 + 0.6 HO2                                                                ', & ! index 78
     '          XO2 + NO --> NO2                                                                          ', & ! index 79
     '         XO2 + HO2 --> ROOH                                                                         ', & ! index 80
     '        XO2 + C2O3 --> 0.2 AACD + 0.8 MEO2 + 0.8 RO2                                                ', & ! index 81
     '         XO2 + RO2 --> RO2                                                                          ', & ! index 82
     '         XO2N + NO --> 0.5 NTR2 + 0.5 NTR1                                                          ', & ! index 83
     '        XO2N + HO2 --> ROOH                                                                         ', & ! index 84
     '       XO2N + C2O3 --> 0.2 AACD + 0.8 MEO2 + 0.8 RO2 + 0.8 HO2                                      ', & ! index 85
     '        XO2N + RO2 --> RO2                                                                          ', & ! index 86
     '         MEPX + OH --> 0.4 FORM + 0.6 MEO2 + 0.4 OH + 0.6 RO2                                       ', & ! index 87
     '              MEPX --> MEO2 + OH + RO2                                                              ', & ! index 88
     '         ROOH + OH --> 0.06 XO2N + 0.54 XO2H + 0.4 OH + 0.6 RO2                                     ', & ! index 89
     '              ROOH --> OH + HO2                                                                     ' /) ! index up to 90
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '         NTR1 + OH --> NTR2                                                                         ', & ! index 91
     '              NTR1 --> NO2                                                                          ', & ! index 92
     '         FACD + OH --> HO2                                                                          ', & ! index 93
     '         AACD + OH --> MEO2 + RO2                                                                   ', & ! index 94
     '         PACD + OH --> C2O3                                                                         ', & ! index 95
     '         FORM + OH --> CO + HO2                                                                     ', & ! index 96
     '              FORM --> CO + 2 HO2                                                                   ', & ! index 97
     '              FORM --> CO                                                                           ', & ! index 98
     '          FORM + O --> CO + OH + HO2                                                                ', & ! index 99
     '        FORM + NO3 --> CO + HNO3 + HO2                                                              ', & ! index 100
     '        FORM + HO2 --> HCO3                                                                         ', & ! index 101
     '              HCO3 --> FORM + HO2                                                                   ', & ! index 102
     '         HCO3 + NO --> FACD + NO2 + HO2                                                             ', & ! index 103
     '        HCO3 + HO2 --> 0.5 MEPX + 0.5 FACD + 0.2 OH + 0.2 HO2                                       ', & ! index 104
     '          ALD2 + O --> OH + C2O3                                                                    ', & ! index 105
     '         ALD2 + OH --> C2O3                                                                         ', & ! index 106
     '        ALD2 + NO3 --> HNO3 + C2O3                                                                  ', & ! index 107
     '              ALD2 --> CO + MEO2 + RO2 + HO2                                                        ', & ! index 108
     '          ALDX + O --> CXO3 + OH                                                                    ', & ! index 109
     '         ALDX + OH --> CXO3                                                                         ', & ! index 110
     '        ALDX + NO3 --> HNO3 + CXO3                                                                  ', & ! index 111
     '              ALDX --> CO + XO2H + ALD2 + RO2 + HO2                                                 ', & ! index 112
     '         GLYD + OH --> 0.2 GLY + 0.2 HO2 + 0.8 C2O3                                                 ', & ! index 113
     '              GLYD --> 0.15 MEOH + 0.89 CO + 0.11 GLY + 0.74 FORM + 0.11 XO2H + 0.19 OH + 0.... etc.', & ! index 114
     '        GLYD + NO3 --> HNO3 + C2O3                                                                  ', & ! index 115
     '          GLY + OH --> 1.8 CO + 0.2 XO2 + 0.2 RO2 + HO2                                             ', & ! index 116
     '               GLY --> 2 CO + 2 HO2                                                                 ', & ! index 117
     '         GLY + NO3 --> 1.5 CO + HNO3 + 0.5 XO2 + 0.5 RO2 + HO2                                      ', & ! index 118
     '              MGLY --> CO + HO2 + C2O3                                                              ', & ! index 119
     '        MGLY + NO3 --> HNO3 + XO2 + RO2 + C2O3                                                      ' /) ! index up to 120
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '         MGLY + OH --> CO + C2O3                                                                    ', & ! index 121
     '           OH + H2 --> HO2                                                                          ', & ! index 122
     '           CO + OH --> HO2                                                                          ', & ! index 123
     '          OH + CH4 --> MEO2 + RO2                                                                   ', & ! index 124
     '         ETHA + OH --> 0.009 XO2N + 0.991 XO2H + 0.991 ALD2 + RO2                                   ', & ! index 125
     '         MEOH + OH --> FORM + HO2                                                                   ', & ! index 126
     '         ETOH + OH --> 0.011 GLYD + 0.078 FORM + 0.1 XO2H + 0.95 ALD2 + 0.1 RO2 + 0.9 HO2           ', & ! index 127
     '               KET --> 0.5 XO2H + 0.5 CXO3 + 0.5 ALD2 + 0.5 MEO2 + RO2 + 0.5 C2O3 - -2.5 PAR        ', & ! index 128
     '              ACET --> 0.38 CO + 1.38 MEO2 + 1.38 RO2 + 0.62 C2O3                                   ', & ! index 129
     '         ACET + OH --> XO2 + FORM + RO2 + C2O3                                                      ', & ! index 130
     '         PRPA + OH --> XPRP                                                                         ', & ! index 131
     '          OH + PAR --> XPAR                                                                         ', & ! index 132
     '               ROR --> 0.2 KET + 0.42 ACET + 0.02 ROR + 0.04 XO2N + 0.94 XO2H + 0.74 ALD2 + ... etc.', & ! index 133
     '          ROR + O2 --> KET + HO2                                                                    ', & ! index 134
     '         ROR + NO2 --> NTR1                                                                         ', & ! index 135
     '         ETHY + OH --> 0.3 FACD + 0.3 CO + 0.7 GLY + 0.7 OH + 0.3 HO2                               ', & ! index 136
     '           ETH + O --> CO + FORM + 0.7 XO2H + 0.3 OH + 0.7 RO2 + HO2                                ', & ! index 137
     '          ETH + OH --> 0.22 GLYD + 1.56 FORM + XO2H + RO2                                           ', & ! index 138
     '          ETH + O3 --> 0.42 FACD + 0.35 CO + FORM + 0.17 OH + 0.27 HO2                              ', & ! index 139
     '         ETH + NO3 --> 0.5 NTR1 + 0.5 XO2 + 1.125 FORM + 0.5 XO2H + 0.5 NO2 + RO2                   ', & ! index 140
     '           OLE + O --> 0.2 CO + 0.2 FORM + 0.01 XO2N + 0.2 XO2H + 0.2 ALD2 + 0.3 ALDX + 0.1 ... etc.', & ! index 141
     '          OLE + OH --> 0.195 XO2 + 0.781 FORM + 0.024 XO2N + 0.976 XO2H + 0.488 ALD2 + 0.488... etc.', & ! index 142
     '          OLE + O3 --> 0.04 H2O2 + 0.09 FACD + 0.13 AACD + 0.378 CO + 0.075 GLY + 0.075 MGLY... etc.', & ! index 143
     '         OLE + NO3 --> 0.5 NTR1 + 0.48 XO2 + 0.5 FORM + 0.04 XO2N + 0.48 XO2H + 0.25 ALD2 + ... etc.', & ! index 144
     '          IOLE + O --> 0.1 CO + 0.1 XO2H + 1.24 ALD2 + 0.66 ALDX + 0.1 RO2 + 0.1 PAR                ', & ! index 145
     '         IOLE + OH --> XO2H + 1.3 ALD2 + 0.7 ALDX + RO2                                             ', & ! index 146
     '         IOLE + O3 --> 0.08 H2O2 + 0.08 AACD + 0.245 CO + 0.24 GLY + 0.06 MGLY + 0.128 FORM ... etc.', & ! index 147
     '        IOLE + NO3 --> 0.5 NTR1 + 0.48 XO2 + 0.04 XO2N + 0.48 XO2H + 0.5 ALD2 + 0.625 ALDX +... etc.', & ! index 148
     '         ISOP + OH --> ISOPRXN + ISO2 + RO2                                                         ', & ! index 149
     '          ISOP + O --> 0.25 XO2 + 0.5 FORM + 0.25 CXO3 + 0.75 ISPD + 0.25 RO2 + 0.25 HO2 + 0.25 PAR ' /) ! index up to 150
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '         ISO2 + NO --> 0.1 INTR + 0.673 FORM + 0.082 XO2H + 0.9 ISPD + 0.9 NO2 + 0.082 RO2 +... etc.', & ! index 151
     '        ISO2 + HO2 --> 0.88 ISPX + 0.12 FORM + 0.12 ISPD + 0.12 OH + 0.12 HO2                       ', & ! index 152
     '       ISO2 + C2O3 --> 0.2 AACD + 0.598 FORM + 0.072 XO2H + ISPD + 0.8 MEO2 + 0.872 RO2 + 0.728 HO2 ', & ! index 153
     '        ISO2 + RO2 --> 0.598 FORM + 0.072 XO2H + ISPD + 1.072 RO2 + 0.728 HO2                       ', & ! index 154
     '              ISO2 --> HPLD + HO2                                                                   ', & ! index 155
     '         ISOP + O3 --> 0.066 CO + 0.2 XO2 + 0.6 FORM + 0.2 CXO3 + 0.65 ISPD + 0.15 ALDX + 0.... etc.', & ! index 156
     '        ISOP + NO3 --> ISOPRXN + 0.65 NTR2 + 0.33 XO2 + 0.35 FORM + 0.03 XO2N + 0.64 XO2H + ... etc.', & ! index 157
     '         ISPD + OH --> 0.137 ACET + 0.137 CO + 0.115 MGLY + 0.269 GLYD + 0.457 OPO3 + 0.521 ... etc.', & ! index 158
     '         ISPD + O3 --> 0.15 FACD + 0.17 ACET + 0.543 CO + 0.17 GLY + 0.531 MGLY + 0.231 FORM... etc.', & ! index 159
     '        ISPD + NO3 --> 0.142 NTR2 + 0.717 HNO3 + 0.113 MGLY + 0.113 GLYD + 0.142 XO2 + 0.142... etc.', & ! index 160
     '              ISPD --> 0.17 ACET + 0.128 GLYD + 0.16 XO2 + 0.26 FORM + 0.34 XO2H + 0.24 OLE ... etc.', & ! index 161
     '         ISPX + OH --> 0.904 EPOX + 0.029 IOLE + 0.067 ISO2 + 0.029 ALDX + 0.933 OH + 0.067 RO2     ', & ! index 162
     '              HPLD --> ISPD + OH                                                                    ', & ! index 163
     '        HPLD + NO3 --> HNO3 + ISPD                                                                  ', & ! index 164
     '         EPOX + OH --> EPX2 + RO2                                                                   ', & ! index 165
     '        EPX2 + HO2 --> 0.074 FACD + 0.251 CO + 0.275 GLY + 0.275 MGLY + 0.275 GLYD + 0.375 F... etc.', & ! index 166
     '         EPX2 + NO --> 0.251 CO + 0.275 GLY + 0.275 MGLY + 0.275 GLYD + 0.375 FORM + NO2 + 0... etc.', & ! index 167
     '       EPX2 + C2O3 --> 0.2 AACD + 0.2 CO + 0.22 GLY + 0.22 MGLY + 0.22 GLYD + 0.3 FORM + 0.8... etc.', & ! index 168
     '        EPX2 + RO2 --> 0.251 CO + 0.275 GLY + 0.275 MGLY + 0.275 GLYD + 0.375 FORM + 0.125 O... etc.', & ! index 169
     '         INTR + OH --> 0.266 NTR2 + 0.185 FACD + 0.104 INTR + 0.331 GLYD + 0.63 XO2 + 0.592 ... etc.', & ! index 170
     '          TERP + O --> TRPRXN + 0.15 ALDX + 5.12 PAR                                                ', & ! index 171
     '         TERP + OH --> TRPRXN + 0.5 XO2 + 0.28 FORM + 0.25 XO2N + 0.75 XO2H + 0.47 ALDX + 1.... etc.', & ! index 172
     '         TERP + O3 --> TRPRXN + 0.001 CO + 0.69 XO2 + 0.24 FORM + 0.18 XO2N + 0.07 XO2H + 0.... etc.', & ! index 173
     '        TERP + NO3 --> TERPNRO2 + 0.53 NTR2 + 0.75 XO2 + 0.25 XO2N + 0.28 XO2H + 0.47 ALDX +... etc.', & ! index 174
     '          APIN + O --> TRPRXN + 0.15 ALDX + 5.12 PAR                                                ', & ! index 175
     '         APIN + OH --> TRPRXN + 0.5 XO2 + 0.28 FORM + 0.25 XO2N + 0.75 XO2H + 0.47 ALDX + 1.... etc.', & ! index 176
     '         APIN + O3 --> TRPRXN + 0.001 CO + 0.69 XO2 + 0.24 FORM + 0.18 XO2N + 0.07 XO2H + 0.... etc.', & ! index 177
     '        APIN + NO3 --> 0.53 NTR2 + 0.75 XO2 + 0.25 XO2N + 0.28 XO2H + 0.47 ALDX + 0.47 NO2 +... etc.', & ! index 178
     '      BENZENE + OH --> BENZRO2 + 0.352 BZO2 + 0.53 CRES + 0.118 OPEN + 0.118 OH + 0.352 RO2 ... etc.', & ! index 179
     '         BZO2 + NO --> 0.082 NTR2 + 0.918 GLY + 0.918 OPEN + 0.918 NO2 + 0.918 HO2                  ' /) ! index up to 180
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '       BZO2 + C2O3 --> GLY + OPEN + MEO2 + RO2 + HO2                                                ', & ! index 181
     '        BZO2 + HO2 --> DUMMY                                                                        ', & ! index 182
     '        BZO2 + RO2 --> GLY + OPEN + RO2 + HO2                                                       ', & ! index 183
     '          TOL + OH --> TOLRO2 + 0.65 TO2 + 0.18 CRES + 0.1 OPEN + 0.07 XO2H + 0.1 OH + 0.72 ... etc.', & ! index 184
     '          TO2 + NO --> 0.14 NTR2 + 0.417 GLY + 0.2 XOPN + 0.443 MGLY + 0.66 OPEN + 0.86 NO2 ... etc.', & ! index 185
     '        TO2 + C2O3 --> 0.48 GLY + 0.23 XOPN + 0.52 MGLY + 0.77 OPEN + MEO2 + RO2 + HO2              ', & ! index 186
     '         TO2 + HO2 --> DUMMY                                                                        ', & ! index 187
     '         TO2 + RO2 --> 0.48 GLY + 0.23 XOPN + 0.52 MGLY + 0.77 OPEN + RO2 + HO2                     ', & ! index 188
     '        XYLMN + OH --> XYLRO2 + 0.544 XLO2 + 0.155 CRES + 0.244 XOPN + 0.058 XO2H + 0.244 OH... etc.', & ! index 189
     '         NAPH + OH --> PAHRO2 + 0.544 XLO2 + 0.155 CRES + 0.244 XOPN + 0.058 XO2H + 0.244 OH... etc.', & ! index 190
     '         XLO2 + NO --> 0.14 NTR2 + 0.221 GLY + 0.56 XOPN + 0.675 MGLY + 0.3 OPEN + 0.86 NO2 ... etc.', & ! index 191
     '        XLO2 + HO2 --> DUMMY                                                                        ', & ! index 192
     '       XLO2 + C2O3 --> 0.26 GLY + 0.65 XOPN + 0.77 MGLY + 0.35 OPEN + MEO2 + RO2 + HO2              ', & ! index 193
     '        XLO2 + RO2 --> 0.26 GLY + 0.65 XOPN + 0.77 MGLY + 0.35 OPEN + RO2 + HO2                     ', & ! index 194
     '         CRES + OH --> 0.732 CAT1 + 0.2 CRO + 0.025 GLY + 0.025 OPEN + 0.02 XO2N + 0.02 RO2 + HO2   ', & ! index 195
     '        CRES + NO3 --> 0.3 CRO + HNO3 + 0.24 GLY + 0.24 MGLY + 0.48 OPO3 + 0.48 XO2 + 0.1 XO... etc.', & ! index 196
     '         CRO + NO2 --> CRON                                                                         ', & ! index 197
     '         CRO + HO2 --> CRES                                                                         ', & ! index 198
     '         CRON + OH --> NTR2 + 0.5 CRO                                                               ', & ! index 199
     '        CRON + NO3 --> NTR2 + 0.5 CRO + HNO3                                                        ', & ! index 200
     '              CRON --> HONO + OPEN + FORM + HO2                                                     ', & ! index 201
     '              XOPN --> 0.7 CO + 0.4 GLY + XO2H + 0.7 HO2 + 0.3 C2O3                                 ', & ! index 202
     '         XOPN + OH --> 0.4 GLY + MGLY + 2 XO2H + 2 RO2                                              ', & ! index 203
     '         XOPN + O3 --> 0.5 CO + 1.2 MGLY + 0.3 XO2H + 0.1 ALD2 + 0.5 OH + 0.3 RO2 + 0.6 C2O3        ', & ! index 204
     '        XOPN + NO3 --> 0.5 NTR2 + 0.25 MGLY + 0.25 OPEN + 0.45 XO2 + 0.1 XO2N + 0.45 XO2H + ... etc.', & ! index 205
     '              OPEN --> CO + OPO3 + HO2                                                              ', & ! index 206
     '         OPEN + OH --> 0.4 GLY + 0.6 OPO3 + 0.4 XO2H + 0.4 RO2                                      ', & ! index 207
     '         OPEN + O3 --> 1.98 CO + 1.4 GLY + 0.24 MGLY + 0.08 FORM + 0.02 ALD2 + 0.5 OH + 0.56... etc.', & ! index 208
     '        OPEN + NO3 --> HNO3 + OPO3                                                                  ', & ! index 209
     '         CAT1 + OH --> 0.5 CRO + 0.14 FORM + 0.2 HO2                                                ' /) ! index up to 210
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '        CAT1 + NO3 --> CRO + HNO3                                                                   ', & ! index 211
     '         OPO3 + NO --> 0.5 CO + 0.5 GLY + 0.2 CXO3 + NO2 + 0.8 HO2                                  ', & ! index 212
     '        OPO3 + NO2 --> OPAN                                                                         ', & ! index 213
     '              OPAN --> OPO3 + NO2                                                                   ', & ! index 214
     '        OPO3 + HO2 --> 0.37 PACD + 0.13 AACD + 0.5 MEO2 + 0.5 OH + 0.5 RO2 + 0.13 O3                ', & ! index 215
     '       OPO3 + C2O3 --> XO2 + MEO2 + ALDX + 2 RO2                                                    ', & ! index 216
     '        OPO3 + RO2 --> 0.2 AACD + 0.8 XO2H + 0.8 ALDX + 1.8 RO2                                     ', & ! index 217
     '         OPAN + OH --> 0.5 NTR2 + CO + 0.5 GLY + 0.5 NO2                                            ', & ! index 218
     '         PANX + OH --> ALD2 + NO2                                                                   ', & ! index 219
     '         ECH4 + OH --> MEO2 + RO2                                                                   ', & ! index 220
     '              XPRP --> XO2N + RO2                                                                   ', & ! index 221
     '              XPRP --> 0.732 ACET + XO2H + 0.268 ALDX + RO2 + 0.268 PAR                             ', & ! index 222
     '              XPAR --> XO2N + RO2                                                                   ', & ! index 223
     '              XPAR --> 0.874 ROR + 0.874 XO2 + 0.126 XO2H + 0.126 ALDX + RO2 - -0.126 PAR           ', & ! index 224
     '    NO2 + OH + H2O --> HNO3                                                                         ', & ! index 225
     '               CL2 --> 2 CL                                                                         ', & ! index 226
     '              HOCL --> CL + OH                                                                      ', & ! index 227
     '           CL + O3 --> CLO                                                                          ', & ! index 228
     '             2 CLO --> 0.3 CL2 + 1.4 CL                                                             ', & ! index 229
     '          CLO + NO --> NO2 + CL                                                                     ', & ! index 230
     '         CLO + HO2 --> HOCL                                                                         ', & ! index 231
     '        CLO + MEO2 --> FORM + CL + HO2                                                              ', & ! index 232
     '         FMCL + OH --> CO + CL                                                                      ', & ! index 233
     '              FMCL --> CO + CL + HO2                                                                ', & ! index 234
     '          CL + CH4 --> HCL + MEO2 + RO2                                                             ', & ! index 235
     '          CL + PAR --> HCL + XPAR                                                                   ', & ! index 236
     '         PRPA + CL --> HCL + ACET + 0.03 XO2N + 0.97 XO2H + RO2                                     ', & ! index 237
     '         ETHA + CL --> HCL + 0.009 XO2N + 0.991 XO2H + 0.991 ALD2 + RO2                             ', & ! index 238
     '          ETH + CL --> FMCL + 2 XO2 + FORM + HO2                                                    ', & ! index 239
     '          OLE + CL --> FMCL + 2 XO2 + 0.33 ALD2 + 0.67 ALDX + HO2 - PAR                             ' /) ! index up to 240
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '         IOLE + CL --> 0.3 HCL + 0.7 FMCL + 1.7 XO2 + 0.3 OLE + 0.45 ALD2 + 0.55 ALDX + HO2 ... etc.', & ! index 241
     '         ISOP + CL --> FMCL + 0.04 XO2N + 0.96 XO2H + ISPD + RO2                                    ', & ! index 242
     '         FORM + CL --> HCL + CO + HO2                                                               ', & ! index 243
     '         ALD2 + CL --> HCL + C2O3                                                                   ', & ! index 244
     '         ALDX + CL --> HCL + CXO3                                                                   ', & ! index 245
     '         MEOH + CL --> HCL + FORM + HO2                                                             ', & ! index 246
     '         ETOH + CL --> HCL + ALD2 + HO2                                                             ', & ! index 247
     '          HCL + OH --> CL                                                                           ', & ! index 248
     '          TOL + CL --> TOLRO2 + HCL + 0.65 TO2 + 0.18 CRES + 0.1 OPEN + 0.07 XO2H + 0.1 OH +... etc.', & ! index 249
     '        XYLMN + CL --> XYLRO2 + HCL + 0.544 XLO2 + 0.155 CRES + 0.244 XOPN + 0.058 XO2H + 0.... etc.', & ! index 250
     '         NAPH + CL --> PAHRO2 + HCL + 0.544 XLO2 + 0.155 CRES + 0.244 XOPN + 0.058 XO2H + 0.... etc.', & ! index 251
     '             CLNO2 --> NO2 + CL                                                                     ', & ! index 252
     '         CLO + NO2 --> CLNO3                                                                        ', & ! index 253
     '             CLNO3 --> CLO + NO2                                                                    ', & ! index 254
     '             CLNO3 --> NO3 + CL                                                                     ', & ! index 255
     '             CLNO3 --> HOCL + HNO3                                                                  ', & ! index 256
     '             CLNO3 --> DUMMY + HOCL + HNO3                                                          ', & ! index 257
     '       TOLRO2 + NO --> 0.016 SVAVB2 + 0.047 SVAVB4 + 0.051 SVAVB3 + NO                              ', & ! index 258
     '      TOLRO2 + HO2 --> 0.14 SVAVB1 + HO2                                                            ', & ! index 259
     '       XYLRO2 + NO --> 0.015 SVAVB2 + 0.06 SVAVB4 + 0.023 SVAVB3 + NO                               ', & ! index 260
     '      XYLRO2 + HO2 --> 0.193 SVAVB1 + HO2                                                           ', & ! index 261
     '      BENZRO2 + NO --> 0.034 SVAVB2 + 0.392 SVAVB4 + NO                                             ', & ! index 262
     '     BENZRO2 + HO2 --> 0.146 SVAVB1 + HO2                                                           ', & ! index 263
     '         SESQ + O3 --> SESQRXN + O3                                                                 ', & ! index 264
     '         SESQ + OH --> SESQRXN + OH                                                                 ', & ! index 265
     '        SESQ + NO3 --> SESQRXN + NO3                                                                ', & ! index 266
     '       PAHRO2 + NO --> 0.028 SVAVB2 + 0.191 SVAVB4 + 0.225 SVAVB3 + NO                              ', & ! index 267
     '      PAHRO2 + HO2 --> 0.473 SVAVB1 + HO2                                                           ', & ! index 268
     '       SOAALK + OH --> 0.006 SVAVB2 + 0.081 SVAVB4 + 0.052 SVAVB3 + OH                              ', & ! index 269
     '              NTR2 --> HNO3                                                                         ' /) ! index up to 270
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '              N2O5 --> H2NO3PIJ + HNO3                                                              ', & ! index 271
     '              N2O5 --> H2NO3PK + HNO3                                                               ', & ! index 272
     '          H2NO3PIJ --> HNO3                                                                         ', & ! index 273
     '           H2NO3PK --> HNO3                                                                         ', & ! index 274
     '   ACLI + H2NO3PIJ --> CLNO2                                                                        ', & ! index 275
     '   ACLJ + H2NO3PIJ --> CLNO2                                                                        ', & ! index 276
     '    ACLK + H2NO3PK --> CLNO2                                                                        ', & ! index 277
     '               NO2 --> 0.5 HONO + 0.5 HNO3                                                          ', & ! index 278
     '                O3 --> DUMMY                                                                        ', & ! index 279
     '              EPOX --> IEPOXP                                                                       ', & ! index 280
     '    ASO4J + IEPOXP --> AISO3J                                                                       ', & ! index 281
     '            IEPOXP --> AISO3J                                                                       ', & ! index 282
     '               GLY --> AGLYJ                                                                        ', & ! index 283
     '              MGLY --> AGLYJ                                                                        ', & ! index 284
     '     TERPNRO2 + NO --> 0.688 MTNO3 + NO                                                             ', & ! index 285
     '    TERPNRO2 + HO2 --> MTNO3 + HO2                                                                  ', & ! index 286
     '    TERPNRO2 + NO3 --> 0.422 MTNO3 + NO3                                                            ', & ! index 287
     '    TERPNRO2 + RO2 --> 0.711 MTNO3 + RO2                                                            ', & ! index 288
     '        MTNO3 + CL --> 0.37 MTNO3 + CL                                                              ', & ! index 289
     '        MTNO3 + OH --> 0.24 MTNO3 + OH                                                              ', & ! index 290
     '             MTNO3 --> DUMMY                                                                        ', & ! index 291
     '           AMTNO3J --> AMTHYDJ                                                                      ', & ! index 292
     '            AAVB2J --> 0.907 AOLGAJ                                                                 ', & ! index 293
     '            AAVB3J --> 0.925 AOLGAJ                                                                 ', & ! index 294
     '            AAVB4J --> 0.943 AOLGAJ                                                                 ', & ! index 295
     '            AISO1J --> 0.5 AOLGBJ                                                                   ', & ! index 296
     '            AISO2J --> 0.5 AOLGBJ                                                                   ', & ! index 297
     '             ASQTJ --> 1.5 AOLGBJ                                                                   ', & ! index 298
     '        APOCI + OH --> APOCI + 1.25 APNCOMI + OH                                                    ', & ! index 299
     '      APNCOMI + OH --> OH                                                                           ' /) ! index up to 300
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '        APOCJ + OH --> APOCJ + 1.25 APNCOMJ + OH                                                    ', & ! index 301
     '      APNCOMJ + OH --> OH                                                                           ', & ! index 302
     '        PCVOC + OH --> PCSOARXN + OH                                                                ', & ! index 303
     '       VLVPO1 + OH --> 0.0023 VIVPO1 + 0.0025 VSVPO2 + 0.0026 VSVPO3 + 0.0062 VSVPO1 + 0.485... etc.', & ! index 304
     '       VSVPO1 + OH --> 0.0041 VSVPO2 + 0.0035 VSVPO3 + 0.2862 VSVPO1 + 0.3003 VLVPO1 + 0.182... etc.', & ! index 305
     '       VSVPO2 + OH --> 0.1373 VSVPO2 + 0.0005 VSVPO3 + 0.095 VSVPO1 + 0.3856 VLVPO1 + 0.1764... etc.', & ! index 306
     '       VSVPO3 + OH --> 0.0153 VSVPO2 + 0.1043 VSVPO3 + 0.3063 VSVPO1 + 0.2181 VLVPO1 + 0.166... etc.', & ! index 307
     '       VIVPO1 + OH --> 0.3 VSVPO2 + 0.2089 VSVPO1 + 0.2412 VLVPO1 + 0.0471 VLVOO2 + 0.2028 V... etc.', & ! index 308
     '       VLVOO1 + OH --> 0.1239 VSVOO2 + 0.1831 VSVOO3 + 0.0143 VLVOO2 + 0.6664 VLVOO1 + 0.012... etc.', & ! index 309
     '       VLVOO2 + OH --> 0.1027 VSVOO2 + 0.2045 VSVOO3 + 0.3931 VLVOO2 + 0.2858 VLVOO1 + 0.013... etc.', & ! index 310
     '       VSVOO1 + OH --> 0.0702 VSVOO2 + 0.1116 VSVOO3 + 0.2272 VLVOO2 + 0.3303 VLVOO1 + 0.260... etc.', & ! index 311
     '       VSVOO2 + OH --> 0.2577 VSVOO2 + 0.0739 VSVOO3 + 0.2749 VLVOO2 + 0.3444 VLVOO1 + 0.049... etc.', & ! index 312
     '       VSVOO3 + OH --> 0.0385 VSVOO2 + 0.2667 VSVOO3 + 0.2421 VLVOO2 + 0.3886 VLVOO1 + 0.064... etc.', & ! index 313
     ' FORM_PRIMARY + OH --> OH                                                                           ', & ! index 314
     'FORM_PRIMARY + NO3 --> NO3                                                                          ', & ! index 315
     '  FORM_PRIMARY + O --> O                                                                            ', & ! index 316
     '      FORM_PRIMARY --> DUMMY                                                                        ', & ! index 317
     '      FORM_PRIMARY --> 2 DUMMY                                                                      ', & ! index 318
     ' FORM_PRIMARY + CL --> CL                                                                           ', & ! index 319
     ' ALD2_PRIMARY + OH --> OH                                                                           ', & ! index 320
     'ALD2_PRIMARY + NO3 --> NO3                                                                          ', & ! index 321
     '  ALD2_PRIMARY + O --> O                                                                            ', & ! index 322
     '      ALD2_PRIMARY --> DUMMY                                                                        ', & ! index 323
     ' ALD2_PRIMARY + CL --> CL                                                                           ', & ! index 324
     '  BUTADIENE13 + OH --> 0.58 ACROLEIN + OH                                                           ', & ! index 325
     '  BUTADIENE13 + O3 --> 0.52 ACROLEIN + O3                                                           ', & ! index 326
     ' BUTADIENE13 + NO3 --> 0.045 ACROLEIN + NO3                                                         ', & ! index 327
     '  BUTADIENE13 + CL --> 0.58 ACROLEIN + CL                                                           ', & ! index 328
     ' ACRO_PRIMARY + OH --> OH                                                                           ', & ! index 329
     ' ACRO_PRIMARY + O3 --> O3                                                                           ' /) ! index up to 330
  CHARACTER(LEN=100), PARAMETER, DIMENSION(19) :: EQN_NAMES_11 = (/ &
     'ACRO_PRIMARY + NO3 --> NO3                                                                          ', & ! index 331
     '      ACRO_PRIMARY --> DUMMY                                                                        ', & ! index 332
     ' ACRO_PRIMARY + CL --> CL                                                                           ', & ! index 333
     '     ACROLEIN + OH --> OH                                                                           ', & ! index 334
     '     ACROLEIN + O3 --> O3                                                                           ', & ! index 335
     '    ACROLEIN + NO3 --> NO3                                                                          ', & ! index 336
     '          ACROLEIN --> DUMMY                                                                        ', & ! index 337
     '     ACROLEIN + CL --> CL                                                                           ', & ! index 338
     '         TOLU + OH --> OH                                                                           ', & ! index 339
     '         TOLU + CL --> CL                                                                           ', & ! index 340
     '           HG + O3 --> 0.5 HGIIAER + 0.5 HGIIGAS + O3                                               ', & ! index 341
     '          HG + CL2 --> HGIIGAS + CL2                                                                ', & ! index 342
     '         HG + H2O2 --> HGIIGAS + H2O2                                                               ', & ! index 343
     '           HG + OH --> 0.5 HGIIAER + 0.5 HGIIGAS + OH                                               ', & ! index 344
     '       HG + CL + M --> 0.5 HGIIGAS + 0.5 HG + CL + M                                                ', & ! index 345
     '          DMS + OH --> SO2 + FORM + MEO2                                                            ', & ! index 346
     '          DMS + OH --> 0.25 MSA + 0.75 SO2 + MEO2                                                   ', & ! index 347
     '         DMS + NO3 --> SO2 + HNO3 + FORM + MEO2                                                     ', & ! index 348
     '          DMS + CL --> 0.14 MSA + 0.86 SO2 + 0.45 HCL + 0.55 CLO + 0.45 FORM + MEO2                 ' /) ! index up to 349
  CHARACTER(LEN=100), PARAMETER, DIMENSION(349) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11 /)

  CHARACTER(LEN=32), PARAMETER, DIMENSION(90) :: EQN_TAGS_0 = (/ &
     'R1                              ','R2                              ','R3                              ', & ! index 1 - 3
     'R4                              ','R5                              ','R6                              ', & ! index 4 - 6
     'R7                              ','R8                              ','R9                              ', & ! index 7 - 9
     'R10                             ','R11                             ','R12                             ', & ! index 10 - 12
     'R13                             ','R14                             ','R15                             ', & ! index 13 - 15
     'R16                             ','R17                             ','R18                             ', & ! index 16 - 18
     'R19                             ','R20                             ','R21                             ', & ! index 19 - 21
     'R22                             ','R23                             ','R24                             ', & ! index 22 - 24
     'R25                             ','R26                             ','R27                             ', & ! index 25 - 27
     'R28                             ','R29                             ','R30                             ', & ! index 28 - 30
     'R31                             ','R32                             ','R33                             ', & ! index 31 - 33
     'R34                             ','R35                             ','R36                             ', & ! index 34 - 36
     'R37                             ','R38                             ','R39                             ', & ! index 37 - 39
     'R40                             ','R41                             ','R42                             ', & ! index 40 - 42
     'R43                             ','R44                             ','R45                             ', & ! index 43 - 45
     'R46                             ','R47                             ','R48                             ', & ! index 46 - 48
     'R49                             ','R50                             ','R51                             ', & ! index 49 - 51
     'R52                             ','R53                             ','R54                             ', & ! index 52 - 54
     'R55                             ','R56                             ','R57                             ', & ! index 55 - 57
     'R58                             ','R59                             ','R60                             ', & ! index 58 - 60
     'R61                             ','R62                             ','R63                             ', & ! index 61 - 63
     'R64                             ','R65                             ','R66                             ', & ! index 64 - 66
     'R67                             ','R68                             ','R69                             ', & ! index 67 - 69
     'R70                             ','R71                             ','R72                             ', & ! index 70 - 72
     'R73                             ','R74                             ','R75                             ', & ! index 73 - 75
     'R76                             ','R77                             ','R78                             ', & ! index 76 - 78
     'R79                             ','R80                             ','R81                             ', & ! index 79 - 81
     'R82                             ','R83                             ','R84                             ', & ! index 82 - 84
     'R85                             ','R86                             ','R87                             ', & ! index 85 - 87
     'R88                             ','R89                             ','R90                             ' /) ! index up to 90
  CHARACTER(LEN=32), PARAMETER, DIMENSION(90) :: EQN_TAGS_1 = (/ &
     'R91                             ','R92                             ','R93                             ', & ! index 91 - 93
     'R94                             ','R95                             ','R96                             ', & ! index 94 - 96
     'R97                             ','R98                             ','R99                             ', & ! index 97 - 99
     'R100                            ','R101                            ','R102                            ', & ! index 100 - 102
     'R103                            ','R104                            ','R105                            ', & ! index 103 - 105
     'R106                            ','R107                            ','R108                            ', & ! index 106 - 108
     'R109                            ','R110                            ','R111                            ', & ! index 109 - 111
     'R112                            ','R113                            ','R114                            ', & ! index 112 - 114
     'R115                            ','R116                            ','R117                            ', & ! index 115 - 117
     'R118                            ','R119                            ','R120                            ', & ! index 118 - 120
     'R121                            ','R122                            ','R123                            ', & ! index 121 - 123
     'R124                            ','R125                            ','R126                            ', & ! index 124 - 126
     'R127                            ','R128                            ','R129                            ', & ! index 127 - 129
     'R130                            ','R131                            ','R132                            ', & ! index 130 - 132
     'R133                            ','R134                            ','R135                            ', & ! index 133 - 135
     'R136                            ','R137                            ','R138                            ', & ! index 136 - 138
     'R139                            ','R140                            ','R141                            ', & ! index 139 - 141
     'R142                            ','R143                            ','R144                            ', & ! index 142 - 144
     'R145                            ','R146                            ','R147                            ', & ! index 145 - 147
     'R148                            ','R149                            ','R150                            ', & ! index 148 - 150
     'R151                            ','R152                            ','R153                            ', & ! index 151 - 153
     'R154                            ','R155                            ','R156                            ', & ! index 154 - 156
     'R157                            ','R158                            ','R159                            ', & ! index 157 - 159
     'R160                            ','R161                            ','R162                            ', & ! index 160 - 162
     'R163                            ','R164                            ','R165                            ', & ! index 163 - 165
     'R166                            ','R167                            ','R168                            ', & ! index 166 - 168
     'R169                            ','R170                            ','R171                            ', & ! index 169 - 171
     'R172                            ','R173                            ','R174                            ', & ! index 172 - 174
     'R171a                           ','R172a                           ','R173a                           ', & ! index 175 - 177
     'R174a                           ','R175                            ','R176                            ' /) ! index up to 180
  CHARACTER(LEN=32), PARAMETER, DIMENSION(90) :: EQN_TAGS_2 = (/ &
     'R177                            ','R178                            ','R179                            ', & ! index 181 - 183
     'R180                            ','R181                            ','R182                            ', & ! index 184 - 186
     'R183                            ','R184                            ','R185                            ', & ! index 187 - 189
     'R185a                           ','R186                            ','R187                            ', & ! index 190 - 192
     'R188                            ','R189                            ','R190                            ', & ! index 193 - 195
     'R191                            ','R192                            ','R193                            ', & ! index 196 - 198
     'R194                            ','R195                            ','R196                            ', & ! index 199 - 201
     'R197                            ','R198                            ','R199                            ', & ! index 202 - 204
     'R200                            ','R201                            ','R202                            ', & ! index 205 - 207
     'R203                            ','R204                            ','R205                            ', & ! index 208 - 210
     'R206                            ','R207                            ','R208                            ', & ! index 211 - 213
     'R209                            ','R210                            ','R211                            ', & ! index 214 - 216
     'R212                            ','R213                            ','R214                            ', & ! index 217 - 219
     'R216                            ','R217                            ','R218                            ', & ! index 220 - 222
     'R219                            ','R220                            ','R221                            ', & ! index 223 - 225
     'CL1                             ','CL2                             ','CL3                             ', & ! index 226 - 228
     'CL4                             ','CL5                             ','CL6                             ', & ! index 229 - 231
     'CL7                             ','CL8                             ','CL9                             ', & ! index 232 - 234
     'CL10                            ','CL11                            ','CL12                            ', & ! index 235 - 237
     'CL13                            ','CL14                            ','CL15                            ', & ! index 238 - 240
     'CL16                            ','CL17                            ','CL18                            ', & ! index 241 - 243
     'CL19                            ','CL20                            ','CL21                            ', & ! index 244 - 246
     'CL22                            ','CL23                            ','CL24                            ', & ! index 247 - 249
     'CL25                            ','CL26                            ','CL27                            ', & ! index 250 - 252
     'CL28                            ','CL30                            ','CL31                            ', & ! index 253 - 255
     'HET_CLNO3_WAI                   ','HET_CLNO3_WAJ                   ','SA01                            ', & ! index 256 - 258
     'SA02                            ','SA03                            ','SA04                            ', & ! index 259 - 261
     'SA06                            ','SA07                            ','SA08                            ', & ! index 262 - 264
     'SA09                            ','SA10                            ','SA11                            ', & ! index 265 - 267
     'SA12                            ','SA13                            ','HET_NTR2                        ' /) ! index up to 270
  CHARACTER(LEN=32), PARAMETER, DIMENSION(79) :: EQN_TAGS_3 = (/ &
     'HET_N2O5IJ                      ','HET_N2O5K                       ','HET_H2NO3PIJA                   ', & ! index 271 - 273
     'HET_H2NO3PKA                    ','HET_H2NO3PIB                    ','HET_H2NO3PJB                    ', & ! index 274 - 276
     'HET_H2NO3PKB                    ','HET_N02                         ','HAL_Ozone                       ', & ! index 277 - 279
     'HET_IEPOX                       ','HET_IEPOXOS                     ','HET_TETROL                      ', & ! index 280 - 282
     'HET_GLY                         ','HET_MGLY                        ','BL18a                           ', & ! index 283 - 285
     'BL18b                           ','BL18c                           ','BL18d                           ', & ! index 286 - 288
     'CP07mtp                         ','BP70mtp                         ','BP71mtp                         ', & ! index 289 - 291
     'HYD_MT                          ','OLIG_AROMATIC1                  ','OLIG_AROMATIC2                  ', & ! index 292 - 294
     'OLIG_AROMATIC3                  ','OLIG_ISOPRENE1                  ','OLIG_ISOPRENE2                  ', & ! index 295 - 297
     'OLIG_SESQT1                     ','RPOAGEPI                        ','RPOAGELI                        ', & ! index 298 - 300
     'RPOAGEPJ                        ','RPOAGELJ                        ','PCSOA                           ', & ! index 301 - 303
     'POA_AGE1                        ','POA_AGE2                        ','POA_AGE3                        ', & ! index 304 - 306
     'POA_AGE4                        ','POA_AGE5                        ','POA_AGE6                        ', & ! index 307 - 309
     'POA_AGE7                        ','POA_AGE8                        ','POA_AGE9                        ', & ! index 310 - 312
     'POA_AGE10                       ','T01                             ','T02                             ', & ! index 313 - 315
     'T03                             ','T04                             ','T05                             ', & ! index 316 - 318
     'TCL1                            ','T06                             ','T07                             ', & ! index 319 - 321
     'T08                             ','T09                             ','TCL2                            ', & ! index 322 - 324
     'T10                             ','T11                             ','T12                             ', & ! index 325 - 327
     'TCL3                            ','T13                             ','T14                             ', & ! index 328 - 330
     'T15                             ','T16                             ','TCL4                            ', & ! index 331 - 333
     'T17                             ','T18                             ','T19                             ', & ! index 334 - 336
     'T20                             ','TCL5                            ','T21                             ', & ! index 337 - 339
     'TCL6                            ','HG1                             ','HG2                             ', & ! index 340 - 342
     'HG3                             ','HG4                             ','HG5                             ', & ! index 343 - 345
     'DMS1                            ','DMS2                            ','DMS3                            ', & ! index 346 - 348
     'DMS4                            ' /) ! index up to 349
  CHARACTER(LEN=32), PARAMETER, DIMENSION(349) :: EQN_TAGS = (/&
    EQN_TAGS_0, EQN_TAGS_1, EQN_TAGS_2, EQN_TAGS_3 /)

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! INLINED global variables

! End INLINED global variables


END MODULE gas_Monitor
