! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mchem_Global.f90
! Time                 : Fri Jul  5 18:39:20 2024
! Working directory    : /DFS-L/DATA/carlton/srosanka/code/CMAQ_MCHEM/UTIL/mchemmech
! Equation file        : mchem.kpp
! Output root filename : mchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mchem_Global

  USE mchem_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1) )
      EQUIVALENCE( C(419),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

! Name of Mechanism 
CHARACTER(32), PARAMETER :: MECHNAME = 'MCHEM'
!
!
REAL(dp), PARAMETER :: INV_T300 = 1.0D0 / 300.0D0 ! reciprocal 300K
REAL(dp)            :: CAIR          ! air number density (wet) [molec/cm^3]
REAL(dp)            :: INV_TEMP      ! reciprocal of air temperature, K-1
REAL(dp)            :: PRESS         ! pressure [Atm]
REAL(dp)            :: COEFF_FALLOFF ! Factor in pressure limiting rate constant
REAL(dp)            :: SEAWATER      ! Fraction of seawater in grid box
LOGICAL             :: OPEN_WATER    ! Is land category ice free open water?
LOGICAL             :: LSUNLIGHT     ! Logical that is true if photolysis rates 
REAL(dp)            :: TFAC

INTEGER, PARAMETER  :: KPP_NPHOTAB  =  32     ! number of photolysis rates
CHARACTER(16), SAVE :: KPP_PHOTAB( KPP_NPHOTAB )  ! Names of  photolysis
REAL(dp)            :: RJCELL( KPP_NPHOTAB )  ! grid cell photolysis rates ,[min
INTEGER, PARAMETER  :: IJ_NO2_IUPAC10           =   1
INTEGER, PARAMETER  :: IJ_O3_O3P_IUPAC10        =   2
INTEGER, PARAMETER  :: IJ_O3_O1D_IUPAC10        =   3
INTEGER, PARAMETER  :: IJ_H2O2_IUPAC10          =   4
INTEGER, PARAMETER  :: IJ_NO3NO2_06             =   5
INTEGER, PARAMETER  :: IJ_NO3NO_06              =   6
INTEGER, PARAMETER  :: IJ_N2O5_IUPAC10          =   7
INTEGER, PARAMETER  :: IJ_HONO_IUPAC10          =   8
INTEGER, PARAMETER  :: IJ_HNO3_IUPAC10          =   9
INTEGER, PARAMETER  :: IJ_PNA_IUPAC10           =   10
INTEGER, PARAMETER  :: IJ_PAN_IUPAC10           =   11
INTEGER, PARAMETER  :: IJ_MEPX_IUPAC10          =   12
INTEGER, PARAMETER  :: IJ_NTR_IUPAC10           =   13
INTEGER, PARAMETER  :: IJ_FORM_R_IUPAC13        =   14
INTEGER, PARAMETER  :: IJ_FORM_M_IUPAC13        =   15
INTEGER, PARAMETER  :: IJ_ALD2_R_IUPAC13        =   16
INTEGER, PARAMETER  :: IJ_ALDX_R_IUPAC13        =   17
INTEGER, PARAMETER  :: IJ_GLYD_IUPAC13          =   18
INTEGER, PARAMETER  :: IJ_GLY_R_IUPAC13         =   19
INTEGER, PARAMETER  :: IJ_MGLY_IUPAC10          =   20
INTEGER, PARAMETER  :: IJ_KET_IUPAC10           =   21
INTEGER, PARAMETER  :: IJ_ACET_IUPAC10          =   22
INTEGER, PARAMETER  :: IJ_ISPD                  =   23
INTEGER, PARAMETER  :: IJ_HPALD                 =   24
INTEGER, PARAMETER  :: IJ_CL2_IUPAC04           =   25
INTEGER, PARAMETER  :: IJ_HOCL_IUPAC04          =   26
INTEGER, PARAMETER  :: IJ_FMCL_IUPAC04          =   27
INTEGER, PARAMETER  :: IJ_CLNO2_IUPAC13         =   28
INTEGER, PARAMETER  :: IJ_CLONO2_1              =   29
INTEGER, PARAMETER  :: IJ_CLONO2_2              =   30
INTEGER, PARAMETER  :: IJ_IC3ONO2               =   31
INTEGER, PARAMETER  :: IJ_ACRO_09               =   32
DATA KPP_PHOTAB(  1 ) / 'NO2_IUPAC10     ' /
DATA KPP_PHOTAB(  2 ) / 'O3_O3P_IUPAC10  ' /
DATA KPP_PHOTAB(  3 ) / 'O3_O1D_IUPAC10  ' /
DATA KPP_PHOTAB(  4 ) / 'H2O2_IUPAC10    ' /
DATA KPP_PHOTAB(  5 ) / 'NO3NO2_06       ' /
DATA KPP_PHOTAB(  6 ) / 'NO3NO_06        ' /
DATA KPP_PHOTAB(  7 ) / 'N2O5_IUPAC10    ' /
DATA KPP_PHOTAB(  8 ) / 'HONO_IUPAC10    ' /
DATA KPP_PHOTAB(  9 ) / 'HNO3_IUPAC10    ' /
DATA KPP_PHOTAB( 10 ) / 'PNA_IUPAC10     ' /
DATA KPP_PHOTAB( 11 ) / 'PAN_IUPAC10     ' /
DATA KPP_PHOTAB( 12 ) / 'MEPX_IUPAC10    ' /
DATA KPP_PHOTAB( 13 ) / 'NTR_IUPAC10     ' /
DATA KPP_PHOTAB( 14 ) / 'FORM_R_IUPAC13  ' /
DATA KPP_PHOTAB( 15 ) / 'FORM_M_IUPAC13  ' /
DATA KPP_PHOTAB( 16 ) / 'ALD2_R_IUPAC13  ' /
DATA KPP_PHOTAB( 17 ) / 'ALDX_R_IUPAC13  ' /
DATA KPP_PHOTAB( 18 ) / 'GLYD_IUPAC13    ' /
DATA KPP_PHOTAB( 19 ) / 'GLY_R_IUPAC13   ' /
DATA KPP_PHOTAB( 20 ) / 'MGLY_IUPAC10    ' /
DATA KPP_PHOTAB( 21 ) / 'KET_IUPAC10     ' /
DATA KPP_PHOTAB( 22 ) / 'ACET_IUPAC10    ' /
DATA KPP_PHOTAB( 23 ) / 'ISPD            ' /
DATA KPP_PHOTAB( 24 ) / 'HPALD           ' /
DATA KPP_PHOTAB( 25 ) / 'CL2_IUPAC04     ' /
DATA KPP_PHOTAB( 26 ) / 'HOCL_IUPAC04    ' /
DATA KPP_PHOTAB( 27 ) / 'FMCL_IUPAC04    ' /
DATA KPP_PHOTAB( 28 ) / 'CLNO2_IUPAC13   ' /
DATA KPP_PHOTAB( 29 ) / 'CLONO2_1        ' /
DATA KPP_PHOTAB( 30 ) / 'CLONO2_2        ' /
DATA KPP_PHOTAB( 31 ) / 'IC3ONO2         ' /
DATA KPP_PHOTAB( 32 ) / 'ACRO_09         ' /

INTEGER, PARAMETER  :: KPP_NHETERO  =  17     ! number of heterogeneous rates
CHARACTER(16), SAVE :: KPP_HETERO( KPP_NHETERO )  ! Names of  heterogeneous
REAL(dp)            :: KHETCELL( KPP_NHETERO )  ! grid cell heterogeneous rates 
INTEGER, PARAMETER  :: IK_HETERO_CLNO3_WAI      =   1
INTEGER, PARAMETER  :: IK_HETERO_CLNO3_WAJ      =   2
INTEGER, PARAMETER  :: IK_HETERO_NTR2           =   3
INTEGER, PARAMETER  :: IK_HETERO_N2O5IJ         =   4
INTEGER, PARAMETER  :: IK_HETERO_N2O5K          =   5
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PAIJ      =   6
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PAK       =   7
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PBIJ      =   8
INTEGER, PARAMETER  :: IK_HETERO_H2NO3PBK       =   9
INTEGER, PARAMETER  :: IK_HETERO_NO2            =   10
INTEGER, PARAMETER  :: IK_HETERO_IEPOX          =   11
INTEGER, PARAMETER  :: IK_HETERO_IEPOXOS        =   12
INTEGER, PARAMETER  :: IK_HETERO_TETROL         =   13
INTEGER, PARAMETER  :: IK_HETERO_GLY            =   14
INTEGER, PARAMETER  :: IK_HETERO_MGLY           =   15
INTEGER, PARAMETER  :: IK_HETERO_PNCOMLI        =   16
INTEGER, PARAMETER  :: IK_HETERO_PNCOMLJ        =   17
DATA KPP_HETERO(  1 ) / 'HETERO_CLNO3_WAI' /
DATA KPP_HETERO(  2 ) / 'HETERO_CLNO3_WAJ' /
DATA KPP_HETERO(  3 ) / 'HETERO_NTR2     ' /
DATA KPP_HETERO(  4 ) / 'HETERO_N2O5IJ   ' /
DATA KPP_HETERO(  5 ) / 'HETERO_N2O5K    ' /
DATA KPP_HETERO(  6 ) / 'HETERO_H2NO3PAIJ' /
DATA KPP_HETERO(  7 ) / 'HETERO_H2NO3PAK ' /
DATA KPP_HETERO(  8 ) / 'HETERO_H2NO3PBIJ' /
DATA KPP_HETERO(  9 ) / 'HETERO_H2NO3PBK ' /
DATA KPP_HETERO( 10 ) / 'HETERO_NO2      ' /
DATA KPP_HETERO( 11 ) / 'HETERO_IEPOX    ' /
DATA KPP_HETERO( 12 ) / 'HETERO_IEPOXOS  ' /
DATA KPP_HETERO( 13 ) / 'HETERO_TETROL   ' /
DATA KPP_HETERO( 14 ) / 'HETERO_GLY      ' /
DATA KPP_HETERO( 15 ) / 'HETERO_MGLY     ' /
DATA KPP_HETERO( 16 ) / 'HETERO_PNCOMLI  ' /
DATA KPP_HETERO( 17 ) / 'HETERO_PNCOMLJ  ' /


! Related to cloud chemistry
REAL(dp), PARAMETER :: DDIAM = 1.6D-5 ! Droplet Diameter (m)
REAL(dp), PARAMETER :: DAQ = 1.0D-9   ! Aqueous phase diffusion coefficient (m2/
REAL(dp)            :: LWC_RS        ! Resolved cloud lwc (kg/m3)
REAL(dp)            :: LWC_CV        ! Convective cloud lwc (kg/m3)
REAL(dp)            :: XCL_RS        ! Calculated resolved cloud chemistry (1=ye
REAL(dp)            :: XCL_CV        ! Calculated convective cloud chemistry (1=
REAL(dp)            :: PHI2_RS       !
REAL(dp)            :: PHI2_CV       !
REAL(dp)            :: GM1_RS        !
REAL(dp)            :: GM1_CV        !
REAL(dp)            :: GM2_RS        !
REAL(dp)            :: GM2_CV        !
REAL(dp)            :: WFAC_RS       !
REAL(dp)            :: WFAC_CV       !
REAL(dp)            :: KPP_ALFA3_RS  !
REAL(dp)            :: KPP_ALFA3_CV  !
LOGICAL             :: LCL_RS = .FALSE.
LOGICAL             :: LCL_CV = .FALSE.
LOGICAL             :: LCL    = .FALSE.
REAL(dp), PARAMETER :: CFRAC_RS = 1.0D0
REAL(dp)            :: CFRAC_CV
! Henry's law constants. Just temporary
REAL(dp)            :: H_SO2, H_HNO3, H_CO2, H_NH3, H_H2O2
REAL(dp)            :: H_O3, H_FACD, H_HCL, H_GLY, H_MGLY
REAL(dp)            :: H_OH, H_HO2, H_NO2, H_HONO, H_HNO4
REAL(dp)            :: H_GLYD, H_AACD, H_FORM, H_NO3, H_CH3O2
REAL(dp)            :: H_IEPOX, H_MHP, H_PAA
REAL(dp)            :: H_IMAE, H_IHMML
! Scavenging rates
REAL(dp)            :: KPP_RSCAV(NSPEC)
! IEPOX related
INTEGER, PARAMETER  :: ISPC8 = 0     ! = 0 if aerosol module is not AE6I or AE7I
                                     ! = 1 if aerosol module is AE6I or AE7I

! INLINED global variable declarations


END MODULE mchem_Global

