! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mchem_Rates.f90
! Time                 : Fri Jul  5 14:05:29 2024
! Working directory    : /DFS-L/DATA/carlton/srosanka/code/CMAQ_MCHEM/UTIL/mchemmech
! Equation file        : mchem.kpp
! Output root filename : mchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mchem_Rates

  USE mchem_Parameters
  USE mchem_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


REAL(kind=dp) FUNCTION FALL_OFF ( A0,B0,C0,A1,B1,C1,CE,CF)
  IMPLICIT NONE
  REAL(kind=dp), INTENT( IN ) :: A0,B0,C0,A1,B1,C1,CE,CF
  REAL(kind=dp) K0, K1, KEND
! K0 = A0 * COEFF_FALLOFF * DEXP(B0/TEMP)* (TEMP/300.0_dp)**C0
! K1 = A1 * DEXP(B1/TEMP) * (TEMP/300.0_dp)**C1
  K0 = A0 * COEFF_FALLOFF * DEXP(B0*INV_TEMP)* (TEMP/300.0_dp)**C0
  K1 = A1 * DEXP(B1*INV_TEMP) * (TEMP/300.0_dp)**C1
  KEND = ( ( 1.0_dp + ( ( 1.0_dp / CE ) * DLOG10( K0 / K1 ) ) ** 2.0_dp ) )
  KEND = 1.0_dp / KEND
  FALL_OFF = ( K0 / ( 1.0_dp + K0/K1 ) ) * CF ** KEND
END FUNCTION FALL_OFF

REAL( kind=dp ) FUNCTION HALOGEN_FALLOFF(A1,B1,A2,B2,A3)
   IMPLICIT NONE
   REAL( kind=dp ), INTENT( IN ) :: A1
   REAL( kind=dp ), INTENT( IN ) :: B1
   REAL( kind=dp ), INTENT( IN ) :: A2
   REAL( kind=dp ), INTENT( IN ) :: B2
   REAL( kind=dp ), INTENT( IN ) :: A3
   INTRINSIC DEXP
   IF ( ( OPEN_WATER ) .AND. LSUNLIGHT ) THEN
       HALOGEN_FALLOFF = A1 * DEXP( B1 * PRESS ) + A2 * DEXP( B2 * PRESS )
       HALOGEN_FALLOFF = DMIN1( A3, HALOGEN_FALLOFF) 
       HALOGEN_FALLOFF = HALOGEN_FALLOFF * SEAWATER
   ELSE
       HALOGEN_FALLOFF = 0.0_dp
   END IF
   RETURN
END FUNCTION HALOGEN_FALLOFF

   REAL(kind=dp) FUNCTION ARR2_DP( A0,B0 )
   ! Same as ARR2 just taking A0 and B0 in dp
      REAL(kind=dp) A0,B0
      ARR2_DP =  A0 * EXP( B0/TEMP )
   END FUNCTION ARR2_DP

       REAL( kind=dp ) FUNCTION POWER_T02( A0,B0 )
         IMPLICIT NONE
! rate constant for CMAQ Arrhenuis reaction type 2
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         ! Local
         REAL( kind=dp ) :: TEMPOT300
         TEMPOT300 = TEMP / 300.0D0
         POWER_T02 =  A0 * TEMPOT300**B0
         RETURN
       END FUNCTION POWER_T02

       REAL( kind=dp ) FUNCTION ARRHENUIS_T04( A0,B0,C0 )
         IMPLICIT NONE
! rate constant for CMAQ Arrhenuis reaction type 4
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         REAL( kind=dp ), INTENT( IN ) :: C0
         ! Local:
         INTRINSIC DEXP
         REAL( kind=dp ) :: INV_TEMP
         REAL( kind=dp ) :: TEMPOT300
         INV_TEMP  = 1.0D0 / TEMP
         TEMPOT300 = TEMP / 300.0D0
         ARRHENUIS_T04 =  A0 * DEXP( B0 * INV_TEMP ) * TEMPOT300**C0
         RETURN
       END FUNCTION ARRHENUIS_T04

       REAL( kind=dp ) FUNCTION FALLOFF_T08(A0,C0,A2,C2,A3,C3)
! rate constant for CMAQ fall off reaction type 8
         IMPLICIT NONE
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: C0
         REAL( kind=dp ), INTENT( IN ) :: A2
         REAL( kind=dp ), INTENT( IN ) :: C2
         REAL( kind=dp ), INTENT( IN ) :: A3
         REAL( kind=dp ), INTENT( IN ) :: C3
         ! Local:
         REAL( kind=dp ) K0
         REAL( kind=dp ) K2
         REAL( kind=dp ) K3
         REAL( kind=dp ) :: INV_TEMP
         INTRINSIC DEXP
         INV_TEMP  = 1.0D0 / TEMP
         K0 = A0 * DEXP( C0 * INV_TEMP )
         K2 = A2 * DEXP( C2 * INV_TEMP )
         K3 = A3 * DEXP( C3 * INV_TEMP )
         K3 = K3 * COEFF_FALLOFF
         FALLOFF_T08 = K0 + K3/( 1.0D0 + K3/K2 )
         RETURN
       END FUNCTION FALLOFF_T08

       REAL( kind=dp ) FUNCTION FALLOFF_T09(A1,C1,A2,C2)
! rate constant for CMAQ fall off reaction type 9
         IMPLICIT NONE
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A1
         REAL( kind=dp ), INTENT( IN ) :: C1
         REAL( kind=dp ), INTENT( IN ) :: A2
         REAL( kind=dp ), INTENT( IN ) :: C2
         !  Local:
         REAL( kind=dp ) K1
         REAL( kind=dp ) K2
         REAL( kind=dp ) :: INV_TEMP
         INTRINSIC DEXP
         INV_TEMP  = 1.0D0 / TEMP
         K1 = A1 * DEXP( C1 * INV_TEMP )
         K2 = A2 * DEXP( C2 * INV_TEMP )
         FALLOFF_T09 = K1 + K2 * COEFF_FALLOFF
         RETURN
       END FUNCTION FALLOFF_T09
       REAL( kind=dp ) FUNCTION FALLOFF_T10(A0,B0,C0,A1,B1,C1,CE,CF)
         IMPLICIT NONE
! rate constant for CMAQ fall off reaction type 10
! Arguements:
         REAL( kind=dp ), INTENT( IN ) :: A0
         REAL( kind=dp ), INTENT( IN ) :: B0
         REAL( kind=dp ), INTENT( IN ) :: C0
         REAL( kind=dp ), INTENT( IN ) :: A1
         REAL( kind=dp ), INTENT( IN ) :: B1
         REAL( kind=dp ), INTENT( IN ) :: C1
         REAL( kind=dp ), INTENT( IN ) :: CE
         REAL( kind=dp ), INTENT( IN ) :: CF
         ! Local:
         REAL( kind=dp ) K0
         REAL( kind=dp ) K1
         REAL( kind=dp ) KEND
         REAL( kind=dp ) :: INV_TEMP
         REAL( kind=dp ) :: TEMPOT300
         INV_TEMP  = 1.0D0 / TEMP
         TEMPOT300 = TEMP / 300.0D0
         K0 = A0 * COEFF_FALLOFF * DEXP(B0*INV_TEMP)* TEMPOT300**C0
         K1 = A1 * DEXP(B1*INV_TEMP) * TEMPOT300**C1
         KEND = ( ( 1.0D0 + ( ( 1.0D0 / CE ) * DLOG10( K0 / K1 ) ) ** 2.0D0 ) )
         KEND = 1.0D0 / KEND
         FALLOFF_T10 = ( K0 / ( 1.0D0 + K0/K1 ) ) * CF ** KEND
         RETURN
       END FUNCTION FALLOFF_T10

REAL( dp ) FUNCTION KMT(TEMP,LWC,MMASS,DG,HENRY,ACOM,FB)
  IMPLICIT NONE
  REAL( dp ), INTENT( IN ) :: TEMP
  REAL( dp ), INTENT( IN ) :: LWC
  REAL( dp ), INTENT( IN ) :: MMASS
  REAL( dp ), INTENT( IN ) :: DG
  REAL( dp ), INTENT( IN ) :: HENRY
  REAL( dp ), INTENT( IN ) :: ACOM
  INTEGER,   INTENT( IN ) :: FB ! logical (forward/backward)
  REAL( dp )               :: RAD
  REAL( dp )               :: R_KMT
  REAL( dp )               :: R2_KMT
  REAL( dp )               :: PI_KMT
  REAL( dp )               :: V_mean
  INTRINSIC DEXP

  RAD    = DDIAM * 0.5D0
  R_KMT  = 8.3145D0
  R2_KMT = 0.08206D0
  PI_KMT = 3.1415926536D0

  V_mean = SQRT( 8D0 * R_KMT * TEMP * 1000.0D0 / PI_KMT / MMASS )
  KMT    = 1.0D0/((RAD*RAD)/(3D0*DG)+(4D0*RAD/(3D0*V_mean*ACOM)))
  IF ( FB .EQ. 0 ) THEN
     KMT = KMT * LWC / 1000.0D0
  ELSE
     KMT   = KMT  / ( R2_KMT * TEMP * HENRY )
  END IF
  RETURN
END FUNCTION KMT

REAL( kind=dp )FUNCTION KRXN ( KR, DH, RTYPE, QY, METAL, CLTYPE )

     IMPLICIT NONE

     ! Input
     REAL( kind=dp )     , INTENT( IN ) :: KR, DH
     INTEGER             , INTENT( IN ) :: QY, RTYPE, METAL
     CHARACTER( LEN = 2 ), INTENT( IN ) :: CLTYPE

     ! Local variables
     REAL( kind=dp )      :: Q, q1, COTHq, SVIinh
     REAL( kind=dp )      :: kO31, kO32, kO33, kO3T
     INTEGER              :: ind_L_H2SO4, ind_L_HSO4MIN, ind_L_SO4MIN2
     INTEGER              :: ind_L_HPLUS
     INTEGER              :: ind_L_SO2, ind_L_HSO3MIN, ind_L_SO3MIN2
     REAL( kind=dp )      :: PHI2

     ! Select cloud indices and properties
     IF ( CLTYPE .EQ. 'RS' ) THEN
       IND_L_HPLUS   = ind_Hp_RS
       IND_L_H2SO4   = ind_SULF_RS
       IND_L_HSO4MIN = ind_HSO4m_RS
       IND_L_SO4MIN2 = ind_SO4mm_RS
       IND_L_SO2     = ind_SO2_RS
       IND_L_HSO3MIN = ind_HSO3m_RS
       IND_L_SO3MIN2 = ind_SO3mm_RS
       PHI2          = PHI2_RS
     ELSE IF ( CLTYPE .EQ. 'CV' ) THEN
       IND_L_HPLUS   = ind_Hp_CV
       IND_L_H2SO4   = ind_SULF_CV
       IND_L_HSO4MIN = ind_HSO4m_CV
       IND_L_SO4MIN2 = ind_SO4mm_CV
       IND_L_SO2     = ind_SO2_CV
       IND_L_HSO3MIN = ind_HSO3m_CV
       IND_L_SO3MIN2 = ind_SO3mm_CV
       PHI2          = PHI2_CV
     END IF


     KRXN = KR * EXP( DH * TFAC )

     IF ( RTYPE .EQ. 1 ) THEN   ! SO2 - H2O2 OXIDATION
        KRXN = ( KRXN / ( 1.0D0 + 13.0D0 * VAR( ind_L_HPLUS ) * PHI2 ) ) * PHI2
!    ELSE IF ( RTYPE .EQ. 2 ) then   ! SO2 - PAA OXIDATION
!       KRXN = KRXN * (VAR(ind_L_HPLUS) * PHI2) + 7.00D2
     ELSE IF ( RTYPE .EQ. 3 ) then   ! SO2 - Fe3/Mn2 synergism and
        KRXN = KRXN * PHI2           ! MHP and PAA reaction
     ELSE IF ( RTYPE .EQ. 4 ) then   ! only one reactant
        KRXN = KRXN / PHI2
     END IF

     ! SO4 inhibition only for metal-catalyzed oxidation
     IF (METAL .GT. 0) THEN
        ! SO4 inhibition of metal catalysis
        SVIinh = 1.0D0 + 75.0D0 * ( ( VAR( ind_L_H2SO4 )     &
                 +                    VAR( ind_L_HSO4MIN )   &
                 +                    VAR( ind_L_SO4MIN2 ) ) &
                 * PHI2 )**0.67D0
        KRXN = KRXN / SVIinh
     END IF

!    Ionic strength impact on SIV-O3 reaction rate
!          IF (QY .GT. 0) THEN
!             KRXN = KRXN * (1.0D0 + 2.5 * STION)
!          END IF

!    Aqueous diffusion limitation for O3

     q1 = 0.0D0
     Q = 1.0D0

     IF( QY .GE. 1 ) THEN

        kO31 = 2.4D+4 * EXP( 0.0D0 * TFAC )
        kO32 = 3.7D+5 * EXP( -5530.88D0 * TFAC )
        kO33 = 1.5D+9 * EXP( -5280.56D0 * TFAC )
        kO3T = ( kO31 * VAR( ind_L_SO2 ) + kO32 &
             * VAR( ind_L_HSO3MIN ) &
             + kO33 * VAR( ind_L_SO3MIN2 ) ) * PHI2

        q1 = DDIAM / 2.0D0 * SQRT( kO3T / DAQ )  ! diffuso-reactive param

        IF ( q1 .GT. 1.0D-3 ) THEN
           IF ( q1 .LE. 100.0D0 ) THEN
              COTHq = ( EXP( 2 * q1 ) + 1 ) / ( EXP( 2 * q1 ) - 1 )
              Q = 3 * ( ( COTHq / q1 ) - ( 1 / ( q1 * q1 ) ) )
              IF ( Q .GT. 1.0D0 ) Q = 1.0D0
           ELSE
              Q = 3.d0/q1
           END IF
        ELSE
           Q = 1.0D0
        END IF

        KRXN = KRXN * Q

     END IF

     KRXN = KRXN * PHI2

     RETURN
END FUNCTION KRXN

REAL( kind=dp )FUNCTION KIEPOX ( KH, KHSO4, TYPE, CLTYPE )

     IMPLICIT NONE

     ! Input
     REAL( kind=dp ),      INTENT( IN ) :: KH, KHSO4
     INTEGER,              INTENT( IN ) :: TYPE
     CHARACTER( LEN = 2 ), INTENT( IN ) :: CLTYPE

     ! Local variables
     REAL( kind=dp )      :: K1, K2
     REAL( kind=dp )      :: KIEPOXT, KMAET
     REAL( kind=dp )      :: Q, q1, COTHq
     INTEGER              :: ind_L_HPLUS
     INTEGER              :: indf_L_H2O, ind_L_HSO4MIN, ind_L_SO4MIN2
     INTEGER              :: ind_L_NO3MIN, ind_L_IETET, ind_L_IEOS
     REAL( kind=dp )      :: PHI2

     ! Select cloud indices and properties
     IF ( CLTYPE .EQ. 'RS' ) THEN
       IND_L_HPLUS   = ind_Hp_RS
       INDF_L_H2O    = indf_H2O_RS
       IND_L_HSO4MIN = ind_HSO4m_RS
       IND_L_SO4MIN2 = ind_SO4mm_RS
       IND_L_NO3MIN  = ind_NO3m_RS
       IND_L_IETET   = ind_IETET_RS
       IND_L_IEOS    = ind_IEOS_RS
       PHI2          = PHI2_RS
     ELSE IF ( CLTYPE .EQ. 'CV' ) THEN
       IND_L_HPLUS   = ind_Hp_CV
       INDF_L_H2O    = indf_H2O_CV
       IND_L_HSO4MIN = ind_HSO4m_CV
       IND_L_SO4MIN2 = ind_SO4mm_CV
       IND_L_NO3MIN  = ind_NO3m_CV
       IND_L_IETET   = ind_IETET_CV
       IND_L_IEOS    = ind_IEOS_CV
       PHI2          = PHI2_CV
     END IF

     K1 = KH * VAR( ind_L_HPLUS ) * PHI2
     K2 = KHSO4 * VAR( ind_L_HSO4MIN ) * PHI2

     KIEPOX = K1 + K2
!
! Aqueous diffusion limitation for IEPOX and MAE
!
!
     q1 = 0.0D0
     Q = 1.0D0

     IF( TYPE .le. 1 ) THEN   ! FOR IEPOX

        K1 = 9.0D-4 * VAR( ind_L_HPLUS ) * PHI2
        K2 = 1.31D-5 * VAR( ind_L_HSO4MIN ) * PHI2
        KIEPOXT = (K1 + K2) * FIX( indf_L_H2O ) * PHI2  ! IEPOX + H2O

        K1 = 8.83D-3 * VAR( ind_L_HPLUS ) * PHI2
        K2 = 2.92D-6 * VAR( ind_L_HSO4MIN ) * PHI2
        KIEPOXT = KIEPOXT + (K1 + K2) * VAR( ind_L_SO4MIN2 ) &
                * PHI2  ! IEPOX + SO4

        K1 = 2.0D-4 * VAR( ind_L_HPLUS ) * PHI2
        K2 = 2.92D-6 * VAR( ind_L_HSO4MIN ) * PHI2

        IF( ISPC8 .LE. 0 ) THEN
           KIEPOXT = KIEPOXT + (K1 + K2) * VAR( ind_L_NO3MIN ) * PHI2    ! IEPOX
        ELSE
           KIEPOXT = KIEPOXT + (K1 + K2) * VAR( ind_L_IETET ) &
                   * PHI2    ! IEPOX + IETET
           KIEPOXT = KIEPOXT + (K1 + K2) * VAR( ind_L_IEOS ) &
                   * PHI2     ! IEPOX + IEOS
        ENDIF

        q1 = DDIAM/2.0D0 * SQRT( KIEPOXT / DAQ )

        IF ( q1 .GT. 1.0D-3 ) THEN
           IF ( q1 .LE. 100.0D0 ) THEN
              COTHq = ( EXP( 2 * q1 ) + 1 ) / ( EXP( 2 * q1 ) - 1 )
              Q = 3 * ( ( COTHq / q1 ) - ( 1 / ( q1 * q1 ) ) )
              IF ( Q .GT. 1.0D0 ) Q = 1.0D0
           ELSE
              Q = 3.d0/q1
           END IF
        ELSE
           Q = 1.0D0
        END IF

     ELSE   ! FOR MAE OR HMML

        K1 = 9.0D-4 * VAR( ind_L_HPLUS ) * PHI2
        K2 = 1.31D-5 * VAR( ind_L_HSO4MIN ) * PHI2
        KMAET = (K1 + K2) * FIX( indf_L_H2O ) &
              * PHI2  ! MAE/HMML + H2O

        K1 = 2.0D-4 * VAR( ind_L_HPLUS ) * PHI2
        K2 = 2.92D-6 * VAR( ind_L_HSO4MIN ) * PHI2
        KMAET = KMAET + (K1 + K2) * VAR( ind_L_SO4MIN2 ) &
              * PHI2  ! MAE/HMML + SO4

        q1 = DDIAM/2.0D0 * SQRT( KMAET / DAQ )

        IF ( q1 .GT. 1.0D-3 ) THEN
           IF ( q1 .LE. 100.0D0 ) THEN
              COTHq = ( EXP( 2 * q1 ) + 1 ) / ( EXP( 2 * q1 ) - 1 )
              Q = 3 * ( ( COTHq / q1 ) - ( 1 / ( q1 * q1 ) ) )
              IF ( Q .GT. 1.0D0 ) Q = 1.0D0
           ELSE
              Q = 3.d0/q1
           END IF
        ELSE
           Q = 1.0D0
        END IF
     END IF

     KIEPOX = KIEPOX * Q

     KIEPOX = KIEPOX * PHI2

     IF( ISPC8 .LE. 0 ) THEN
        IF( TYPE .GT. 0 ) KIEPOX = 0.d0
     ELSE
        IF( TYPE .LT. 1 ) KIEPOX = 0.d0
     END IF

     RETURN

END FUNCTION KIEPOX

! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE mchem_Parameters
      !USE mchem_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


  USE MCHEM_CLOUDS, ONLY: UPDATE_GM1_GM2

REAL(dp)  :: FALLOFF_T10_R4
REAL(dp)  :: FALLOFF_T10_R6
REAL(dp)  :: FALLOFF_T10_R17
REAL(dp)  :: FALLOFF_T10_R36
REAL(dp)  :: FALLOFF_T10_R37
REAL(dp)  :: FALLOFF_T10_R40
REAL(dp)  :: FALLOFF_T10_R45
REAL(dp)  :: FALLOFF_T08_R46
REAL(dp)  :: FALLOFF_T10_R48
REAL(dp)  :: FALLOFF_T10_R49
REAL(dp)  :: FALLOFF_T10_R52
REAL(dp)  :: FALLOFF_T10_R54
REAL(dp)  :: FALLOFF_T10_R55
REAL(dp)  :: FALLOFF_T10_R136
REAL(dp)  :: FALLOFF_T10_R138
REAL(dp)  :: FALLOFF_T10_R142
REAL(dp)  :: FALLOFF_T10_R217
REAL(dp)  :: FALLOFF_T10_R219
REAL(dp)  :: FALLOFF_T10_CL28
REAL(dp)  :: FALLOFF_T10_DMS2

FALLOFF_T10_R4 = FALLOFF_T10( 1.0000D-31,-0.0000D+00, &
-1.6000D+00,5.0000D-11, &
-0.0000D+00,3.0000D-01, &
8.4000D-01,8.5000D-01)
FALLOFF_T10_R6 = FALLOFF_T10( 1.3000D-31,-0.0000D+00, &
-1.5000D+00,2.3000D-11, &
-0.0000D+00,2.4000D-01, &
1.0300D+00,6.0000D-01)
FALLOFF_T10_R17 = FALLOFF_T10( 9.0000D-31,-0.0000D+00, &
-3.2000D+00,3.9000D-11, &
-0.0000D+00,-4.7000D-01, &
1.2300D+00,4.2000D-01)
FALLOFF_T10_R36 = FALLOFF_T10( 3.6000D-30,-0.0000D+00, &
-4.1000D+00,1.9000D-12, &
-0.0000D+00,2.0000D-01, &
1.3300D+00,3.5000D-01)
FALLOFF_T10_R37 = FALLOFF_T10( 1.3000D-03,-1.1000D+04, &
-3.5000D+00,9.7000D+14, &
-1.1080D+04,1.0000D-01, &
1.3300D+00,3.5000D-01)
FALLOFF_T10_R40 = FALLOFF_T10( 7.4000D-31,-0.0000D+00, &
-2.4000D+00,3.3000D-11, &
-0.0000D+00,-3.0000D-01, &
8.7000D-01,8.1000D-01)
FALLOFF_T10_R45 = FALLOFF_T10( 1.8000D-30,-0.0000D+00, &
-3.0000D+00,2.8000D-11, &
-0.0000D+00,1.0000D+00, &
1.0000D+00,6.0000D-01)
FALLOFF_T08_R46 = FALLOFF_T08( 2.4000D-14,4.6000D+02, &
2.7000D-17,2.1990D+03, &
6.5000D-34,1.3350D+03 )
FALLOFF_T10_R48 = FALLOFF_T10( 1.4000D-31,-0.0000D+00, &
-3.1000D+00,4.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.2600D+00,4.0000D-01)
FALLOFF_T10_R49 = FALLOFF_T10( 4.1000D-05,-1.0650D+04, &
1.0000D+00,6.0000D+15, &
-1.1170D+04,1.0000D+00, &
1.2600D+00,4.0000D-01)
FALLOFF_T10_R52 = FALLOFF_T10( 2.8000D-31,-0.0000D+00, &
-2.6000D+00,2.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.1000D+00,5.3000D-01)
FALLOFF_T10_R54 = FALLOFF_T10( 3.6100D-28,-0.0000D+00, &
-6.8700D+00,1.2400D-11, &
-0.0000D+00,-1.1050D+00, &
1.4100D+00,3.0000D-01)
FALLOFF_T10_R55 = FALLOFF_T10( 1.1000D-05,-1.0100D+04, &
1.0000D+00,1.9000D+17, &
-1.4100D+04,1.0000D+00, &
1.4100D+00,3.0000D-01)
FALLOFF_T10_R136 = FALLOFF_T10( 5.0000D-30,-0.0000D+00, &
-1.5000D+00,1.0000D-12, &
-0.0000D+00,1.0000D+00, &
1.3000D+00,3.7000D-01)
FALLOFF_T10_R138 = FALLOFF_T10( 8.6000D-29,-0.0000D+00, &
-3.1000D+00,9.0000D-12, &
-0.0000D+00,-8.5000D-01, &
1.1500D+00,4.8000D-01)
FALLOFF_T10_R142 = FALLOFF_T10( 8.0000D-27,-0.0000D+00, &
-3.5000D+00,3.0000D-11, &
-0.0000D+00,-1.0000D+00, &
1.1300D+00,5.0000D-01)
FALLOFF_T10_R217 = FALLOFF_T10( 2.3700D-21,-0.0000D+00, &
1.0000D+00,4.0700D-01, &
-0.0000D+00,-8.0000D+00, &
1.0000D+00,4.1000D-01)
FALLOFF_T10_R219 = FALLOFF_T10( 4.8100D-20,-0.0000D+00, &
1.0000D+00,4.0700D-01, &
-0.0000D+00,-8.0000D+00, &
1.0000D+00,4.1000D-01)
FALLOFF_T10_CL28 = FALLOFF_T10( 1.8000D-31,-0.0000D+00, &
-3.4000D+00,1.5000D-11, &
-0.0000D+00,-1.9000D+00, &
1.0000D+00,6.0000D-01)
FALLOFF_T10_DMS2 = FALLOFF_T10( 1.9900D-39,5.2700D+03, &
1.0000D+00,1.2600D-10, &
-3.4000D+02,1.0000D+00, &
1.0000D+00,1.0000D+00)


  ! Update aqueous diffusion correction (GM1 & GM2)
  IF ( LCL_RS ) CALL UPDATE_GM1_GM2( GM1_RS, GM2_RS, PHI2_RS, VAR, 1 )
  IF ( LCL_CV ) CALL UPDATE_GM1_GM2( GM1_CV, GM2_CV, PHI2_CV, VAR, 2 )

! End INLINED RCONST

  RCONST(1) = (1.0*RJCELL(IJ_NO2_IUPAC10))
  RCONST(2) = (POWER_T02(6.0000D-34,-2.6000D+00))
  RCONST(3) = (ARR2_DP(2.0700D-12,-1.4000D+03))
  RCONST(4) = (FALLOFF_T10_R4)
  RCONST(5) = (ARR2_DP(5.1000D-12,1.9800D+02))
  RCONST(6) = (FALLOFF_T10_R6)
  RCONST(7) = (ARR2_DP(8.0000D-12,-2.0600D+03))
  RCONST(8) = (1.0*RJCELL(IJ_O3_O3P_IUPAC10))
  RCONST(9) = (1.0*RJCELL(IJ_O3_O1D_IUPAC10))
  RCONST(10) = (ARR2_DP(2.2300D-11,1.1500D+02))
! RCONST(11) = constant rate coefficient
  RCONST(12) = (ARR2_DP(1.7000D-12,-9.4000D+02))
  RCONST(13) = (ARRHENUIS_T04(2.0300D-16,6.9300D+02,4.5700D+00))
  RCONST(14) = (ARR2_DP(2.4000D-11,1.1000D+02))
  RCONST(15) = (ARR2_DP(3.0000D-11,2.0000D+02))
  RCONST(16) = (ARRHENUIS_T04(6.2000D-14,9.4500D+02,2.6000D+00))
  RCONST(17) = (FALLOFF_T10_R17)
  RCONST(18) = (ARR2_DP(4.8000D-11,2.5000D+02))
  RCONST(19) = (FALLOFF_T09(2.2000D-13,6.0000D+02,1.9000D-33,9.8000D+02))
  RCONST(20) = (FALLOFF_T09(3.0800D-34,2.8000D+03,2.6600D-54,3.1800D+03))
  RCONST(21) = (1.0*RJCELL(IJ_H2O2_IUPAC10))
! RCONST(22) = constant rate coefficient
  RCONST(23) = (ARR2_DP(1.4000D-12,-2.0000D+03))
  RCONST(24) = (ARR2_DP(4.2500D-39,6.6400D+02))
  RCONST(25) = (ARR2_DP(3.4500D-12,2.7000D+02))
  RCONST(26) = (ARR2_DP(1.4000D-13,-2.4700D+03))
  RCONST(27) = (1.0*RJCELL(IJ_NO3NO2_06))
  RCONST(28) = (1.0*RJCELL(IJ_NO3NO_06))
  RCONST(29) = (ARR2_DP(1.8000D-11,1.1000D+02))
  RCONST(30) = (ARR2_DP(4.5000D-14,-1.2600D+03))
! RCONST(31) = constant rate coefficient
! RCONST(32) = constant rate coefficient
! RCONST(33) = constant rate coefficient
! RCONST(34) = constant rate coefficient
  RCONST(35) = (ARR2_DP(8.5000D-13,-2.4500D+03))
  RCONST(36) = (FALLOFF_T10_R36)
  RCONST(37) = (FALLOFF_T10_R37)
  RCONST(38) = (1.0*RJCELL(IJ_N2O5_IUPAC10))
! RCONST(39) = constant rate coefficient
  RCONST(40) = (FALLOFF_T10_R40)
  RCONST(41) = (5.0000D-40)
! RCONST(42) = constant rate coefficient
  RCONST(43) = (1.0*RJCELL(IJ_HONO_IUPAC10))
  RCONST(44) = (ARR2_DP(2.5000D-12,2.6000D+02))
  RCONST(45) = (FALLOFF_T10_R45)
  RCONST(46) = (FALLOFF_T08_R46)
  RCONST(47) = (1.0*RJCELL(IJ_HNO3_IUPAC10))
  RCONST(48) = (FALLOFF_T10_R48)
  RCONST(49) = (FALLOFF_T10_R49)
  RCONST(50) = (1.0*RJCELL(IJ_PNA_IUPAC10))
  RCONST(51) = (ARR2_DP(3.2000D-13,6.9000D+02))
  RCONST(52) = (FALLOFF_T10_R52)
  RCONST(53) = (ARR2_DP(7.5000D-12,2.9000D+02))
  RCONST(54) = (FALLOFF_T10_R54)
  RCONST(55) = (FALLOFF_T10_R55)
  RCONST(56) = (1.0*RJCELL(IJ_PAN_IUPAC10))
  RCONST(57) = (ARR2_DP(3.1400D-12,5.8000D+02))
  RCONST(58) = (ARR2_DP(4.4000D-13,1.0700D+03))
  RCONST(59) = (ARR2_DP(2.9000D-12,5.0000D+02))
  RCONST(60) = (1.00E+0*RCONST(59))
  RCONST(61) = (ARR2_DP(6.7000D-12,3.4000D+02))
  RCONST(62) = (8.4E-1*RCONST(54))
  RCONST(63) = (8.4E-1*RCONST(55))
  RCONST(64) = (1.0*RJCELL(IJ_PAN_IUPAC10))
  RCONST(65) = (1.00E+0*RCONST(57))
  RCONST(66) = (1.00E+0*RCONST(58))
  RCONST(67) = (1.00E+0*RCONST(59))
  RCONST(68) = (ARR2_DP(2.4000D-12,3.6000D+02))
  RCONST(69) = (ARR2_DP(4.8000D-13,8.0000D+02))
  RCONST(70) = (ARR2_DP(6.5000D-14,5.0000D+02))
  RCONST(71) = (ARR2_DP(2.3000D-12,3.6000D+02))
  RCONST(72) = (ARR2_DP(3.8000D-13,7.8000D+02))
  RCONST(73) = (ARR2_DP(2.0000D-12,5.0000D+02))
  RCONST(74) = (1.0*RCONST(70))
  RCONST(75) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(76) = (ARR2_DP(6.8000D-13,8.0000D+02))
  RCONST(77) = (1.0*RCONST(58))
  RCONST(78) = (1.00E+0*RCONST(70))
  RCONST(79) = (1.00E+0*RCONST(75))
  RCONST(80) = (1.00E+0*RCONST(76))
  RCONST(81) = (1.0*RCONST(58))
  RCONST(82) = (1.00E+0*RCONST(70))
  RCONST(83) = (1.00E+0*RCONST(75))
  RCONST(84) = (1.00E+0*RCONST(76))
  RCONST(85) = (1.0*RCONST(58))
  RCONST(86) = (1.00E+0*RCONST(70))
  RCONST(87) = (ARR2_DP(5.3000D-12,1.9000D+02))
  RCONST(88) = (1.0*RJCELL(IJ_MEPX_IUPAC10))
  RCONST(89) = (ARR2_DP(5.3000D-12,1.9000D+02))
  RCONST(90) = (1.0*RJCELL(IJ_MEPX_IUPAC10))
! RCONST(91) = constant rate coefficient
  RCONST(92) = (1.0*RJCELL(IJ_NTR_IUPAC10))
! RCONST(93) = constant rate coefficient
  RCONST(94) = (ARR2_DP(4.0000D-14,8.5000D+02))
  RCONST(95) = (ARR2_DP(5.3000D-12,1.9000D+02))
  RCONST(96) = (ARR2_DP(5.4000D-12,1.3500D+02))
  RCONST(97) = (1.0*RJCELL(IJ_FORM_R_IUPAC13))
  RCONST(98) = (1.0*RJCELL(IJ_FORM_M_IUPAC13))
  RCONST(99) = (ARR2_DP(3.4000D-11,-1.6000D+03))
! RCONST(100) = constant rate coefficient
  RCONST(101) = (ARR2_DP(9.7000D-15,6.2500D+02))
  RCONST(102) = (ARR2_DP(2.4000D+12,-7.0000D+03))
! RCONST(103) = constant rate coefficient
  RCONST(104) = (ARR2_DP(5.6000D-15,2.3000D+03))
  RCONST(105) = (ARR2_DP(1.8000D-11,-1.1000D+03))
  RCONST(106) = (ARR2_DP(4.7000D-12,3.4500D+02))
  RCONST(107) = (ARR2_DP(1.4000D-12,-1.8600D+03))
  RCONST(108) = (1.0*RJCELL(IJ_ALD2_R_IUPAC13))
  RCONST(109) = (ARR2_DP(1.3000D-11,-8.7000D+02))
  RCONST(110) = (ARR2_DP(4.9000D-12,4.0500D+02))
! RCONST(111) = constant rate coefficient
  RCONST(112) = (1.0*RJCELL(IJ_ALDX_R_IUPAC13))
! RCONST(113) = constant rate coefficient
  RCONST(114) = (1.0*RJCELL(IJ_GLYD_IUPAC13))
  RCONST(115) = (1.00E+0*RCONST(107))
  RCONST(116) = (ARR2_DP(3.1000D-12,3.4000D+02))
  RCONST(117) = (1.0*RJCELL(IJ_GLY_R_IUPAC13))
! RCONST(118) = constant rate coefficient
  RCONST(119) = (1.0*RJCELL(IJ_MGLY_IUPAC10))
! RCONST(120) = constant rate coefficient
  RCONST(121) = (ARR2_DP(1.9000D-12,5.7500D+02))
  RCONST(122) = (ARR2_DP(7.7000D-12,-2.1000D+03))
  RCONST(123) = (FALLOFF_T09(1.4400D-13,-0.0000D+00,3.4300D-33,-0.0000D+00))
  RCONST(124) = (ARR2_DP(1.8500D-12,-1.6900D+03))
  RCONST(125) = (ARR2_DP(6.9000D-12,-1.0000D+03))
  RCONST(126) = (ARR2_DP(2.8500D-12,-3.4500D+02))
  RCONST(127) = (ARR2_DP(3.0000D-12,2.0000D+01))
  RCONST(128) = (1.0*RJCELL(IJ_KET_IUPAC10))
  RCONST(129) = (1.0*RJCELL(IJ_ACET_IUPAC10))
  RCONST(130) = (ARR2_DP(1.4100D-12,-6.2060D+02))
  RCONST(131) = (ARR2_DP(7.6000D-12,-5.8500D+02))
! RCONST(132) = constant rate coefficient
  RCONST(133) = (ARR2_DP(5.7000D+12,-5.7800D+03))
  RCONST(134) = (ARR2_DP(1.5000D-14,-2.0000D+02))
  RCONST(135) = (ARR2_DP(8.6000D-12,4.0000D+02))
  RCONST(136) = (FALLOFF_T10_R136)
  RCONST(137) = (ARR2_DP(1.0400D-11,-7.9200D+02))
  RCONST(138) = (FALLOFF_T10_R138)
  RCONST(139) = (ARR2_DP(6.8200D-15,-2.5000D+03))
  RCONST(140) = (ARR2_DP(3.3000D-12,-2.8800D+03))
  RCONST(141) = (ARR2_DP(1.0000D-11,-2.8000D+02))
  RCONST(142) = (FALLOFF_T10_R142)
  RCONST(143) = (ARR2_DP(5.5000D-15,-1.8800D+03))
  RCONST(144) = (ARR2_DP(4.6000D-13,-1.1550D+03))
! RCONST(145) = constant rate coefficient
  RCONST(146) = (ARR2_DP(1.0500D-11,5.1900D+02))
  RCONST(147) = (ARR2_DP(4.7000D-15,-1.0130D+03))
! RCONST(148) = constant rate coefficient
  RCONST(149) = (ARR2_DP(2.7000D-11,3.9000D+02))
! RCONST(150) = constant rate coefficient
  RCONST(151) = (ARR2_DP(2.3900D-12,3.6500D+02))
  RCONST(152) = (ARR2_DP(7.4300D-13,7.0000D+02))
  RCONST(153) = (1.00E+0*RCONST(58))
  RCONST(154) = (1.0*RCONST(70))
  RCONST(155) = (ARR2_DP(3.3000D+09,-8.3000D+03))
  RCONST(156) = (ARR2_DP(1.0300D-14,-1.9950D+03))
  RCONST(157) = (ARR2_DP(3.0300D-12,-4.4800D+02))
  RCONST(158) = (ARR2_DP(5.5800D-12,5.1100D+02))
  RCONST(159) = (ARR2_DP(3.8800D-15,-1.7700D+03))
  RCONST(160) = (ARR2_DP(4.1000D-12,-1.8600D+03))
  RCONST(161) = (1.0*RJCELL(IJ_ISPD))
  RCONST(162) = (ARR2_DP(2.2300D-11,3.7200D+02))
  RCONST(163) = (1.0*RJCELL(IJ_HPALD))
  RCONST(164) = (ARR2_DP(6.0000D-12,-1.8600D+03))
  RCONST(165) = (ARR2_DP(5.7800D-11,-4.0000D+02))
  RCONST(166) = (ARR2_DP(7.4300D-13,7.0000D+02))
  RCONST(167) = (ARR2_DP(2.3900D-12,3.6500D+02))
  RCONST(168) = (1.0*RCONST(58))
  RCONST(169) = (1.0*RCONST(70))
! RCONST(170) = constant rate coefficient
! RCONST(171) = constant rate coefficient
  RCONST(172) = (ARR2_DP(1.5000D-11,4.4900D+02))
  RCONST(173) = (ARR2_DP(1.2000D-15,-8.2100D+02))
  RCONST(174) = (ARR2_DP(3.7000D-12,1.7500D+02))
! RCONST(175) = constant rate coefficient
  RCONST(176) = (ARR2_DP(1.5000D-11,4.4900D+02))
  RCONST(177) = (ARR2_DP(1.2000D-15,-8.2100D+02))
  RCONST(178) = (ARR2_DP(3.7000D-12,1.7500D+02))
  RCONST(179) = (ARR2_DP(2.3000D-12,-1.9000D+02))
  RCONST(180) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(181) = (1.0*RCONST(58))
  RCONST(182) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(183) = (1.0*RCONST(70))
  RCONST(184) = (ARR2_DP(1.8000D-12,3.4000D+02))
  RCONST(185) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(186) = (1.0*RCONST(58))
  RCONST(187) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(188) = (1.0*RCONST(70))
! RCONST(189) = constant rate coefficient
! RCONST(190) = constant rate coefficient
  RCONST(191) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(192) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(193) = (1.0*RCONST(58))
  RCONST(194) = (1.0*RCONST(70))
  RCONST(195) = (ARR2_DP(1.7000D-12,9.5000D+02))
! RCONST(196) = constant rate coefficient
! RCONST(197) = constant rate coefficient
! RCONST(198) = constant rate coefficient
! RCONST(199) = constant rate coefficient
! RCONST(200) = constant rate coefficient
  RCONST(201) = (1.0*RJCELL(IJ_NTR_IUPAC10))
  RCONST(202) = (0.05*RJCELL(IJ_NO2_IUPAC10))
! RCONST(203) = constant rate coefficient
  RCONST(204) = (ARR2_DP(1.0800D-16,-5.0000D+02))
! RCONST(205) = constant rate coefficient
  RCONST(206) = (0.028*RJCELL(IJ_NO2_IUPAC10))
! RCONST(207) = constant rate coefficient
  RCONST(208) = (ARR2_DP(5.4000D-17,-5.0000D+02))
! RCONST(209) = constant rate coefficient
! RCONST(210) = constant rate coefficient
! RCONST(211) = constant rate coefficient
  RCONST(212) = (1.00E+0*RCONST(61))
  RCONST(213) = (1.00E+0*RCONST(62))
  RCONST(214) = (1.00E+0*RCONST(63))
  RCONST(215) = (1.00E+0*RCONST(57))
  RCONST(216) = (1.00E+0*RCONST(59))
  RCONST(217) = (1.00E+0*RCONST(58))
! RCONST(218) = constant rate coefficient
! RCONST(219) = constant rate coefficient
  RCONST(220) = (ARR2_DP(1.8500D-12,-1.6900D+03))
  RCONST(221) = (FALLOFF_T10_R217)
! RCONST(222) = constant rate coefficient
  RCONST(223) = (FALLOFF_T10_R219)
! RCONST(224) = constant rate coefficient
! RCONST(225) = constant rate coefficient
  RCONST(226) = (1.0*RJCELL(IJ_CL2_IUPAC04))
  RCONST(227) = (1.0*RJCELL(IJ_HOCL_IUPAC04))
  RCONST(228) = (ARR2_DP(2.3000D-11,-2.0000D+02))
! RCONST(229) = constant rate coefficient
  RCONST(230) = (ARR2_DP(6.4000D-12,2.9000D+02))
  RCONST(231) = (ARR2_DP(2.2000D-12,3.4000D+02))
  RCONST(232) = (ARR2_DP(3.2000D-12,-1.1000D+02))
! RCONST(233) = constant rate coefficient
  RCONST(234) = (1.0*RJCELL(IJ_FMCL_IUPAC04))
  RCONST(235) = (ARR2_DP(6.6000D-12,-1.2400D+03))
! RCONST(236) = constant rate coefficient
! RCONST(237) = constant rate coefficient
  RCONST(238) = (ARR2_DP(8.3000D-11,-1.0000D+02))
! RCONST(239) = constant rate coefficient
! RCONST(240) = constant rate coefficient
! RCONST(241) = constant rate coefficient
! RCONST(242) = constant rate coefficient
  RCONST(243) = (ARR2_DP(8.2000D-11,-3.4000D+01))
! RCONST(244) = constant rate coefficient
! RCONST(245) = constant rate coefficient
! RCONST(246) = constant rate coefficient
  RCONST(247) = (ARR2_DP(8.2000D-11,4.5000D+01))
  RCONST(248) = (ARRHENUIS_T04(6.5800D-13,5.8000D+01,1.1600D+00))
! RCONST(249) = constant rate coefficient
! RCONST(250) = constant rate coefficient
! RCONST(251) = constant rate coefficient
  RCONST(252) = (1.0*RJCELL(IJ_CLNO2_IUPAC13))
  RCONST(253) = (FALLOFF_T10_CL28)
  RCONST(254) = (1.0*RJCELL(IJ_CLONO2_1))
  RCONST(255) = (1.0*RJCELL(IJ_CLONO2_2))
  RCONST(256) = (1.0*KHETCELL(IK_HETERO_CLNO3_WAI))
  RCONST(257) = (1.0*KHETCELL(IK_HETERO_CLNO3_WAJ))
  RCONST(258) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(259) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(260) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(261) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(262) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(263) = (ARR2_DP(1.9000D-13,1.3000D+03))
! RCONST(264) = constant rate coefficient
! RCONST(265) = constant rate coefficient
! RCONST(266) = constant rate coefficient
  RCONST(267) = (ARR2_DP(2.7000D-12,3.6000D+02))
  RCONST(268) = (ARR2_DP(1.9000D-13,1.3000D+03))
  RCONST(269) = (ARR2_DP(2.7000D-12,3.7400D+02))
  RCONST(270) = (1.4*KHETCELL(IK_HETERO_NTR2))
  RCONST(271) = (1.0*KHETCELL(IK_HETERO_N2O5IJ))
  RCONST(272) = (1.0*KHETCELL(IK_HETERO_N2O5K))
  RCONST(273) = (1.0*KHETCELL(IK_HETERO_H2NO3PAIJ))
  RCONST(274) = (1.0*KHETCELL(IK_HETERO_H2NO3PAK))
  RCONST(275) = (1.0*KHETCELL(IK_HETERO_H2NO3PBIJ)/CAIR)
  RCONST(276) = (1.0*KHETCELL(IK_HETERO_H2NO3PBIJ)/CAIR)
  RCONST(277) = (1.0*KHETCELL(IK_HETERO_H2NO3PBK)/CAIR)
  RCONST(278) = (1.0*KHETCELL(IK_HETERO_NO2))
  RCONST(279) = (HALOGEN_FALLOFF(6.7006D-11,1.0743D+01,3.4153D-08,-6.7130D-01,2.0000D-06))
  RCONST(280) = (1.0*KHETCELL(IK_HETERO_IEPOX))
  RCONST(281) = (1.0*KHETCELL(IK_HETERO_IEPOXOS)/CAIR)
  RCONST(282) = (1.0*KHETCELL(IK_HETERO_TETROL))
  RCONST(283) = (1.0*KHETCELL(IK_HETERO_GLY))
  RCONST(284) = (1.0*KHETCELL(IK_HETERO_MGLY))
  RCONST(285) = (ARR2_DP(2.6000D-12,3.8000D+02))
  RCONST(286) = (ARR2_DP(2.6500D-13,1.3000D+03))
! RCONST(287) = constant rate coefficient
! RCONST(288) = constant rate coefficient
! RCONST(289) = constant rate coefficient
! RCONST(290) = constant rate coefficient
  RCONST(291) = (1.0*RJCELL(IJ_IC3ONO2))
! RCONST(292) = constant rate coefficient
! RCONST(293) = constant rate coefficient
! RCONST(294) = constant rate coefficient
! RCONST(295) = constant rate coefficient
! RCONST(296) = constant rate coefficient
! RCONST(297) = constant rate coefficient
! RCONST(298) = constant rate coefficient
! RCONST(299) = constant rate coefficient
  RCONST(300) = (1.0*KHETCELL(IK_HETERO_PNCOMLI)/CAIR)
! RCONST(301) = constant rate coefficient
  RCONST(302) = (1.0*KHETCELL(IK_HETERO_PNCOMLJ)/CAIR)
! RCONST(303) = constant rate coefficient
! RCONST(304) = constant rate coefficient
! RCONST(305) = constant rate coefficient
! RCONST(306) = constant rate coefficient
! RCONST(307) = constant rate coefficient
! RCONST(308) = constant rate coefficient
! RCONST(309) = constant rate coefficient
! RCONST(310) = constant rate coefficient
! RCONST(311) = constant rate coefficient
! RCONST(312) = constant rate coefficient
! RCONST(313) = constant rate coefficient
  RCONST(314) = (ARR2_DP(5.4000D-12,1.3500D+02))
! RCONST(315) = constant rate coefficient
  RCONST(316) = (ARR2_DP(3.4000D-11,-1.6000D+03))
  RCONST(317) = (1.0*RJCELL(IJ_FORM_R_IUPAC13))
  RCONST(318) = (1.0*RJCELL(IJ_FORM_M_IUPAC13))
  RCONST(319) = (ARR2_DP(8.2000D-11,-3.4000D+01))
  RCONST(320) = (ARR2_DP(4.7000D-12,3.4500D+02))
  RCONST(321) = (ARR2_DP(1.4000D-12,-1.8600D+03))
  RCONST(322) = (ARR2_DP(1.8000D-11,-1.1000D+03))
  RCONST(323) = (1.0*RJCELL(IJ_ALD2_R_IUPAC13))
! RCONST(324) = constant rate coefficient
  RCONST(325) = (ARR2_DP(1.4800D-11,4.4800D+02))
  RCONST(326) = (ARR2_DP(1.3400D-14,-2.2830D+03))
! RCONST(327) = constant rate coefficient
! RCONST(328) = constant rate coefficient
! RCONST(329) = constant rate coefficient
! RCONST(330) = constant rate coefficient
! RCONST(331) = constant rate coefficient
  RCONST(332) = (1.0*RJCELL(IJ_ACRO_09))
! RCONST(333) = constant rate coefficient
! RCONST(334) = constant rate coefficient
! RCONST(335) = constant rate coefficient
! RCONST(336) = constant rate coefficient
  RCONST(337) = (1.0*RJCELL(IJ_ACRO_09))
! RCONST(338) = constant rate coefficient
  RCONST(339) = (ARR2_DP(1.8000D-12,3.4000D+02))
! RCONST(340) = constant rate coefficient
  RCONST(341) = (ARR2_DP(2.1100D-18,-1.2565D+03))
! RCONST(342) = constant rate coefficient
! RCONST(343) = constant rate coefficient
! RCONST(344) = constant rate coefficient
  RCONST(345) = (ARR2_DP(2.2500D-33,6.8000D+02))
  RCONST(346) = (ARR2_DP(1.1200D-11,-2.5000D+02))
  RCONST(347) = (FALLOFF_T10_DMS2)
  RCONST(348) = (ARR2_DP(1.9000D-13,5.2000D+02))
  RCONST(349) = (ARR2_DP(3.4000D-13,2.0810D+03))
  RCONST(350) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,64.0D0,1.28D-5,H_SO2,0.11D0,0))
  RCONST(351) = (XCL_RS*KMT(TEMP,LWC_RS,64.0D0,1.28D-5,H_SO2,0.11D0,1))
  RCONST(352) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,63.0D0,1.32D-5,H_HNO3,0.09D0,0))
  RCONST(353) = (XCL_RS*KMT(TEMP,LWC_RS,63.0D0,1.32D-5,H_HNO3,0.09D0,1))
  RCONST(354) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,44.0D0,1.55D-5,H_CO2,0.00015D0,0))
  RCONST(355) = (XCL_RS*KMT(TEMP,LWC_RS,44.0D0,1.55D-5,H_CO2,0.00015D0,1))
  RCONST(356) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,17.0D0,2.30D-5,H_NH3,0.091D0,0))
  RCONST(357) = (XCL_RS*KMT(TEMP,LWC_RS,17.0D0,2.30D-5,H_NH3,0.091D0,1))
  RCONST(358) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,34.0D0,1.46D-5,H_H2O2,0.15D0,0))
  RCONST(359) = (XCL_RS*KMT(TEMP,LWC_RS,34.0D0,1.46D-5,H_H2O2,0.15D0,1))
  RCONST(360) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,48.0D0,1.48D-5,H_O3,0.1D0,0))
  RCONST(361) = (XCL_RS*KMT(TEMP,LWC_RS,48.0D0,1.48D-5,H_O3,0.1D0,1))
  RCONST(362) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,46.0D0,1.53D-5,H_FACD,0.0229D0,0))
  RCONST(363) = (XCL_RS*KMT(TEMP,LWC_RS,46.0D0,1.53D-5,H_FACD,0.0229D0,1))
  RCONST(364) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,36.5D0,1.89D-5,H_HCL,0.116D0,0))
  RCONST(365) = (XCL_RS*KMT(TEMP,LWC_RS,36.5D0,1.89D-5,H_HCL,0.116D0,1))
  RCONST(366) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,58.0D0,1.15D-5,H_GLY,0.023D0,0))
  RCONST(367) = (XCL_RS*KMT(TEMP,LWC_RS,58.0D0,1.15D-5,H_GLY,0.023D0,1))
  RCONST(368) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,72.0D0,1.15D-5,H_MGLY,0.023D0,0))
  RCONST(369) = (XCL_RS*KMT(TEMP,LWC_RS,72.0D0,1.15D-5,H_MGLY,0.023D0,1))
  RCONST(370) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,17.0D0,1.48D-5,H_OH,0.1D0,0))
  RCONST(371) = (XCL_RS*KMT(TEMP,LWC_RS,17.0D0,1.48D-5,H_OH,0.1D0,1))
  RCONST(372) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,97.0D0,1.48D-5,0.0D0,0.1D0,0))
  RCONST(373) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,108.0D0,1.48D-5,0.0D0,0.1D0,0))
  RCONST(374) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,33.0D0,1.04D-5,H_HO2,0.01D0,0))
  RCONST(375) = (XCL_RS*KMT(TEMP,LWC_RS,33.0D0,1.04D-5,H_HO2,0.01D0,1))
  RCONST(376) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,46.0D0,1.92D-5,H_NO2,0.0015D0,0))
  RCONST(377) = (XCL_RS*KMT(TEMP,LWC_RS,46.0D0,1.92D-5,H_NO2,0.0015D0,1))
  RCONST(378) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,47.0D0,1.30D-5,H_HONO,0.5D0,0))
  RCONST(379) = (XCL_RS*KMT(TEMP,LWC_RS,47.0D0,1.30D-5,H_HONO,0.5D0,1))
  RCONST(380) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,79.0D0,1.30D-5,H_HNO4,0.1D0,0))
  RCONST(381) = (XCL_RS*KMT(TEMP,LWC_RS,79.0D0,1.30D-5,H_HNO4,0.1D0,1))
  RCONST(382) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,60.052D0,1.15D-5,H_GLYD,0.023D0,0))
  RCONST(383) = (XCL_RS*KMT(TEMP,LWC_RS,60.052D0,1.15D-5,H_GLYD,0.023D0,1))
  RCONST(384) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,60.052D0,1.24D-5,H_AACD,0.0322D0,0))
  RCONST(385) = (XCL_RS*KMT(TEMP,LWC_RS,60.052D0,1.24D-5,H_AACD,0.0322D0,1))
  RCONST(386) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,30.0D0,1.64D-5,H_FORM,0.02D0,0))
  RCONST(387) = (XCL_RS*KMT(TEMP,LWC_RS,30.0D0,1.64D-5,H_FORM,0.02D0,1))
  RCONST(388) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,62.0D0,1.00D-5,H_NO3,0.05D0,0))
  RCONST(389) = (XCL_RS*KMT(TEMP,LWC_RS,62.0D0,1.00D-5,H_NO3,0.05D0,1))
  RCONST(390) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,49.0D0,1.35D-5,H_CH3O2,0.05D0,0))
  RCONST(391) = (XCL_RS*KMT(TEMP,LWC_RS,49.0D0,1.35D-5,H_CH3O2,0.05D0,1))
  RCONST(392) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,48.04D0,1.31D-5,H_MHP,0.006758D0,0))
  RCONST(393) = (XCL_RS*KMT(TEMP,LWC_RS,48.04D0,1.31D-5,H_MHP,0.006758D0,1))
  RCONST(394) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,76.05D0,1.02D-5,H_PAA,0.019D0,0))
  RCONST(395) = (XCL_RS*KMT(TEMP,LWC_RS,76.05D0,1.02D-5,H_PAA,0.019D0,1))
  RCONST(396) = (XCL_RS*CFRAC_RS*KMT(TEMP,LWC_RS,118.13D0,1.00D-5,H_IEPOX,0.02D0,0))
  RCONST(397) = (XCL_RS*KMT(TEMP,LWC_RS,118.13D0,1.00D-5,H_IEPOX,0.02D0,1))
  RCONST(398) = (XCL_RS*1.8D-1*EXP(4.03D+3*TFAC)*PHI2_RS)
  RCONST(399) = (XCL_RS*5.1D-3)
  RCONST(400) = (XCL_RS*1.4D10*1.8D-16*EXP(-6.95D3*TFAC))
  RCONST(401) = (XCL_RS*1.4D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(402) = (XCL_RS*2.0D8*1.39D-2*EXP(1.87D3*TFAC))
  RCONST(403) = (XCL_RS*2.0D8*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(404) = (XCL_RS*5.D10*6.72D-8*EXP(3.55D2*TFAC)*GM1_RS)
  RCONST(405) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM2_RS)
  RCONST(406) = (XCL_RS*5.D10*1.70D1)
  RCONST(407) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(408) = (XCL_RS*3.4D10*5.87647D-7*EXP(-2.391D2*TFAC))
  RCONST(409) = (XCL_RS*3.4D10*1.D3*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(410) = (XCL_RS*6.4D4*4.3D-7*EXP(-9.95D2*TFAC))
  RCONST(411) = (XCL_RS*6.4D4*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(412) = (XCL_RS*5.D10*4.68D-11*EXP(-1.79D3*TFAC)*GM1_RS)
  RCONST(413) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM2_RS)
  RCONST(414) = (XCL_RS*5.D10*1.74D6*EXP(6.90D3*TFAC))
  RCONST(415) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(416) = (XCL_RS*5.D10*1.0D3)
  RCONST(417) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(418) = (XCL_RS*1.D11*1.02D-2*EXP(2.45D3*TFAC)*GM1_RS)
  RCONST(419) = (XCL_RS*1.D11*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(420) = (XCL_RS*5.0D10*(1.8D-4*EXP(-2.00D1*TFAC)))
  RCONST(421) = (XCL_RS*5.0D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(422) = (XCL_RS*5.D10*1.6D-5)
  RCONST(423) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(424) = (XCL_RS*5.D10*1.0D-5)
  RCONST(425) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(426) = (XCL_RS*5.D10*(5.3D-4*EXP(-1.76D3*TFAC)))
  RCONST(427) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(428) = (XCL_RS*2.D10*3.47D-4*EXP(-2.67D2*TFAC))
  RCONST(429) = (XCL_RS*2.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(430) = (XCL_RS*5.D10*5.6D-2)
  RCONST(431) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(432) = (XCL_RS*5.D10*5.4D-5*GM1_RS)
  RCONST(433) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM2_RS)
  RCONST(434) = (XCL_RS*2.D10*3.2D-3)
  RCONST(435) = (XCL_RS*2.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(436) = (XCL_RS*2.D10*1.48D-4*EXP(-8.05D1*TFAC))
  RCONST(437) = (XCL_RS*2.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(438) = (XCL_RS*5.D10*1.75D-5)
  RCONST(439) = (XCL_RS*5.D10*PHI2_RS*GM1_RS*GM1_RS)
  RCONST(440) = (XCL_RS*KRXN(7.45D+7,-4756.08D0,1,0,0,'RS'))
  RCONST(441) = (XCL_RS*KRXN(2.4D+4,0.0D0,0,1,0,'RS'))
  RCONST(442) = (XCL_RS*KRXN(3.7D+5,-5530.88D0,0,2,0,'RS'))
  RCONST(443) = (XCL_RS*KRXN(1.5D+9,-5280.56D0,0,3,0,'RS'))
  RCONST(444) = (XCL_RS*8.3D5*EXP(-2.7D3*TFAC)*PHI2_RS)
  RCONST(445) = (XCL_RS*9.6D7*EXP(-9.1D2*TFAC)*PHI2_RS)
  RCONST(446) = (XCL_RS*1.5D9*EXP(-1.5D3*TFAC)*PHI2_RS)
  RCONST(447) = (XCL_RS*2.0D6*PHI2_RS)
  RCONST(448) = (XCL_RS*2.0D6*PHI2_RS)
  RCONST(449) = (XCL_RS*2.0D6*PHI2_RS)
  RCONST(450) = (XCL_RS*3.3D5*PHI2_RS)
  RCONST(451) = (XCL_RS*1.1D0*PHI2_RS)
  RCONST(452) = (XCL_RS*5.0D5*EXP(-7.0D3*TFAC)*PHI2_RS)
  RCONST(453) = (XCL_RS*1.0D10*PHI2_RS)
  RCONST(454) = (XCL_RS*1.0D10*PHI2_RS)
  RCONST(455) = (XCL_RS*3.6D9*EXP(-9.3D2*TFAC)*PHI2_RS)
  RCONST(456) = (XCL_RS*2.8D10*PHI2_RS)
  RCONST(457) = (XCL_RS*3.5D10*EXP(-7.2D2*TFAC)*PHI2_RS)
  RCONST(458) = (XCL_RS*3.2D7*EXP(-1.7D3*TFAC)*PHI2_RS)
  RCONST(459) = (XCL_RS*2.7D9*PHI2_RS)
  RCONST(460) = (XCL_RS*1.8D9*PHI2_RS)
  RCONST(461) = (XCL_RS*4.5D9*PHI2_RS)
  RCONST(462) = (XCL_RS*2.6D-2)
  RCONST(463) = (XCL_RS*1.0D5*PHI2_RS)
  RCONST(464) = (XCL_RS*1.3D9*EXP(-2.2D3*TFAC)*PHI2_RS)
  RCONST(465) = (XCL_RS*1.1D9*PHI2_RS)
  RCONST(466) = (XCL_RS*1.7D9*PHI2_RS)
  RCONST(467) = (XCL_RS*2.2D8*EXP(-2.6D3*TFAC)*PHI2_RS)
  RCONST(468) = (XCL_RS*7.1D6*PHI2_RS*PHI2_RS)
  RCONST(469) = (XCL_RS*4.6D2*EXP(-1.1D3*TFAC)*PHI2_RS)
  RCONST(470) = (XCL_RS*4.6D2*EXP(-1.1D3*TFAC)*PHI2_RS)
  RCONST(471) = (XCL_RS*5.0D5*PHI2_RS)
  RCONST(472) = (XCL_RS*7.9D2*EXP(-2.9D3*TFAC)*PHI2_RS)
  RCONST(473) = (XCL_RS*2.5D7*EXP(-2.45D3*TFAC)*PHI2_RS)
  RCONST(474) = (XCL_RS*7.7D-3*EXP(-9.2E3*TFAC))
  RCONST(475) = (XCL_RS*3.7D3*PHI2_RS)
  RCONST(476) = (XCL_RS*3.0D8*PHI2_RS)
  RCONST(477) = (XCL_RS*1.9D7*EXP(-3.8E3*TFAC)*PHI2_RS*PHI2_RS)
  RCONST(478) = (XCL_RS*3.6D7*EXP(-4.0E3*TFAC)*PHI2_RS*PHI2_RS)
  RCONST(479) = (XCL_RS*7.0D2*PHI2_RS)
  RCONST(480) = (XCL_RS*3.4D9*EXP(-1.2D3*TFAC)*PHI2_RS)
  RCONST(481) = (XCL_RS*5.0D8*PHI2_RS)
  RCONST(482) = (XCL_RS*1.0D9*PHI2_RS)
  RCONST(483) = (XCL_RS*6.0D8*PHI2_RS)
  RCONST(484) = (XCL_RS*8.6D8*PHI2_RS)
  RCONST(485) = (XCL_RS*1.1D9*EXP(-1.516D3*TFAC)*PHI2_RS)
  RCONST(486) = (XCL_RS*1.5D8*PHI2_RS)
  RCONST(487) = (XCL_RS*1.2D9*PHI2_RS)
  RCONST(488) = (XCL_RS*1.4D6*PHI2_RS)
  RCONST(489) = (XCL_RS*4.7D7*PHI2_RS)
  RCONST(490) = (XCL_RS*7.7D6*PHI2_RS)
  RCONST(491) = (XCL_RS*7.0D8*PHI2_RS)
  RCONST(492) = (XCL_RS*6.0D7*PHI2_RS)
  RCONST(493) = (XCL_RS*6.0D7*PHI2_RS)
  RCONST(494) = (XCL_RS*1.6D7*PHI2_RS)
  RCONST(495) = (XCL_RS*8.5D7*PHI2_RS)
  RCONST(496) = (XCL_RS*1.1D9*EXP(-1.02D3*TFAC)*PHI2_RS)
  RCONST(497) = (XCL_RS*1.2D8*EXP(-9.9D2*TFAC)*PHI2_RS)
  RCONST(498) = (XCL_RS*1.0*RJCELL(IJ_H2O2_IUPAC10))
  RCONST(499) = (XCL_RS*KIEPOX(9.0D-4,1.31D-5,0,'RS'))
  RCONST(500) = (XCL_RS*KIEPOX(8.83D-3,2.92D-6,0,'RS'))
  RCONST(501) = (XCL_RS*KIEPOX(2.0D-4,2.92D-6,0,'RS'))
  RCONST(502) = (XCL_RS*CFRAC_RS*KPP_ALFA3_RS)
  RCONST(503) = (XCL_RS*CFRAC_RS*KPP_ALFA3_RS)
  RCONST(504) = (XCL_RS*CFRAC_RS*KPP_ALFA3_RS)
  RCONST(505) = (XCL_RS*CFRAC_RS*KPP_ALFA3_RS)
  RCONST(506) = (XCL_RS*WFAC_RS)
  RCONST(507) = (XCL_RS*WFAC_RS)
  RCONST(508) = (XCL_RS*WFAC_RS)
  RCONST(509) = (XCL_RS*WFAC_RS)
  RCONST(510) = (XCL_RS*WFAC_RS)
  RCONST(511) = (XCL_RS*WFAC_RS)
  RCONST(512) = (XCL_RS*WFAC_RS)
  RCONST(513) = (XCL_RS*WFAC_RS)
  RCONST(514) = (XCL_RS*WFAC_RS)
  RCONST(515) = (XCL_RS*WFAC_RS)
  RCONST(516) = (XCL_RS*WFAC_RS)
  RCONST(517) = (XCL_RS*WFAC_RS)
  RCONST(518) = (XCL_RS*WFAC_RS)
  RCONST(519) = (XCL_RS*WFAC_RS)
  RCONST(520) = (XCL_RS*WFAC_RS)
  RCONST(521) = (XCL_RS*WFAC_RS)
  RCONST(522) = (XCL_RS*WFAC_RS)
  RCONST(523) = (XCL_RS*WFAC_RS)
  RCONST(524) = (XCL_RS*WFAC_RS)
  RCONST(525) = (XCL_RS*WFAC_RS)
  RCONST(526) = (XCL_RS*WFAC_RS)
  RCONST(527) = (XCL_RS*WFAC_RS)
  RCONST(528) = (XCL_RS*WFAC_RS)
  RCONST(529) = (XCL_RS*WFAC_RS)
  RCONST(530) = (XCL_RS*WFAC_RS)
  RCONST(531) = (XCL_RS*WFAC_RS)
  RCONST(532) = (XCL_RS*WFAC_RS)
  RCONST(533) = (XCL_RS*WFAC_RS)
  RCONST(534) = (XCL_RS*WFAC_RS)
  RCONST(535) = (XCL_RS*WFAC_RS)
  RCONST(536) = (XCL_RS*WFAC_RS)
  RCONST(537) = (XCL_RS*WFAC_RS)
  RCONST(538) = (XCL_RS*WFAC_RS)
  RCONST(539) = (XCL_RS*WFAC_RS)
  RCONST(540) = (XCL_RS*WFAC_RS)
  RCONST(541) = (XCL_RS*WFAC_RS)
  RCONST(542) = (XCL_RS*WFAC_RS)
  RCONST(543) = (XCL_RS*WFAC_RS)
  RCONST(544) = (XCL_RS*WFAC_RS)
  RCONST(545) = (XCL_RS*WFAC_RS)
  RCONST(546) = (XCL_RS*WFAC_RS)
  RCONST(547) = (XCL_RS*WFAC_RS)
  RCONST(548) = (XCL_RS*WFAC_RS)
  RCONST(549) = (XCL_RS*WFAC_RS)
  RCONST(550) = (XCL_RS*WFAC_RS)
  RCONST(551) = (XCL_RS*WFAC_RS)
  RCONST(552) = (XCL_RS*WFAC_RS)
  RCONST(553) = (XCL_RS*WFAC_RS)
  RCONST(554) = (XCL_RS*WFAC_RS)
  RCONST(555) = (XCL_RS*WFAC_RS)
  RCONST(556) = (XCL_RS*WFAC_RS)
  RCONST(557) = (XCL_RS*WFAC_RS)
  RCONST(558) = (XCL_RS*WFAC_RS)
  RCONST(559) = (XCL_RS*WFAC_RS)
  RCONST(560) = (XCL_RS*WFAC_RS)
  RCONST(561) = (XCL_RS*WFAC_RS)
  RCONST(562) = (XCL_RS*WFAC_RS)
  RCONST(563) = (XCL_RS*WFAC_RS)
  RCONST(564) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,64.0D0,1.28D-5,H_SO2,0.11D0,0))
  RCONST(565) = (XCL_CV*KMT(TEMP,LWC_CV,64.0D0,1.28D-5,H_SO2,0.11D0,1))
  RCONST(566) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,63.0D0,1.32D-5,H_HNO3,0.09D0,0))
  RCONST(567) = (XCL_CV*KMT(TEMP,LWC_CV,63.0D0,1.32D-5,H_HNO3,0.09D0,1))
  RCONST(568) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,44.0D0,1.55D-5,H_CO2,0.00015D0,0))
  RCONST(569) = (XCL_CV*KMT(TEMP,LWC_CV,44.0D0,1.55D-5,H_CO2,0.00015D0,1))
  RCONST(570) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,17.0D0,2.30D-5,H_NH3,0.091D0,0))
  RCONST(571) = (XCL_CV*KMT(TEMP,LWC_CV,17.0D0,2.30D-5,H_NH3,0.091D0,1))
  RCONST(572) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,34.0D0,1.46D-5,H_H2O2,0.15D0,0))
  RCONST(573) = (XCL_CV*KMT(TEMP,LWC_CV,34.0D0,1.46D-5,H_H2O2,0.15D0,1))
  RCONST(574) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,48.0D0,1.48D-5,H_O3,0.1D0,0))
  RCONST(575) = (XCL_CV*KMT(TEMP,LWC_CV,48.0D0,1.48D-5,H_O3,0.1D0,1))
  RCONST(576) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,46.0D0,1.53D-5,H_FACD,0.0229D0,0))
  RCONST(577) = (XCL_CV*KMT(TEMP,LWC_CV,46.0D0,1.53D-5,H_FACD,0.0229D0,1))
  RCONST(578) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,36.5D0,1.89D-5,H_HCL,0.116D0,0))
  RCONST(579) = (XCL_CV*KMT(TEMP,LWC_CV,36.5D0,1.89D-5,H_HCL,0.116D0,1))
  RCONST(580) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,58.0D0,1.15D-5,H_GLY,0.023D0,0))
  RCONST(581) = (XCL_CV*KMT(TEMP,LWC_CV,58.0D0,1.15D-5,H_GLY,0.023D0,1))
  RCONST(582) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,72.0D0,1.15D-5,H_MGLY,0.023D0,0))
  RCONST(583) = (XCL_CV*KMT(TEMP,LWC_CV,72.0D0,1.15D-5,H_MGLY,0.023D0,1))
  RCONST(584) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,17.0D0,1.48D-5,H_OH,0.1D0,0))
  RCONST(585) = (XCL_CV*KMT(TEMP,LWC_CV,17.0D0,1.48D-5,H_OH,0.1D0,1))
  RCONST(586) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,97.0D0,1.48D-5,0.0D0,0.1D0,0))
  RCONST(587) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,108.0D0,1.48D-5,0.0D0,0.1D0,0))
  RCONST(588) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,33.0D0,1.04D-5,H_HO2,0.01D0,0))
  RCONST(589) = (XCL_CV*KMT(TEMP,LWC_CV,33.0D0,1.04D-5,H_HO2,0.01D0,1))
  RCONST(590) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,46.0D0,1.92D-5,H_NO2,0.0015D0,0))
  RCONST(591) = (XCL_CV*KMT(TEMP,LWC_CV,46.0D0,1.92D-5,H_NO2,0.0015D0,1))
  RCONST(592) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,47.0D0,1.30D-5,H_HONO,0.5D0,0))
  RCONST(593) = (XCL_CV*KMT(TEMP,LWC_CV,47.0D0,1.30D-5,H_HONO,0.5D0,1))
  RCONST(594) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,79.0D0,1.30D-5,H_HNO4,0.1D0,0))
  RCONST(595) = (XCL_CV*KMT(TEMP,LWC_CV,79.0D0,1.30D-5,H_HNO4,0.1D0,1))
  RCONST(596) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,60.052D0,1.15D-5,H_GLYD,0.023D0,0))
  RCONST(597) = (XCL_CV*KMT(TEMP,LWC_CV,60.052D0,1.15D-5,H_GLYD,0.023D0,1))
  RCONST(598) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,60.052D0,1.24D-5,H_AACD,0.0322D0,0))
  RCONST(599) = (XCL_CV*KMT(TEMP,LWC_CV,60.052D0,1.24D-5,H_AACD,0.0322D0,1))
  RCONST(600) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,30.0D0,1.64D-5,H_FORM,0.02D0,0))
  RCONST(601) = (XCL_CV*KMT(TEMP,LWC_CV,30.0D0,1.64D-5,H_FORM,0.02D0,1))
  RCONST(602) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,62.0D0,1.00D-5,H_NO3,0.05D0,0))
  RCONST(603) = (XCL_CV*KMT(TEMP,LWC_CV,62.0D0,1.00D-5,H_NO3,0.05D0,1))
  RCONST(604) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,49.0D0,1.35D-5,H_CH3O2,0.05D0,0))
  RCONST(605) = (XCL_CV*KMT(TEMP,LWC_CV,49.0D0,1.35D-5,H_CH3O2,0.05D0,1))
  RCONST(606) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,48.04D0,1.31D-5,H_MHP,0.006758D0,0))
  RCONST(607) = (XCL_CV*KMT(TEMP,LWC_CV,48.04D0,1.31D-5,H_MHP,0.006758D0,1))
  RCONST(608) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,76.05D0,1.02D-5,H_PAA,0.019D0,0))
  RCONST(609) = (XCL_CV*KMT(TEMP,LWC_CV,76.05D0,1.02D-5,H_PAA,0.019D0,1))
  RCONST(610) = (XCL_CV*CFRAC_CV*KMT(TEMP,LWC_CV,118.13D0,1.00D-5,H_IEPOX,0.02D0,0))
  RCONST(611) = (XCL_CV*KMT(TEMP,LWC_CV,118.13D0,1.00D-5,H_IEPOX,0.02D0,1))
  RCONST(612) = (XCL_CV*1.8D-1*EXP(4.03D+3*TFAC)*PHI2_CV)
  RCONST(613) = (XCL_CV*5.1D-3)
  RCONST(614) = (XCL_CV*1.4D10*1.8D-16*EXP(-6.95D3*TFAC))
  RCONST(615) = (XCL_CV*1.4D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(616) = (XCL_CV*2.0D8*1.39D-2*EXP(1.87D3*TFAC))
  RCONST(617) = (XCL_CV*2.0D8*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(618) = (XCL_CV*5.D10*6.72D-8*EXP(3.55D2*TFAC)*GM1_CV)
  RCONST(619) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM2_CV)
  RCONST(620) = (XCL_CV*5.D10*1.70D1)
  RCONST(621) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(622) = (XCL_CV*3.4D10*5.87647D-7*EXP(-2.391D2*TFAC))
  RCONST(623) = (XCL_CV*3.4D10*1.D3*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(624) = (XCL_CV*6.4D4*4.3D-7*EXP(-9.95D2*TFAC))
  RCONST(625) = (XCL_CV*6.4D4*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(626) = (XCL_CV*5.D10*4.68D-11*EXP(-1.79D3*TFAC)*GM1_CV)
  RCONST(627) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM2_CV)
  RCONST(628) = (XCL_CV*5.D10*1.74D6*EXP(6.90D3*TFAC))
  RCONST(629) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(630) = (XCL_CV*5.D10*1.0D3)
  RCONST(631) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(632) = (XCL_CV*1.D11*1.02D-2*EXP(2.45D3*TFAC)*GM1_CV)
  RCONST(633) = (XCL_CV*1.D11*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(634) = (XCL_CV*5.0D10*(1.8D-4*EXP(-2.00D1*TFAC)))
  RCONST(635) = (XCL_CV*5.0D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(636) = (XCL_CV*5.D10*1.6D-5)
  RCONST(637) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(638) = (XCL_CV*5.D10*1.0D-5)
  RCONST(639) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(640) = (XCL_CV*5.D10*(5.3D-4*EXP(-1.76D3*TFAC)))
  RCONST(641) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(642) = (XCL_CV*2.D10*3.47D-4*EXP(-2.67D2*TFAC))
  RCONST(643) = (XCL_CV*2.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(644) = (XCL_CV*5.D10*5.6D-2)
  RCONST(645) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(646) = (XCL_CV*5.D10*5.4D-5*GM1_CV)
  RCONST(647) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM2_CV)
  RCONST(648) = (XCL_CV*2.D10*3.2D-3)
  RCONST(649) = (XCL_CV*2.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(650) = (XCL_CV*2.D10*1.48D-4*EXP(-8.05D1*TFAC))
  RCONST(651) = (XCL_CV*2.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(652) = (XCL_CV*5.D10*1.75D-5)
  RCONST(653) = (XCL_CV*5.D10*PHI2_CV*GM1_CV*GM1_CV)
  RCONST(654) = (XCL_CV*KRXN(7.45D+7,-4756.08D0,1,0,0,'CV'))
  RCONST(655) = (XCL_CV*KRXN(2.4D+4,0.0D0,0,1,0,'CV'))
  RCONST(656) = (XCL_CV*KRXN(3.7D+5,-5530.88D0,0,2,0,'CV'))
  RCONST(657) = (XCL_CV*KRXN(1.5D+9,-5280.56D0,0,3,0,'CV'))
  RCONST(658) = (XCL_CV*8.3D5*EXP(-2.7D3*TFAC)*PHI2_CV)
  RCONST(659) = (XCL_CV*9.6D7*EXP(-9.1D2*TFAC)*PHI2_CV)
  RCONST(660) = (XCL_CV*1.5D9*EXP(-1.5D3*TFAC)*PHI2_CV)
  RCONST(661) = (XCL_CV*2.0D6*PHI2_CV)
  RCONST(662) = (XCL_CV*2.0D6*PHI2_CV)
  RCONST(663) = (XCL_CV*2.0D6*PHI2_CV)
  RCONST(664) = (XCL_CV*3.3D5*PHI2_CV)
  RCONST(665) = (XCL_CV*1.1D0*PHI2_CV)
  RCONST(666) = (XCL_CV*5.0D5*EXP(-7.0D3*TFAC)*PHI2_CV)
  RCONST(667) = (XCL_CV*1.0D10*PHI2_CV)
  RCONST(668) = (XCL_CV*1.0D10*PHI2_CV)
  RCONST(669) = (XCL_CV*3.6D9*EXP(-9.3D2*TFAC)*PHI2_CV)
  RCONST(670) = (XCL_CV*2.8D10*PHI2_CV)
  RCONST(671) = (XCL_CV*3.5D10*EXP(-7.2D2*TFAC)*PHI2_CV)
  RCONST(672) = (XCL_CV*3.2D7*EXP(-1.7D3*TFAC)*PHI2_CV)
  RCONST(673) = (XCL_CV*2.7D9*PHI2_CV)
  RCONST(674) = (XCL_CV*1.8D9*PHI2_CV)
  RCONST(675) = (XCL_CV*4.5D9*PHI2_CV)
  RCONST(676) = (XCL_CV*2.6D-2)
  RCONST(677) = (XCL_CV*1.0D5*PHI2_CV)
  RCONST(678) = (XCL_CV*1.3D9*EXP(-2.2D3*TFAC)*PHI2_CV)
  RCONST(679) = (XCL_CV*1.1D9*PHI2_CV)
  RCONST(680) = (XCL_CV*1.7D9*PHI2_CV)
  RCONST(681) = (XCL_CV*2.2D8*EXP(-2.6D3*TFAC)*PHI2_CV)
  RCONST(682) = (XCL_CV*7.1D6*PHI2_CV*PHI2_CV)
  RCONST(683) = (XCL_CV*4.6D2*EXP(-1.1D3*TFAC)*PHI2_CV)
  RCONST(684) = (XCL_CV*4.6D2*EXP(-1.1D3*TFAC)*PHI2_CV)
  RCONST(685) = (XCL_CV*5.0D5*PHI2_CV)
  RCONST(686) = (XCL_CV*7.9D2*EXP(-2.9D3*TFAC)*PHI2_CV)
  RCONST(687) = (XCL_CV*2.5D7*EXP(-2.45D3*TFAC)*PHI2_CV)
  RCONST(688) = (XCL_CV*7.7D-3*EXP(-9.2E3*TFAC))
  RCONST(689) = (XCL_CV*3.7D3*PHI2_CV)
  RCONST(690) = (XCL_CV*3.0D8*PHI2_CV)
  RCONST(691) = (XCL_CV*1.9D7*EXP(-3.8E3*TFAC)*PHI2_CV*PHI2_CV)
  RCONST(692) = (XCL_CV*3.6D7*EXP(-4.0E3*TFAC)*PHI2_CV*PHI2_CV)
  RCONST(693) = (XCL_CV*7.0D2*PHI2_CV)
  RCONST(694) = (XCL_CV*3.4D9*EXP(-1.2D3*TFAC)*PHI2_CV)
  RCONST(695) = (XCL_CV*5.0D8*PHI2_CV)
  RCONST(696) = (XCL_CV*1.0D9*PHI2_CV)
  RCONST(697) = (XCL_CV*6.0D8*PHI2_CV)
  RCONST(698) = (XCL_CV*8.6D8*PHI2_CV)
  RCONST(699) = (XCL_CV*1.1D9*EXP(-1.516D3*TFAC)*PHI2_CV)
  RCONST(700) = (XCL_CV*1.5D8*PHI2_CV)
  RCONST(701) = (XCL_CV*1.2D9*PHI2_CV)
  RCONST(702) = (XCL_CV*1.4D6*PHI2_CV)
  RCONST(703) = (XCL_CV*4.7D7*PHI2_CV)
  RCONST(704) = (XCL_CV*7.7D6*PHI2_CV)
  RCONST(705) = (XCL_CV*7.0D8*PHI2_CV)
  RCONST(706) = (XCL_CV*6.0D7*PHI2_CV)
  RCONST(707) = (XCL_CV*6.0D7*PHI2_CV)
  RCONST(708) = (XCL_CV*1.6D7*PHI2_CV)
  RCONST(709) = (XCL_CV*8.5D7*PHI2_CV)
  RCONST(710) = (XCL_CV*1.1D9*EXP(-1.02D3*TFAC)*PHI2_CV)
  RCONST(711) = (XCL_CV*1.2D8*EXP(-9.9D2*TFAC)*PHI2_CV)
  RCONST(712) = (XCL_CV*1.0*RJCELL(IJ_H2O2_IUPAC10))
  RCONST(713) = (XCL_CV*KIEPOX(9.0D-4,1.31D-5,0,'CV'))
  RCONST(714) = (XCL_CV*KIEPOX(8.83D-3,2.92D-6,0,'CV'))
  RCONST(715) = (XCL_CV*KIEPOX(2.0D-4,2.92D-6,0,'CV'))
  RCONST(716) = (XCL_CV*CFRAC_CV*KPP_ALFA3_CV)
  RCONST(717) = (XCL_CV*CFRAC_CV*KPP_ALFA3_CV)
  RCONST(718) = (XCL_CV*CFRAC_CV*KPP_ALFA3_CV)
  RCONST(719) = (XCL_CV*CFRAC_CV*KPP_ALFA3_CV)
  RCONST(720) = (XCL_CV*WFAC_CV)
  RCONST(721) = (XCL_CV*WFAC_CV)
  RCONST(722) = (XCL_CV*WFAC_CV)
  RCONST(723) = (XCL_CV*WFAC_CV)
  RCONST(724) = (XCL_CV*WFAC_CV)
  RCONST(725) = (XCL_CV*WFAC_CV)
  RCONST(726) = (XCL_CV*WFAC_CV)
  RCONST(727) = (XCL_CV*WFAC_CV)
  RCONST(728) = (XCL_CV*WFAC_CV)
  RCONST(729) = (XCL_CV*WFAC_CV)
  RCONST(730) = (XCL_CV*WFAC_CV)
  RCONST(731) = (XCL_CV*WFAC_CV)
  RCONST(732) = (XCL_CV*WFAC_CV)
  RCONST(733) = (XCL_CV*WFAC_CV)
  RCONST(734) = (XCL_CV*WFAC_CV)
  RCONST(735) = (XCL_CV*WFAC_CV)
  RCONST(736) = (XCL_CV*WFAC_CV)
  RCONST(737) = (XCL_CV*WFAC_CV)
  RCONST(738) = (XCL_CV*WFAC_CV)
  RCONST(739) = (XCL_CV*WFAC_CV)
  RCONST(740) = (XCL_CV*WFAC_CV)
  RCONST(741) = (XCL_CV*WFAC_CV)
  RCONST(742) = (XCL_CV*WFAC_CV)
  RCONST(743) = (XCL_CV*WFAC_CV)
  RCONST(744) = (XCL_CV*WFAC_CV)
  RCONST(745) = (XCL_CV*WFAC_CV)
  RCONST(746) = (XCL_CV*WFAC_CV)
  RCONST(747) = (XCL_CV*WFAC_CV)
  RCONST(748) = (XCL_CV*WFAC_CV)
  RCONST(749) = (XCL_CV*WFAC_CV)
  RCONST(750) = (XCL_CV*WFAC_CV)
  RCONST(751) = (XCL_CV*WFAC_CV)
  RCONST(752) = (XCL_CV*WFAC_CV)
  RCONST(753) = (XCL_CV*WFAC_CV)
  RCONST(754) = (XCL_CV*WFAC_CV)
  RCONST(755) = (XCL_CV*WFAC_CV)
  RCONST(756) = (XCL_CV*WFAC_CV)
  RCONST(757) = (XCL_CV*WFAC_CV)
  RCONST(758) = (XCL_CV*WFAC_CV)
  RCONST(759) = (XCL_CV*WFAC_CV)
  RCONST(760) = (XCL_CV*WFAC_CV)
  RCONST(761) = (XCL_CV*WFAC_CV)
  RCONST(762) = (XCL_CV*WFAC_CV)
  RCONST(763) = (XCL_CV*WFAC_CV)
  RCONST(764) = (XCL_CV*WFAC_CV)
  RCONST(765) = (XCL_CV*WFAC_CV)
  RCONST(766) = (XCL_CV*WFAC_CV)
  RCONST(767) = (XCL_CV*WFAC_CV)
  RCONST(768) = (XCL_CV*WFAC_CV)
  RCONST(769) = (XCL_CV*WFAC_CV)
  RCONST(770) = (XCL_CV*WFAC_CV)
  RCONST(771) = (XCL_CV*WFAC_CV)
  RCONST(772) = (XCL_CV*WFAC_CV)
  RCONST(773) = (XCL_CV*WFAC_CV)
  RCONST(774) = (XCL_CV*WFAC_CV)
  RCONST(775) = (XCL_CV*WFAC_CV)
  RCONST(776) = (XCL_CV*WFAC_CV)
  RCONST(777) = (XCL_CV*WFAC_CV)
  RCONST(778) = (KPP_RSCAV(IND_NO2))
  RCONST(779) = (KPP_RSCAV(IND_NO))
  RCONST(780) = (KPP_RSCAV(IND_O3))
  RCONST(781) = (KPP_RSCAV(IND_NO3))
  RCONST(782) = (KPP_RSCAV(IND_H2O2))
  RCONST(783) = (KPP_RSCAV(IND_N2O5))
  RCONST(784) = (KPP_RSCAV(IND_HNO3))
  RCONST(785) = (KPP_RSCAV(IND_HONO))
  RCONST(786) = (KPP_RSCAV(IND_PNA))
  RCONST(787) = (KPP_RSCAV(IND_SO2))
  RCONST(788) = (KPP_RSCAV(IND_SULF))
  RCONST(789) = (KPP_RSCAV(IND_PAN))
  RCONST(790) = (KPP_RSCAV(IND_PACD))
  RCONST(791) = (KPP_RSCAV(IND_AACD))
  RCONST(792) = (KPP_RSCAV(IND_ALD2))
  RCONST(793) = (KPP_RSCAV(IND_PANX))
  RCONST(794) = (KPP_RSCAV(IND_FORM))
  RCONST(795) = (KPP_RSCAV(IND_MEPX))
  RCONST(796) = (KPP_RSCAV(IND_MEOH))
  RCONST(797) = (KPP_RSCAV(IND_ROOH))
  RCONST(798) = (KPP_RSCAV(IND_NTR1))
  RCONST(799) = (KPP_RSCAV(IND_NTR2))
  RCONST(800) = (KPP_RSCAV(IND_FACD))
  RCONST(801) = (KPP_RSCAV(IND_CO))
  RCONST(802) = (KPP_RSCAV(IND_ALDX))
  RCONST(803) = (KPP_RSCAV(IND_GLYD))
  RCONST(804) = (KPP_RSCAV(IND_GLY))
  RCONST(805) = (KPP_RSCAV(IND_MGLY))
  RCONST(806) = (KPP_RSCAV(IND_ETHA))
  RCONST(807) = (KPP_RSCAV(IND_ETOH))
  RCONST(808) = (KPP_RSCAV(IND_KET))
  RCONST(809) = (KPP_RSCAV(IND_PAR))
  RCONST(810) = (KPP_RSCAV(IND_ACET))
  RCONST(811) = (KPP_RSCAV(IND_PRPA))
  RCONST(812) = (KPP_RSCAV(IND_ETHY))
  RCONST(813) = (KPP_RSCAV(IND_ETH))
  RCONST(814) = (KPP_RSCAV(IND_OLE))
  RCONST(815) = (KPP_RSCAV(IND_IOLE))
  RCONST(816) = (KPP_RSCAV(IND_ISOP))
  RCONST(817) = (KPP_RSCAV(IND_ISPD))
  RCONST(818) = (KPP_RSCAV(IND_INTR))
  RCONST(819) = (KPP_RSCAV(IND_ISPX))
  RCONST(820) = (KPP_RSCAV(IND_EPOX))
  RCONST(821) = (KPP_RSCAV(IND_TERP))
  RCONST(822) = (KPP_RSCAV(IND_APIN))
  RCONST(823) = (KPP_RSCAV(IND_MTNO3))
  RCONST(824) = (KPP_RSCAV(IND_BENZENE))
  RCONST(825) = (KPP_RSCAV(IND_CRES))
  RCONST(826) = (KPP_RSCAV(IND_OPEN))
  RCONST(827) = (KPP_RSCAV(IND_TOL))
  RCONST(828) = (KPP_RSCAV(IND_XOPN))
  RCONST(829) = (KPP_RSCAV(IND_XYLMN))
  RCONST(830) = (KPP_RSCAV(IND_NAPH))
  RCONST(831) = (KPP_RSCAV(IND_CAT1))
  RCONST(832) = (KPP_RSCAV(IND_CRON))
  RCONST(833) = (KPP_RSCAV(IND_OPAN))
  RCONST(834) = (KPP_RSCAV(IND_ECH4))
  RCONST(835) = (KPP_RSCAV(IND_CL2))
  RCONST(836) = (KPP_RSCAV(IND_HOCL))
  RCONST(837) = (KPP_RSCAV(IND_CLO))
  RCONST(838) = (KPP_RSCAV(IND_FMCL))
  RCONST(839) = (KPP_RSCAV(IND_HCL))
  RCONST(840) = (KPP_RSCAV(IND_CLNO2))
  RCONST(841) = (KPP_RSCAV(IND_CLNO3))
  RCONST(842) = (KPP_RSCAV(IND_SESQ))
  RCONST(843) = (KPP_RSCAV(IND_SOAALK))
  RCONST(844) = (KPP_RSCAV(IND_VLVPO1))
  RCONST(845) = (KPP_RSCAV(IND_VSVPO1))
  RCONST(846) = (KPP_RSCAV(IND_VSVPO2))
  RCONST(847) = (KPP_RSCAV(IND_VSVPO3))
  RCONST(848) = (KPP_RSCAV(IND_VIVPO1))
  RCONST(849) = (KPP_RSCAV(IND_VLVOO1))
  RCONST(850) = (KPP_RSCAV(IND_VLVOO2))
  RCONST(851) = (KPP_RSCAV(IND_VSVOO1))
  RCONST(852) = (KPP_RSCAV(IND_VSVOO2))
  RCONST(853) = (KPP_RSCAV(IND_VSVOO3))
  RCONST(854) = (KPP_RSCAV(IND_PCVOC))
  RCONST(855) = (KPP_RSCAV(IND_FORM_PRIMARY))
  RCONST(856) = (KPP_RSCAV(IND_ALD2_PRIMARY))
  RCONST(857) = (KPP_RSCAV(IND_BUTADIENE13))
  RCONST(858) = (KPP_RSCAV(IND_ACROLEIN))
  RCONST(859) = (KPP_RSCAV(IND_ACRO_PRIMARY))
  RCONST(860) = (KPP_RSCAV(IND_TOLU))
  RCONST(861) = (KPP_RSCAV(IND_HG))
  RCONST(862) = (KPP_RSCAV(IND_HGIIGAS))
  RCONST(863) = (KPP_RSCAV(IND_SVAVB1))
  RCONST(864) = (KPP_RSCAV(IND_SVAVB2))
  RCONST(865) = (KPP_RSCAV(IND_SVAVB3))
  RCONST(866) = (KPP_RSCAV(IND_SVAVB4))
  RCONST(867) = (KPP_RSCAV(IND_DMS))
  RCONST(868) = (KPP_RSCAV(IND_MSA))
  RCONST(869) = (KPP_RSCAV(IND_ASO4I))
  RCONST(870) = (KPP_RSCAV(IND_ASO4J))
  RCONST(871) = (KPP_RSCAV(IND_ANH4I))
  RCONST(872) = (KPP_RSCAV(IND_ANO3I))
  RCONST(873) = (KPP_RSCAV(IND_ACLI))
  RCONST(874) = (KPP_RSCAV(IND_ACLJ))
  RCONST(875) = (KPP_RSCAV(IND_ACLK))
  RCONST(876) = (KPP_RSCAV(IND_AISO1J))
  RCONST(877) = (KPP_RSCAV(IND_AISO2J))
  RCONST(878) = (KPP_RSCAV(IND_ASQTJ))
  RCONST(879) = (KPP_RSCAV(IND_AISO3J))
  RCONST(880) = (KPP_RSCAV(IND_AOLGAJ))
  RCONST(881) = (KPP_RSCAV(IND_AOLGBJ))
  RCONST(882) = (KPP_RSCAV(IND_AGLYJ))
  RCONST(883) = (KPP_RSCAV(IND_AMTNO3J))
  RCONST(884) = (KPP_RSCAV(IND_AMTHYDJ))
  RCONST(885) = (KPP_RSCAV(IND_APOCI))
  RCONST(886) = (KPP_RSCAV(IND_APOCJ))
  RCONST(887) = (KPP_RSCAV(IND_APNCOMI))
  RCONST(888) = (KPP_RSCAV(IND_APNCOMJ))
  RCONST(889) = (KPP_RSCAV(IND_AAVB2J))
  RCONST(890) = (KPP_RSCAV(IND_AAVB3J))
  RCONST(891) = (KPP_RSCAV(IND_AAVB4J))
  RCONST(892) = (KPP_RSCAV(IND_NH3))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE mchem_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mchem_Rates

