! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Auxiliary Routines File
! 
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : mchem_Util.F90
! Equation file        : mchem.kpp
! Output root filename : mchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mchem_Util

  USE mchem_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! UTIL - Utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE mchem_Parameters

      open(10, file='mchem.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!                            
! SaveData - Write LOOKAT species in the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE mchem_Global
      USE mchem_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
      (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
 999  FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE mchem_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE mchem_Parameters
      USE mchem_Global
      USE mchem_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='mchem.m')
      write(20,*) 'load mchem.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = mchem;')
      write(20,*) 'clear mchem;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! ****************************************************************
!
! Integrator_Update_Options - determine whether to call Update_RCONST,
!    Update_PHOTO, and Update_SUN from within the integrator
!
!   Parameters:
!    option (input)
!        = -1 :  Do not call Update_* functions within the integrator
!        =  0 :  Status quo: Call whichever functions are normally called
!        =  1 :  Call Update_RCONST from within the integrator
!        =  2 :  Call Update_PHOTO from within the integrator
!        =  3 :  Call Update_RCONST and Update_PHOTO from within the int.
!        =  4 :  Call Update_SUN from within the integrator
!        =  5 :  Call Update_SUN and Update_RCONST from within the int.
!        =  6 :  not implemented
!        =  7 :  not implemented
!
!    Do_Update_RCONST (output):
!        =T : Calls Update_RCONST from within the integrator
!        =F : Does not call UPDATE_RCONST from w/in the int.
!
!    Do_Update_PHOTO (output):
!        =T : Calls Update_PHOTO from within the integrator
!        =F : Does not call UPDATE_PHOTO from w/in the int.
!
!    Do_Update_SUN (output):
!        =T : Calls Update_SUN from within the integrator
!        =F : Does not call UPDATE_SUN from w/in the int.
!
! ****************************************************************

      SUBROUTINE Integrator_Update_Options( option,            &
                                            Do_Update_RConst,  &
                                            Do_Update_Photo,   &
                                            Do_Update_Sun     )

      !~~~> Input variables
      INTEGER, INTENT(IN)  :: option

      !~~~> Output variables
      LOGICAL, INTENT(OUT) :: Do_Update_RCONST
      LOGICAL, INTENT(OUT) :: Do_Update_PHOTO
      LOGICAL, INTENT(OUT) :: Do_Update_SUN

      ! Option -1: turn off all Update_* calls within the integrator
      IF ( option == -1 ) THEN
         Do_Update_RCONST = .FALSE.
         Do_Update_PHOTO  = .FALSE.
         Do_Update_SUN    = .FALSE.
         RETURN
      ENDIF

      ! Otherwise determine from the value passed
      Do_Update_RCONST = ( IAND( option, 1 ) > 0 )
      Do_Update_PHOTO  = ( IAND( option, 2 ) > 0 )
      Do_Update_SUN    = ( IAND( option, 4 ) > 0 )

      END SUBROUTINE Integrator_Update_Options

! End of Integrator_Update_Options function
! ****************************************************************
! ****************************************************************
!                            
! tag2num - convert equation tags to kpp reaction number
!   Arguments :
!      id        - string with the equation tag
!
! ****************************************************************

ELEMENTAL INTEGER FUNCTION tag2num ( id )

  USE mchem_Monitor, ONLY: EQN_TAGS

  CHARACTER(LEN=*), INTENT(IN) :: id
  INTEGER i

  tag2num = 0 ! mz_rs_20050115
  DO i = 1, SIZE(EQN_TAGS)
    IF (TRIM(EQN_TAGS(i)) == TRIM(id)) THEN
      tag2num = i ! mz_rs_20050115
      EXIT
    ENDIF
  END DO

END FUNCTION tag2num

! End of tag2num function
! ****************************************************************

! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(408) = V_USER(1)
  V(388) = V_USER(2)
  V(384) = V_USER(3)
  V(385) = V_USER(4)
  V(405) = V_USER(5)
  V(31) = V_USER(6)
  V(209) = V_USER(7)
  V(411) = V_USER(8)
  V(395) = V_USER(9)
  V(418) = V_USER(10)
  V(293) = V_USER(11)
  V(373) = V_USER(12)
  V(412) = V_USER(13)
  V(326) = V_USER(14)
  V(376) = V_USER(15)
  V(214) = V_USER(16)
  V(32) = V_USER(17)
  V(389) = V_USER(18)
  V(391) = V_USER(19)
  V(390) = V_USER(20)
  V(243) = V_USER(21)
  V(410) = V_USER(22)
  V(355) = V_USER(23)
  V(379) = V_USER(24)
  V(372) = V_USER(25)
  V(370) = V_USER(26)
  V(311) = V_USER(27)
  V(397) = V_USER(28)
  V(359) = V_USER(29)
  V(318) = V_USER(30)
  V(321) = V_USER(31)
  V(371) = V_USER(32)
  V(367) = V_USER(33)
  V(322) = V_USER(34)
  V(282) = V_USER(35)
  V(407) = V_USER(36)
  V(342) = V_USER(37)
  V(313) = V_USER(38)
  V(369) = V_USER(39)
  V(409) = V_USER(40)
  V(393) = V_USER(41)
  V(400) = V_USER(42)
  V(269) = V_USER(43)
  V(285) = V_USER(44)
  V(233) = V_USER(45)
  V(382) = V_USER(46)
  V(331) = V_USER(47)
  V(292) = V_USER(48)
  V(249) = V_USER(49)
  V(312) = V_USER(50)
  V(344) = V_USER(51)
  V(225) = V_USER(52)
  V(353) = V_USER(53)
  V(375) = V_USER(54)
  V(368) = V_USER(55)
  V(360) = V_USER(56)
  V(378) = V_USER(57)
  V(33) = V_USER(58)
  V(380) = V_USER(59)
  V(336) = V_USER(60)
  V(286) = V_USER(61)
  V(234) = V_USER(62)
  V(377) = V_USER(63)
  V(339) = V_USER(64)
  V(365) = V_USER(65)
  V(345) = V_USER(66)
  V(34) = V_USER(67)
  V(119) = V_USER(68)
  V(346) = V_USER(69)
  V(227) = V_USER(70)
  V(362) = V_USER(71)
  V(337) = V_USER(72)
  V(358) = V_USER(73)
  V(177) = V_USER(74)
  V(287) = V_USER(75)
  V(350) = V_USER(76)
  V(176) = V_USER(77)
  V(361) = V_USER(78)
  V(288) = V_USER(79)
  V(349) = V_USER(80)
  V(178) = V_USER(81)
  V(289) = V_USER(82)
  V(179) = V_USER(83)
  V(315) = V_USER(84)
  V(290) = V_USER(85)
  V(338) = V_USER(86)
  V(291) = V_USER(87)
  V(212) = V_USER(88)
  V(203) = V_USER(89)
  V(392) = V_USER(90)
  V(229) = V_USER(91)
  V(354) = V_USER(92)
  V(316) = V_USER(93)
  V(343) = V_USER(94)
  V(217) = V_USER(95)
  V(252) = V_USER(96)
  V(171) = V_USER(97)
  V(175) = V_USER(98)
  V(173) = V_USER(99)
  V(169) = V_USER(100)
  V(138) = V_USER(101)
  V(35) = V_USER(102)
  V(180) = V_USER(103)
  V(226) = V_USER(104)
  V(208) = V_USER(105)
  V(216) = V_USER(106)
  V(206) = V_USER(107)
  V(207) = V_USER(108)
  V(205) = V_USER(109)
  V(204) = V_USER(110)
  V(72) = V_USER(111)
  V(191) = V_USER(112)
  V(118) = V_USER(113)
  V(1) = V_USER(114)
  V(2) = V_USER(115)
  V(3) = V_USER(116)
  V(6) = V_USER(117)
  V(4) = V_USER(118)
  V(5) = V_USER(119)
  V(7) = V_USER(120)
  V(10) = V_USER(121)
  V(8) = V_USER(122)
  V(9) = V_USER(123)
  V(11) = V_USER(124)
  V(197) = V_USER(125)
  V(12) = V_USER(126)
  V(199) = V_USER(127)
  V(151) = V_USER(128)
  V(36) = V_USER(129)
  V(304) = V_USER(130)
  V(305) = V_USER(131)
  V(246) = V_USER(132)
  V(306) = V_USER(133)
  V(301) = V_USER(134)
  V(302) = V_USER(135)
  V(303) = V_USER(136)
  V(307) = V_USER(137)
  V(308) = V_USER(138)
  V(309) = V_USER(139)
  V(153) = V_USER(140)
  V(155) = V_USER(141)
  V(159) = V_USER(142)
  V(158) = V_USER(143)
  V(161) = V_USER(144)
  V(163) = V_USER(145)
  V(167) = V_USER(146)
  V(37) = V_USER(147)
  V(166) = V_USER(148)
  V(323) = V_USER(149)
  V(183) = V_USER(150)
  V(223) = V_USER(151)
  V(329) = V_USER(152)
  V(330) = V_USER(153)
  V(258) = V_USER(154)
  V(259) = V_USER(155)
  V(239) = V_USER(156)
  V(240) = V_USER(157)
  V(222) = V_USER(160)
  V(224) = V_USER(161)
  V(332) = V_USER(162)
  V(333) = V_USER(163)
  V(398) = V_USER(164)
  V(394) = V_USER(165)
  V(320) = V_USER(166)
  V(319) = V_USER(167)
  V(231) = V_USER(168)
  V(232) = V_USER(169)
  V(253) = V_USER(170)
  V(263) = V_USER(171)
  V(247) = V_USER(172)
  V(248) = V_USER(173)
  V(386) = V_USER(174)
  V(387) = V_USER(175)
  V(237) = V_USER(176)
  V(238) = V_USER(177)
  V(374) = V_USER(178)
  V(381) = V_USER(179)
  V(401) = V_USER(180)
  V(399) = V_USER(181)
  V(297) = V_USER(182)
  V(310) = V_USER(183)
  V(402) = V_USER(184)
  V(366) = V_USER(185)
  V(244) = V_USER(186)
  V(245) = V_USER(187)
  V(314) = V_USER(188)
  V(317) = V_USER(189)
  V(334) = V_USER(190)
  V(335) = V_USER(191)
  V(294) = V_USER(192)
  V(295) = V_USER(193)
  V(264) = V_USER(194)
  V(265) = V_USER(195)
  V(241) = V_USER(196)
  V(242) = V_USER(197)
  V(283) = V_USER(198)
  V(284) = V_USER(199)
  V(255) = V_USER(200)
  V(268) = V_USER(201)
  V(356) = V_USER(202)
  V(357) = V_USER(203)
  V(413) = V_USER(204)
  V(414) = V_USER(205)
  V(383) = V_USER(206)
  V(415) = V_USER(207)
  V(406) = V_USER(208)
  V(416) = V_USER(209)
  V(363) = V_USER(210)
  V(364) = V_USER(211)
  V(396) = V_USER(212)
  V(417) = V_USER(213)
  V(219) = V_USER(214)
  V(218) = V_USER(215)
  V(221) = V_USER(216)
  V(215) = V_USER(217)
  V(220) = V_USER(218)
  V(213) = V_USER(219)
  V(230) = V_USER(220)
  V(228) = V_USER(221)
  V(270) = V_USER(222)
  V(271) = V_USER(223)
  V(403) = V_USER(224)
  V(404) = V_USER(225)
  V(273) = V_USER(226)
  V(274) = V_USER(227)
  V(340) = V_USER(228)
  V(341) = V_USER(229)
  V(254) = V_USER(230)
  V(256) = V_USER(231)
  V(351) = V_USER(232)
  V(352) = V_USER(233)
  V(210) = V_USER(234)
  V(211) = V_USER(235)
  V(235) = V_USER(236)
  V(236) = V_USER(237)
  V(296) = V_USER(238)
  V(299) = V_USER(239)
  V(257) = V_USER(240)
  V(262) = V_USER(241)
  V(348) = V_USER(242)
  V(347) = V_USER(243)
  V(38) = V_USER(244)
  V(39) = V_USER(245)
  V(327) = V_USER(246)
  V(324) = V_USER(247)
  V(328) = V_USER(248)
  V(325) = V_USER(249)
  V(260) = V_USER(250)
  V(261) = V_USER(251)
  V(266) = V_USER(252)
  V(267) = V_USER(253)
  V(250) = V_USER(254)
  V(251) = V_USER(255)
  V(272) = V_USER(256)
  V(277) = V_USER(257)
  V(278) = V_USER(258)
  V(279) = V_USER(259)
  V(275) = V_USER(260)
  V(280) = V_USER(261)
  V(276) = V_USER(262)
  V(281) = V_USER(263)
  V(298) = V_USER(264)
  V(300) = V_USER(265)
  V(46) = V_USER(266)
  V(47) = V_USER(267)
  V(73) = V_USER(268)
  V(74) = V_USER(269)
  V(13) = V_USER(270)
  V(14) = V_USER(271)
  V(15) = V_USER(286)
  V(16) = V_USER(287)
  V(17) = V_USER(288)
  V(18) = V_USER(289)
  V(29) = V_USER(290)
  V(30) = V_USER(291)
  V(19) = V_USER(292)
  V(20) = V_USER(293)
  V(21) = V_USER(294)
  V(22) = V_USER(295)
  V(23) = V_USER(296)
  V(24) = V_USER(297)
  V(40) = V_USER(298)
  V(41) = V_USER(299)
  V(42) = V_USER(300)
  V(43) = V_USER(301)
  V(44) = V_USER(302)
  V(45) = V_USER(303)
  V(48) = V_USER(304)
  V(49) = V_USER(305)
  V(50) = V_USER(306)
  V(51) = V_USER(307)
  V(52) = V_USER(308)
  V(53) = V_USER(309)
  V(54) = V_USER(310)
  V(55) = V_USER(311)
  V(56) = V_USER(312)
  V(57) = V_USER(313)
  V(58) = V_USER(314)
  V(59) = V_USER(315)
  V(60) = V_USER(316)
  V(61) = V_USER(317)
  V(62) = V_USER(318)
  V(63) = V_USER(319)
  V(64) = V_USER(320)
  V(65) = V_USER(321)
  V(66) = V_USER(322)
  V(67) = V_USER(323)
  V(68) = V_USER(324)
  V(69) = V_USER(325)
  V(70) = V_USER(326)
  V(71) = V_USER(327)
  V(75) = V_USER(328)
  V(76) = V_USER(329)
  V(77) = V_USER(330)
  V(78) = V_USER(331)
  V(79) = V_USER(332)
  V(80) = V_USER(333)
  V(81) = V_USER(341)
  V(82) = V_USER(342)
  V(83) = V_USER(343)
  V(84) = V_USER(344)
  V(85) = V_USER(345)
  V(86) = V_USER(346)
  V(87) = V_USER(347)
  V(25) = V_USER(348)
  V(26) = V_USER(349)
  V(27) = V_USER(350)
  V(28) = V_USER(351)
  V(88) = V_USER(352)
  V(89) = V_USER(353)
  V(90) = V_USER(354)
  V(91) = V_USER(355)
  V(92) = V_USER(356)
  V(93) = V_USER(357)
  V(94) = V_USER(358)
  V(95) = V_USER(359)
  V(96) = V_USER(360)
  V(97) = V_USER(361)
  V(98) = V_USER(362)
  V(99) = V_USER(363)
  V(100) = V_USER(364)
  V(101) = V_USER(365)
  V(102) = V_USER(366)
  V(103) = V_USER(367)
  V(104) = V_USER(368)
  V(105) = V_USER(369)
  V(106) = V_USER(370)
  V(107) = V_USER(371)
  V(108) = V_USER(372)
  V(109) = V_USER(373)
  V(110) = V_USER(374)
  V(111) = V_USER(375)
  V(112) = V_USER(376)
  V(113) = V_USER(377)
  V(114) = V_USER(378)
  V(115) = V_USER(379)
  V(116) = V_USER(380)
  V(117) = V_USER(381)
  V(120) = V_USER(382)
  V(121) = V_USER(383)
  V(122) = V_USER(384)
  V(123) = V_USER(385)
  V(124) = V_USER(386)
  V(125) = V_USER(387)
  V(126) = V_USER(388)
  V(127) = V_USER(389)
  V(128) = V_USER(390)
  V(129) = V_USER(391)
  V(130) = V_USER(392)
  V(131) = V_USER(393)
  V(132) = V_USER(394)
  V(133) = V_USER(395)
  V(134) = V_USER(396)
  V(135) = V_USER(397)
  V(136) = V_USER(398)
  V(137) = V_USER(399)
  V(139) = V_USER(400)
  V(140) = V_USER(401)
  V(141) = V_USER(402)
  V(142) = V_USER(403)
  V(143) = V_USER(404)
  V(144) = V_USER(405)
  V(145) = V_USER(406)
  V(146) = V_USER(407)
  V(147) = V_USER(408)
  V(148) = V_USER(409)
  V(149) = V_USER(410)
  V(150) = V_USER(411)
  V(152) = V_USER(412)
  V(154) = V_USER(413)
  V(156) = V_USER(414)
  V(157) = V_USER(415)
  V(160) = V_USER(416)
      
END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(408)
  V_USER(2) = V(388)
  V_USER(3) = V(384)
  V_USER(4) = V(385)
  V_USER(5) = V(405)
  V_USER(6) = V(31)
  V_USER(7) = V(209)
  V_USER(8) = V(411)
  V_USER(9) = V(395)
  V_USER(10) = V(418)
  V_USER(11) = V(293)
  V_USER(12) = V(373)
  V_USER(13) = V(412)
  V_USER(14) = V(326)
  V_USER(15) = V(376)
  V_USER(16) = V(214)
  V_USER(17) = V(32)
  V_USER(18) = V(389)
  V_USER(19) = V(391)
  V_USER(20) = V(390)
  V_USER(21) = V(243)
  V_USER(22) = V(410)
  V_USER(23) = V(355)
  V_USER(24) = V(379)
  V_USER(25) = V(372)
  V_USER(26) = V(370)
  V_USER(27) = V(311)
  V_USER(28) = V(397)
  V_USER(29) = V(359)
  V_USER(30) = V(318)
  V_USER(31) = V(321)
  V_USER(32) = V(371)
  V_USER(33) = V(367)
  V_USER(34) = V(322)
  V_USER(35) = V(282)
  V_USER(36) = V(407)
  V_USER(37) = V(342)
  V_USER(38) = V(313)
  V_USER(39) = V(369)
  V_USER(40) = V(409)
  V_USER(41) = V(393)
  V_USER(42) = V(400)
  V_USER(43) = V(269)
  V_USER(44) = V(285)
  V_USER(45) = V(233)
  V_USER(46) = V(382)
  V_USER(47) = V(331)
  V_USER(48) = V(292)
  V_USER(49) = V(249)
  V_USER(50) = V(312)
  V_USER(51) = V(344)
  V_USER(52) = V(225)
  V_USER(53) = V(353)
  V_USER(54) = V(375)
  V_USER(55) = V(368)
  V_USER(56) = V(360)
  V_USER(57) = V(378)
  V_USER(58) = V(33)
  V_USER(59) = V(380)
  V_USER(60) = V(336)
  V_USER(61) = V(286)
  V_USER(62) = V(234)
  V_USER(63) = V(377)
  V_USER(64) = V(339)
  V_USER(65) = V(365)
  V_USER(66) = V(345)
  V_USER(67) = V(34)
  V_USER(68) = V(119)
  V_USER(69) = V(346)
  V_USER(70) = V(227)
  V_USER(71) = V(362)
  V_USER(72) = V(337)
  V_USER(73) = V(358)
  V_USER(74) = V(177)
  V_USER(75) = V(287)
  V_USER(76) = V(350)
  V_USER(77) = V(176)
  V_USER(78) = V(361)
  V_USER(79) = V(288)
  V_USER(80) = V(349)
  V_USER(81) = V(178)
  V_USER(82) = V(289)
  V_USER(83) = V(179)
  V_USER(84) = V(315)
  V_USER(85) = V(290)
  V_USER(86) = V(338)
  V_USER(87) = V(291)
  V_USER(88) = V(212)
  V_USER(89) = V(203)
  V_USER(90) = V(392)
  V_USER(91) = V(229)
  V_USER(92) = V(354)
  V_USER(93) = V(316)
  V_USER(94) = V(343)
  V_USER(95) = V(217)
  V_USER(96) = V(252)
  V_USER(97) = V(171)
  V_USER(98) = V(175)
  V_USER(99) = V(173)
  V_USER(100) = V(169)
  V_USER(101) = V(138)
  V_USER(102) = V(35)
  V_USER(103) = V(180)
  V_USER(104) = V(226)
  V_USER(105) = V(208)
  V_USER(106) = V(216)
  V_USER(107) = V(206)
  V_USER(108) = V(207)
  V_USER(109) = V(205)
  V_USER(110) = V(204)
  V_USER(111) = V(72)
  V_USER(112) = V(191)
  V_USER(113) = V(118)
  V_USER(114) = V(1)
  V_USER(115) = V(2)
  V_USER(116) = V(3)
  V_USER(117) = V(6)
  V_USER(118) = V(4)
  V_USER(119) = V(5)
  V_USER(120) = V(7)
  V_USER(121) = V(10)
  V_USER(122) = V(8)
  V_USER(123) = V(9)
  V_USER(124) = V(11)
  V_USER(125) = V(197)
  V_USER(126) = V(12)
  V_USER(127) = V(199)
  V_USER(128) = V(151)
  V_USER(129) = V(36)
  V_USER(130) = V(304)
  V_USER(131) = V(305)
  V_USER(132) = V(246)
  V_USER(133) = V(306)
  V_USER(134) = V(301)
  V_USER(135) = V(302)
  V_USER(136) = V(303)
  V_USER(137) = V(307)
  V_USER(138) = V(308)
  V_USER(139) = V(309)
  V_USER(140) = V(153)
  V_USER(141) = V(155)
  V_USER(142) = V(159)
  V_USER(143) = V(158)
  V_USER(144) = V(161)
  V_USER(145) = V(163)
  V_USER(146) = V(167)
  V_USER(147) = V(37)
  V_USER(148) = V(166)
  V_USER(149) = V(323)
  V_USER(150) = V(183)
  V_USER(151) = V(223)
  V_USER(152) = V(329)
  V_USER(153) = V(330)
  V_USER(154) = V(258)
  V_USER(155) = V(259)
  V_USER(156) = V(239)
  V_USER(157) = V(240)
  V_USER(160) = V(222)
  V_USER(161) = V(224)
  V_USER(162) = V(332)
  V_USER(163) = V(333)
  V_USER(164) = V(398)
  V_USER(165) = V(394)
  V_USER(166) = V(320)
  V_USER(167) = V(319)
  V_USER(168) = V(231)
  V_USER(169) = V(232)
  V_USER(170) = V(253)
  V_USER(171) = V(263)
  V_USER(172) = V(247)
  V_USER(173) = V(248)
  V_USER(174) = V(386)
  V_USER(175) = V(387)
  V_USER(176) = V(237)
  V_USER(177) = V(238)
  V_USER(178) = V(374)
  V_USER(179) = V(381)
  V_USER(180) = V(401)
  V_USER(181) = V(399)
  V_USER(182) = V(297)
  V_USER(183) = V(310)
  V_USER(184) = V(402)
  V_USER(185) = V(366)
  V_USER(186) = V(244)
  V_USER(187) = V(245)
  V_USER(188) = V(314)
  V_USER(189) = V(317)
  V_USER(190) = V(334)
  V_USER(191) = V(335)
  V_USER(192) = V(294)
  V_USER(193) = V(295)
  V_USER(194) = V(264)
  V_USER(195) = V(265)
  V_USER(196) = V(241)
  V_USER(197) = V(242)
  V_USER(198) = V(283)
  V_USER(199) = V(284)
  V_USER(200) = V(255)
  V_USER(201) = V(268)
  V_USER(202) = V(356)
  V_USER(203) = V(357)
  V_USER(204) = V(413)
  V_USER(205) = V(414)
  V_USER(206) = V(383)
  V_USER(207) = V(415)
  V_USER(208) = V(406)
  V_USER(209) = V(416)
  V_USER(210) = V(363)
  V_USER(211) = V(364)
  V_USER(212) = V(396)
  V_USER(213) = V(417)
  V_USER(214) = V(219)
  V_USER(215) = V(218)
  V_USER(216) = V(221)
  V_USER(217) = V(215)
  V_USER(218) = V(220)
  V_USER(219) = V(213)
  V_USER(220) = V(230)
  V_USER(221) = V(228)
  V_USER(222) = V(270)
  V_USER(223) = V(271)
  V_USER(224) = V(403)
  V_USER(225) = V(404)
  V_USER(226) = V(273)
  V_USER(227) = V(274)
  V_USER(228) = V(340)
  V_USER(229) = V(341)
  V_USER(230) = V(254)
  V_USER(231) = V(256)
  V_USER(232) = V(351)
  V_USER(233) = V(352)
  V_USER(234) = V(210)
  V_USER(235) = V(211)
  V_USER(236) = V(235)
  V_USER(237) = V(236)
  V_USER(238) = V(296)
  V_USER(239) = V(299)
  V_USER(240) = V(257)
  V_USER(241) = V(262)
  V_USER(242) = V(348)
  V_USER(243) = V(347)
  V_USER(244) = V(38)
  V_USER(245) = V(39)
  V_USER(246) = V(327)
  V_USER(247) = V(324)
  V_USER(248) = V(328)
  V_USER(249) = V(325)
  V_USER(250) = V(260)
  V_USER(251) = V(261)
  V_USER(252) = V(266)
  V_USER(253) = V(267)
  V_USER(254) = V(250)
  V_USER(255) = V(251)
  V_USER(256) = V(272)
  V_USER(257) = V(277)
  V_USER(258) = V(278)
  V_USER(259) = V(279)
  V_USER(260) = V(275)
  V_USER(261) = V(280)
  V_USER(262) = V(276)
  V_USER(263) = V(281)
  V_USER(264) = V(298)
  V_USER(265) = V(300)
  V_USER(266) = V(46)
  V_USER(267) = V(47)
  V_USER(268) = V(73)
  V_USER(269) = V(74)
  V_USER(270) = V(13)
  V_USER(271) = V(14)
  V_USER(286) = V(15)
  V_USER(287) = V(16)
  V_USER(288) = V(17)
  V_USER(289) = V(18)
  V_USER(290) = V(29)
  V_USER(291) = V(30)
  V_USER(292) = V(19)
  V_USER(293) = V(20)
  V_USER(294) = V(21)
  V_USER(295) = V(22)
  V_USER(296) = V(23)
  V_USER(297) = V(24)
  V_USER(298) = V(40)
  V_USER(299) = V(41)
  V_USER(300) = V(42)
  V_USER(301) = V(43)
  V_USER(302) = V(44)
  V_USER(303) = V(45)
  V_USER(304) = V(48)
  V_USER(305) = V(49)
  V_USER(306) = V(50)
  V_USER(307) = V(51)
  V_USER(308) = V(52)
  V_USER(309) = V(53)
  V_USER(310) = V(54)
  V_USER(311) = V(55)
  V_USER(312) = V(56)
  V_USER(313) = V(57)
  V_USER(314) = V(58)
  V_USER(315) = V(59)
  V_USER(316) = V(60)
  V_USER(317) = V(61)
  V_USER(318) = V(62)
  V_USER(319) = V(63)
  V_USER(320) = V(64)
  V_USER(321) = V(65)
  V_USER(322) = V(66)
  V_USER(323) = V(67)
  V_USER(324) = V(68)
  V_USER(325) = V(69)
  V_USER(326) = V(70)
  V_USER(327) = V(71)
  V_USER(328) = V(75)
  V_USER(329) = V(76)
  V_USER(330) = V(77)
  V_USER(331) = V(78)
  V_USER(332) = V(79)
  V_USER(333) = V(80)
  V_USER(341) = V(81)
  V_USER(342) = V(82)
  V_USER(343) = V(83)
  V_USER(344) = V(84)
  V_USER(345) = V(85)
  V_USER(346) = V(86)
  V_USER(347) = V(87)
  V_USER(348) = V(25)
  V_USER(349) = V(26)
  V_USER(350) = V(27)
  V_USER(351) = V(28)
  V_USER(352) = V(88)
  V_USER(353) = V(89)
  V_USER(354) = V(90)
  V_USER(355) = V(91)
  V_USER(356) = V(92)
  V_USER(357) = V(93)
  V_USER(358) = V(94)
  V_USER(359) = V(95)
  V_USER(360) = V(96)
  V_USER(361) = V(97)
  V_USER(362) = V(98)
  V_USER(363) = V(99)
  V_USER(364) = V(100)
  V_USER(365) = V(101)
  V_USER(366) = V(102)
  V_USER(367) = V(103)
  V_USER(368) = V(104)
  V_USER(369) = V(105)
  V_USER(370) = V(106)
  V_USER(371) = V(107)
  V_USER(372) = V(108)
  V_USER(373) = V(109)
  V_USER(374) = V(110)
  V_USER(375) = V(111)
  V_USER(376) = V(112)
  V_USER(377) = V(113)
  V_USER(378) = V(114)
  V_USER(379) = V(115)
  V_USER(380) = V(116)
  V_USER(381) = V(117)
  V_USER(382) = V(120)
  V_USER(383) = V(121)
  V_USER(384) = V(122)
  V_USER(385) = V(123)
  V_USER(386) = V(124)
  V_USER(387) = V(125)
  V_USER(388) = V(126)
  V_USER(389) = V(127)
  V_USER(390) = V(128)
  V_USER(391) = V(129)
  V_USER(392) = V(130)
  V_USER(393) = V(131)
  V_USER(394) = V(132)
  V_USER(395) = V(133)
  V_USER(396) = V(134)
  V_USER(397) = V(135)
  V_USER(398) = V(136)
  V_USER(399) = V(137)
  V_USER(400) = V(139)
  V_USER(401) = V(140)
  V_USER(402) = V(141)
  V_USER(403) = V(142)
  V_USER(404) = V(143)
  V_USER(405) = V(144)
  V_USER(406) = V(145)
  V_USER(407) = V(146)
  V_USER(408) = V(147)
  V_USER(409) = V(148)
  V_USER(410) = V(149)
  V_USER(411) = V(150)
  V_USER(412) = V(152)
  V_USER(413) = V(154)
  V_USER(414) = V(156)
  V_USER(415) = V(157)
  V_USER(416) = V(160)
      
END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)

      
END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mchem_Util

